mocks:
	go run go.uber.org/mock/mockgen@v0.4.0 -package mocks -source ./internal/domain/ports/card.go -destination ./test/mocks/card_mocks.go
	go run go.uber.org/mock/mockgen@v0.4.0 -package mocks -source ./internal/domain/ports/castle.go -destination ./test/mocks/castle_mocks.go
	go run go.uber.org/mock/mockgen@v0.4.0 -package mocks -source ./internal/domain/ports/deck.go -destination ./test/mocks/deck_mocks.go
	go run go.uber.org/mock/mockgen@v0.4.0 -package mocks -source ./internal/domain/ports/field.go -destination ./test/mocks/field_mocks.go
	go run go.uber.org/mock/mockgen@v0.4.0 -package mocks -source ./internal/domain/ports/hand.go -destination ./test/mocks/hand_mocks.go
	go run go.uber.org/mock/mockgen@v0.4.0 -package mocks -source ./internal/domain/ports/observers.go -destination ./test/mocks/observers_mocks.go
	go run go.uber.org/mock/mockgen@v0.4.0 -package mocks -source ./internal/domain/ports/player.go -destination ./test/mocks/player_mocks.go
	go run go.uber.org/mock/mockgen@v0.4.0 -package mocks -source ./internal/domain/ports/dealer.go -destination ./test/mocks/dealer_mocks.go
	go run go.uber.org/mock/mockgen@v0.4.0 -package mocks -source ./internal/domain/ports/cemetery.go -destination ./test/mocks/cemetery_mocks.go
	go run go.uber.org/mock/mockgen@v0.4.0 -package mocks -source ./internal/domain/ports/discardpile.go -destination ./test/mocks/discardpile_mocks.go
	go run go.uber.org/mock/mockgen@v0.4.0 -package domain -source ./internal/domain/gamestatusprovider.go -destination ./internal/domain/gamestatusprovider_mocks.go

