// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/domain/gamestatus/provider.go
//
// Generated by this command:
//
//	mockgen -package mocks -source ./internal/domain/gamestatus/provider.go -destination ./test/mocks/provider_mocks.go
//

// Package mocks is a generated GoMock package.
package domain

import (
	reflect "reflect"

	gamestatus "github.com/alelopezbcn/thecampaign/internal/domain/gamestatus"
	ports "github.com/alelopezbcn/thecampaign/internal/domain/ports"
	types "github.com/alelopezbcn/thecampaign/internal/domain/types"
	gomock "go.uber.org/mock/gomock"
)

// MockProvider is a mock of Provider interface.
type MockProvider struct {
	ctrl     *gomock.Controller
	recorder *MockProviderMockRecorder
}

// MockProviderMockRecorder is the mock recorder for MockProvider.
type MockProviderMockRecorder struct {
	mock *MockProvider
}

// NewMockProvider creates a new mock instance.
func NewMockProvider(ctrl *gomock.Controller) *MockProvider {
	mock := &MockProvider{ctrl: ctrl}
	mock.recorder = &MockProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProvider) EXPECT() *MockProviderMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockProvider) Get(currentPlayer, enemy ports.Player, action types.ActionType, canMove, canTrade bool, newCards ...ports.Card) gamestatus.GameStatus {
	m.ctrl.T.Helper()
	varargs := []any{currentPlayer, enemy, action, canMove, canTrade}
	for _, a := range newCards {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Get", varargs...)
	ret0, _ := ret[0].(gamestatus.GameStatus)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockProviderMockRecorder) Get(currentPlayer, enemy, action, canMove, canTrade any, newCards ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{currentPlayer, enemy, action, canMove, canTrade}, newCards...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockProvider)(nil).Get), varargs...)
}
