// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/domain/gamestatusprovider.go
//
// Generated by this command:
//
//	mockgen -package domain -source ./internal/domain/gamestatusprovider.go -destination ./internal/domain/gamestatusprovider_mocks.go
//

// Package domain is a generated GoMock package.
package domain

import (
	reflect "reflect"

	gamestatus "github.com/alelopezbcn/thecampaign/internal/domain/gamestatus"
	ports "github.com/alelopezbcn/thecampaign/internal/domain/ports"
	types "github.com/alelopezbcn/thecampaign/internal/domain/types"
	gomock "go.uber.org/mock/gomock"
)

// MockGameStatusProvider is a mock of GameStatusProvider interface.
type MockGameStatusProvider struct {
	ctrl     *gomock.Controller
	recorder *MockGameStatusProviderMockRecorder
}

// MockGameStatusProviderMockRecorder is the mock recorder for MockGameStatusProvider.
type MockGameStatusProviderMockRecorder struct {
	mock *MockGameStatusProvider
}

// NewMockGameStatusProvider creates a new mock instance.
func NewMockGameStatusProvider(ctrl *gomock.Controller) *MockGameStatusProvider {
	mock := &MockGameStatusProvider{ctrl: ctrl}
	mock.recorder = &MockGameStatusProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGameStatusProvider) EXPECT() *MockGameStatusProviderMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockGameStatusProvider) Get(currentPlayer, enemy ports.Player, action types.ActionType, canMove, canTrade bool, cemetery ports.Cemetery, newCards ...ports.Card) gamestatus.GameStatus {
	m.ctrl.T.Helper()
	varargs := []any{currentPlayer, enemy, action, canMove, canTrade, cemetery}
	for _, a := range newCards {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Get", varargs...)
	ret0, _ := ret[0].(gamestatus.GameStatus)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockGameStatusProviderMockRecorder) Get(currentPlayer, enemy, action, canMove, canTrade, cemetery any, newCards ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{currentPlayer, enemy, action, canMove, canTrade, cemetery}, newCards...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockGameStatusProvider)(nil).Get), varargs...)
}
