// Code generated by MockGen. DO NOT EDIT.
// Source: ./backend/internal/domain/gamestatusprovider.go
//
// Generated by this command:
//
//	mockgen -package domain -source ./backend/internal/domain/gamestatusprovider.go -destination ./backend/internal/domain/gamestatusprovider_mocks.go
//

// Package domain is a generated GoMock package.
package domain

import (
	reflect "reflect"

	ports "github.com/alelopezbcn/thecampaign/internal/domain/ports"
	gomock "go.uber.org/mock/gomock"
)

// MockGameStatusProvider is a mock of GameStatusProvider interface.
type MockGameStatusProvider struct {
	ctrl     *gomock.Controller
	recorder *MockGameStatusProviderMockRecorder
}

// MockGameStatusProviderMockRecorder is the mock recorder for MockGameStatusProvider.
type MockGameStatusProviderMockRecorder struct {
	mock *MockGameStatusProvider
}

// NewMockGameStatusProvider creates a new mock instance.
func NewMockGameStatusProvider(ctrl *gomock.Controller) *MockGameStatusProvider {
	mock := &MockGameStatusProvider{ctrl: ctrl}
	mock.recorder = &MockGameStatusProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGameStatusProvider) EXPECT() *MockGameStatusProviderMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockGameStatusProvider) Get(p, e ports.Player, game *Game, newCards ...ports.Card) GameStatus {
	m.ctrl.T.Helper()
	varargs := []any{p, e, game}
	for _, a := range newCards {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Get", varargs...)
	ret0, _ := ret[0].(GameStatus)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockGameStatusProviderMockRecorder) Get(p, e, game any, newCards ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{p, e, game}, newCards...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockGameStatusProvider)(nil).Get), varargs...)
}

// GetWithModal mocks base method.
func (m *MockGameStatusProvider) GetWithModal(p, e ports.Player, game *Game, modalCards []ports.Card) GameStatus {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWithModal", p, e, game, modalCards)
	ret0, _ := ret[0].(GameStatus)
	return ret0
}

// GetWithModal indicates an expected call of GetWithModal.
func (mr *MockGameStatusProviderMockRecorder) GetWithModal(p, e, game, modalCards any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWithModal", reflect.TypeOf((*MockGameStatusProvider)(nil).GetWithModal), p, e, game, modalCards)
}
