// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/domain/cards/ambush.go
//
// Generated by this command:
//
//	mockgen -package mocks -source ./internal/domain/cards/ambush.go -destination ./test/mocks/ambush_mocks.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	cards "github.com/alelopezbcn/thecampaign/internal/domain/cards"
	types "github.com/alelopezbcn/thecampaign/internal/domain/types"
	gomock "go.uber.org/mock/gomock"
)

// MockAmbush is a mock of Ambush interface.
type MockAmbush struct {
	ctrl     *gomock.Controller
	recorder *MockAmbushMockRecorder
}

// MockAmbushMockRecorder is the mock recorder for MockAmbush.
type MockAmbushMockRecorder struct {
	mock *MockAmbush
}

// NewMockAmbush creates a new mock instance.
func NewMockAmbush(ctrl *gomock.Controller) *MockAmbush {
	mock := &MockAmbush{ctrl: ctrl}
	mock.recorder = &MockAmbushMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAmbush) EXPECT() *MockAmbushMockRecorder {
	return m.recorder
}

// AddCardMovedToPileObserver mocks base method.
func (m *MockAmbush) AddCardMovedToPileObserver(observer cards.CardMovedToPileObserver) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddCardMovedToPileObserver", observer)
}

// AddCardMovedToPileObserver indicates an expected call of AddCardMovedToPileObserver.
func (mr *MockAmbushMockRecorder) AddCardMovedToPileObserver(observer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCardMovedToPileObserver", reflect.TypeOf((*MockAmbush)(nil).AddCardMovedToPileObserver), observer)
}

// GetCardMovedToPileObserver mocks base method.
func (m *MockAmbush) GetCardMovedToPileObserver() cards.CardMovedToPileObserver {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCardMovedToPileObserver")
	ret0, _ := ret[0].(cards.CardMovedToPileObserver)
	return ret0
}

// GetCardMovedToPileObserver indicates an expected call of GetCardMovedToPileObserver.
func (mr *MockAmbushMockRecorder) GetCardMovedToPileObserver() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCardMovedToPileObserver", reflect.TypeOf((*MockAmbush)(nil).GetCardMovedToPileObserver))
}

// GetID mocks base method.
func (m *MockAmbush) GetID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetID")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetID indicates an expected call of GetID.
func (mr *MockAmbushMockRecorder) GetID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetID", reflect.TypeOf((*MockAmbush)(nil).GetID))
}

// Name mocks base method.
func (m *MockAmbush) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockAmbushMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockAmbush)(nil).Name))
}

// Effect mocks base method.
func (m *MockAmbush) Effect() types.AmbushEffect {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Effect")
	ret0, _ := ret[0].(types.AmbushEffect)
	return ret0
}

// Effect indicates an expected call of Effect.
func (mr *MockAmbushMockRecorder) Effect() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Effect", reflect.TypeOf((*MockAmbush)(nil).Effect))
}
