// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/domain/cards/attackablebase.go
//
// Generated by this command:
//
//	mockgen -package mocks -source ./internal/domain/cards/attackablebase.go -destination ./test/mocks/attackable_mocks.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	cards "github.com/alelopezbcn/thecampaign/internal/domain/cards"
	gomock "go.uber.org/mock/gomock"
)

// MockAttackable is a mock of Attackable interface.
type MockAttackable struct {
	ctrl     *gomock.Controller
	recorder *MockAttackableMockRecorder
}

// MockAttackableMockRecorder is the mock recorder for MockAttackable.
type MockAttackableMockRecorder struct {
	mock *MockAttackable
}

// NewMockAttackable creates a new mock instance.
func NewMockAttackable(ctrl *gomock.Controller) *MockAttackable {
	mock := &MockAttackable{ctrl: ctrl}
	mock.recorder = &MockAttackableMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAttackable) EXPECT() *MockAttackableMockRecorder {
	return m.recorder
}

// AttackedBy mocks base method.
func (m *MockAttackable) AttackedBy() []cards.Weapon {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AttackedBy")
	ret0, _ := ret[0].([]cards.Weapon)
	return ret0
}

// AttackedBy indicates an expected call of AttackedBy.
func (mr *MockAttackableMockRecorder) AttackedBy() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AttackedBy", reflect.TypeOf((*MockAttackable)(nil).AttackedBy))
}

// BeAttacked mocks base method.
func (m *MockAttackable) BeAttacked(weapon cards.Weapon) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeAttacked", weapon)
	ret0, _ := ret[0].(error)
	return ret0
}

// BeAttacked indicates an expected call of BeAttacked.
func (mr *MockAttackableMockRecorder) BeAttacked(weapon any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeAttacked", reflect.TypeOf((*MockAttackable)(nil).BeAttacked), weapon)
}

// Health mocks base method.
func (m *MockAttackable) Health() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Health")
	ret0, _ := ret[0].(int)
	return ret0
}

// Health indicates an expected call of Health.
func (mr *MockAttackableMockRecorder) Health() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Health", reflect.TypeOf((*MockAttackable)(nil).Health))
}

// ReceiveDamage mocks base method.
func (m *MockAttackable) ReceiveDamage(weapon cards.Weapon, multiplier int) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReceiveDamage", weapon, multiplier)
	ret0, _ := ret[0].(bool)
	return ret0
}

// ReceiveDamage indicates an expected call of ReceiveDamage.
func (mr *MockAttackableMockRecorder) ReceiveDamage(weapon, multiplier any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReceiveDamage", reflect.TypeOf((*MockAttackable)(nil).ReceiveDamage), weapon, multiplier)
}

// String mocks base method.
func (m *MockAttackable) String() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "String")
	ret0, _ := ret[0].(string)
	return ret0
}

// String indicates an expected call of String.
func (mr *MockAttackableMockRecorder) String() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "String", reflect.TypeOf((*MockAttackable)(nil).String))
}
