// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/domain/cards/bloodrain.go
//
// Generated by this command:
//
//	mockgen -package mocks -source ./internal/domain/cards/bloodrain.go -destination ./test/mocks/bloodrain_mocks.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	cards "github.com/alelopezbcn/thecampaign/internal/domain/cards"
	types "github.com/alelopezbcn/thecampaign/internal/domain/types"
	gomock "go.uber.org/mock/gomock"
)

// MockBloodRain is a mock of BloodRain interface.
type MockBloodRain struct {
	ctrl     *gomock.Controller
	recorder *MockBloodRainMockRecorder
}

// MockBloodRainMockRecorder is the mock recorder for MockBloodRain.
type MockBloodRainMockRecorder struct {
	mock *MockBloodRain
}

// NewMockBloodRain creates a new mock instance.
func NewMockBloodRain(ctrl *gomock.Controller) *MockBloodRain {
	mock := &MockBloodRain{ctrl: ctrl}
	mock.recorder = &MockBloodRainMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBloodRain) EXPECT() *MockBloodRainMockRecorder {
	return m.recorder
}

// AddCardMovedToPileObserver mocks base method.
func (m *MockBloodRain) AddCardMovedToPileObserver(observer cards.CardMovedToPileObserver) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddCardMovedToPileObserver", observer)
}

// AddCardMovedToPileObserver indicates an expected call of AddCardMovedToPileObserver.
func (mr *MockBloodRainMockRecorder) AddCardMovedToPileObserver(observer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCardMovedToPileObserver", reflect.TypeOf((*MockBloodRain)(nil).AddCardMovedToPileObserver), observer)
}

// Attack mocks base method.
func (m *MockBloodRain) Attack(targets []cards.Warrior) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Attack", targets)
	ret0, _ := ret[0].(error)
	return ret0
}

// Attack indicates an expected call of Attack.
func (mr *MockBloodRainMockRecorder) Attack(targets any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Attack", reflect.TypeOf((*MockBloodRain)(nil).Attack), targets)
}

// CanConstruct mocks base method.
func (m *MockBloodRain) CanConstruct() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CanConstruct")
	ret0, _ := ret[0].(bool)
	return ret0
}

// CanConstruct indicates an expected call of CanConstruct.
func (mr *MockBloodRainMockRecorder) CanConstruct() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CanConstruct", reflect.TypeOf((*MockBloodRain)(nil).CanConstruct))
}

// DamageAmount mocks base method.
func (m *MockBloodRain) DamageAmount() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DamageAmount")
	ret0, _ := ret[0].(int)
	return ret0
}

// DamageAmount indicates an expected call of DamageAmount.
func (mr *MockBloodRainMockRecorder) DamageAmount() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DamageAmount", reflect.TypeOf((*MockBloodRain)(nil).DamageAmount))
}

// GetCardMovedToPileObserver mocks base method.
func (m *MockBloodRain) GetCardMovedToPileObserver() cards.CardMovedToPileObserver {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCardMovedToPileObserver")
	ret0, _ := ret[0].(cards.CardMovedToPileObserver)
	return ret0
}

// GetCardMovedToPileObserver indicates an expected call of GetCardMovedToPileObserver.
func (mr *MockBloodRainMockRecorder) GetCardMovedToPileObserver() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCardMovedToPileObserver", reflect.TypeOf((*MockBloodRain)(nil).GetCardMovedToPileObserver))
}

// GetID mocks base method.
func (m *MockBloodRain) GetID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetID")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetID indicates an expected call of GetID.
func (mr *MockBloodRainMockRecorder) GetID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetID", reflect.TypeOf((*MockBloodRain)(nil).GetID))
}

// MultiplierFactor mocks base method.
func (m *MockBloodRain) MultiplierFactor(target cards.Warrior) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MultiplierFactor", target)
	ret0, _ := ret[0].(int)
	return ret0
}

// MultiplierFactor indicates an expected call of MultiplierFactor.
func (mr *MockBloodRainMockRecorder) MultiplierFactor(target any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MultiplierFactor", reflect.TypeOf((*MockBloodRain)(nil).MultiplierFactor), target)
}

// String mocks base method.
func (m *MockBloodRain) String() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "String")
	ret0, _ := ret[0].(string)
	return ret0
}

// String indicates an expected call of String.
func (mr *MockBloodRainMockRecorder) String() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "String", reflect.TypeOf((*MockBloodRain)(nil).String))
}

// Type mocks base method.
func (m *MockBloodRain) Type() types.WeaponType {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Type")
	ret0, _ := ret[0].(types.WeaponType)
	return ret0
}

// Type indicates an expected call of Type.
func (mr *MockBloodRainMockRecorder) Type() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Type", reflect.TypeOf((*MockBloodRain)(nil).Type))
}
