// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/domain/ports/card.go
//
// Generated by this command:
//
//	mockgen -package mocks -source ./internal/domain/ports/card.go -destination ./test/mocks/card_mocks.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	ports "github.com/alelopezbcn/thecampaign/internal/domain/ports"
	gomock "go.uber.org/mock/gomock"
)

// MockCard is a mock of Card interface.
type MockCard struct {
	ctrl     *gomock.Controller
	recorder *MockCardMockRecorder
}

// MockCardMockRecorder is the mock recorder for MockCard.
type MockCardMockRecorder struct {
	mock *MockCard
}

// NewMockCard creates a new mock instance.
func NewMockCard(ctrl *gomock.Controller) *MockCard {
	mock := &MockCard{ctrl: ctrl}
	mock.recorder = &MockCardMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCard) EXPECT() *MockCardMockRecorder {
	return m.recorder
}

// AddMessageObserver mocks base method.
func (m *MockCard) AddMessageObserver(o ports.MessageObserver) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddMessageObserver", o)
}

// AddMessageObserver indicates an expected call of AddMessageObserver.
func (mr *MockCardMockRecorder) AddMessageObserver(o any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMessageObserver", reflect.TypeOf((*MockCard)(nil).AddMessageObserver), o)
}

// AssignedToPlayer mocks base method.
func (m *MockCard) AssignedToPlayer(player ports.Player) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AssignedToPlayer", player)
}

// AssignedToPlayer indicates an expected call of AssignedToPlayer.
func (mr *MockCardMockRecorder) AssignedToPlayer(player any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignedToPlayer", reflect.TypeOf((*MockCard)(nil).AssignedToPlayer), player)
}

// GetCardToBeDiscardedObserver mocks base method.
func (m *MockCard) GetCardToBeDiscardedObserver() ports.CardToBeDiscardedObserver {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCardToBeDiscardedObserver")
	ret0, _ := ret[0].(ports.CardToBeDiscardedObserver)
	return ret0
}

// GetCardToBeDiscardedObserver indicates an expected call of GetCardToBeDiscardedObserver.
func (mr *MockCardMockRecorder) GetCardToBeDiscardedObserver() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCardToBeDiscardedObserver", reflect.TypeOf((*MockCard)(nil).GetCardToBeDiscardedObserver))
}

// GetID mocks base method.
func (m *MockCard) GetID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetID")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetID indicates an expected call of GetID.
func (mr *MockCardMockRecorder) GetID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetID", reflect.TypeOf((*MockCard)(nil).GetID))
}

// GetMessageObserver mocks base method.
func (m *MockCard) GetMessageObserver() ports.MessageObserver {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessageObserver")
	ret0, _ := ret[0].(ports.MessageObserver)
	return ret0
}

// GetMessageObserver indicates an expected call of GetMessageObserver.
func (mr *MockCardMockRecorder) GetMessageObserver() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessageObserver", reflect.TypeOf((*MockCard)(nil).GetMessageObserver))
}

// String mocks base method.
func (m *MockCard) String() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "String")
	ret0, _ := ret[0].(string)
	return ret0
}

// String indicates an expected call of String.
func (mr *MockCardMockRecorder) String() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "String", reflect.TypeOf((*MockCard)(nil).String))
}

// MockAttackable is a mock of Attackable interface.
type MockAttackable struct {
	ctrl     *gomock.Controller
	recorder *MockAttackableMockRecorder
}

// MockAttackableMockRecorder is the mock recorder for MockAttackable.
type MockAttackableMockRecorder struct {
	mock *MockAttackable
}

// NewMockAttackable creates a new mock instance.
func NewMockAttackable(ctrl *gomock.Controller) *MockAttackable {
	mock := &MockAttackable{ctrl: ctrl}
	mock.recorder = &MockAttackableMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAttackable) EXPECT() *MockAttackableMockRecorder {
	return m.recorder
}

// AttackedBy mocks base method.
func (m *MockAttackable) AttackedBy() []ports.Weapon {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AttackedBy")
	ret0, _ := ret[0].([]ports.Weapon)
	return ret0
}

// AttackedBy indicates an expected call of AttackedBy.
func (mr *MockAttackableMockRecorder) AttackedBy() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AttackedBy", reflect.TypeOf((*MockAttackable)(nil).AttackedBy))
}

// Health mocks base method.
func (m *MockAttackable) Health() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Health")
	ret0, _ := ret[0].(int)
	return ret0
}

// Health indicates an expected call of Health.
func (mr *MockAttackableMockRecorder) Health() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Health", reflect.TypeOf((*MockAttackable)(nil).Health))
}

// ReceiveDamage mocks base method.
func (m *MockAttackable) ReceiveDamage(weapon ports.Weapon, multiplier int) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReceiveDamage", weapon, multiplier)
	ret0, _ := ret[0].(bool)
	return ret0
}

// ReceiveDamage indicates an expected call of ReceiveDamage.
func (mr *MockAttackableMockRecorder) ReceiveDamage(weapon, multiplier any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReceiveDamage", reflect.TypeOf((*MockAttackable)(nil).ReceiveDamage), weapon, multiplier)
}

// MockCatapult is a mock of Catapult interface.
type MockCatapult struct {
	ctrl     *gomock.Controller
	recorder *MockCatapultMockRecorder
}

// MockCatapultMockRecorder is the mock recorder for MockCatapult.
type MockCatapultMockRecorder struct {
	mock *MockCatapult
}

// NewMockCatapult creates a new mock instance.
func NewMockCatapult(ctrl *gomock.Controller) *MockCatapult {
	mock := &MockCatapult{ctrl: ctrl}
	mock.recorder = &MockCatapultMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCatapult) EXPECT() *MockCatapultMockRecorder {
	return m.recorder
}

// AddMessageObserver mocks base method.
func (m *MockCatapult) AddMessageObserver(o ports.MessageObserver) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddMessageObserver", o)
}

// AddMessageObserver indicates an expected call of AddMessageObserver.
func (mr *MockCatapultMockRecorder) AddMessageObserver(o any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMessageObserver", reflect.TypeOf((*MockCatapult)(nil).AddMessageObserver), o)
}

// AssignedToPlayer mocks base method.
func (m *MockCatapult) AssignedToPlayer(player ports.Player) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AssignedToPlayer", player)
}

// AssignedToPlayer indicates an expected call of AssignedToPlayer.
func (mr *MockCatapultMockRecorder) AssignedToPlayer(player any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignedToPlayer", reflect.TypeOf((*MockCatapult)(nil).AssignedToPlayer), player)
}

// Attack mocks base method.
func (m *MockCatapult) Attack(castle ports.Castle, position int) (ports.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Attack", castle, position)
	ret0, _ := ret[0].(ports.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Attack indicates an expected call of Attack.
func (mr *MockCatapultMockRecorder) Attack(castle, position any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Attack", reflect.TypeOf((*MockCatapult)(nil).Attack), castle, position)
}

// GetCardToBeDiscardedObserver mocks base method.
func (m *MockCatapult) GetCardToBeDiscardedObserver() ports.CardToBeDiscardedObserver {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCardToBeDiscardedObserver")
	ret0, _ := ret[0].(ports.CardToBeDiscardedObserver)
	return ret0
}

// GetCardToBeDiscardedObserver indicates an expected call of GetCardToBeDiscardedObserver.
func (mr *MockCatapultMockRecorder) GetCardToBeDiscardedObserver() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCardToBeDiscardedObserver", reflect.TypeOf((*MockCatapult)(nil).GetCardToBeDiscardedObserver))
}

// GetID mocks base method.
func (m *MockCatapult) GetID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetID")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetID indicates an expected call of GetID.
func (mr *MockCatapultMockRecorder) GetID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetID", reflect.TypeOf((*MockCatapult)(nil).GetID))
}

// GetMessageObserver mocks base method.
func (m *MockCatapult) GetMessageObserver() ports.MessageObserver {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessageObserver")
	ret0, _ := ret[0].(ports.MessageObserver)
	return ret0
}

// GetMessageObserver indicates an expected call of GetMessageObserver.
func (mr *MockCatapultMockRecorder) GetMessageObserver() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessageObserver", reflect.TypeOf((*MockCatapult)(nil).GetMessageObserver))
}

// String mocks base method.
func (m *MockCatapult) String() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "String")
	ret0, _ := ret[0].(string)
	return ret0
}

// String indicates an expected call of String.
func (mr *MockCatapultMockRecorder) String() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "String", reflect.TypeOf((*MockCatapult)(nil).String))
}

// MockResource is a mock of Resource interface.
type MockResource struct {
	ctrl     *gomock.Controller
	recorder *MockResourceMockRecorder
}

// MockResourceMockRecorder is the mock recorder for MockResource.
type MockResourceMockRecorder struct {
	mock *MockResource
}

// NewMockResource creates a new mock instance.
func NewMockResource(ctrl *gomock.Controller) *MockResource {
	mock := &MockResource{ctrl: ctrl}
	mock.recorder = &MockResourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResource) EXPECT() *MockResourceMockRecorder {
	return m.recorder
}

// AddMessageObserver mocks base method.
func (m *MockResource) AddMessageObserver(o ports.MessageObserver) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddMessageObserver", o)
}

// AddMessageObserver indicates an expected call of AddMessageObserver.
func (mr *MockResourceMockRecorder) AddMessageObserver(o any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMessageObserver", reflect.TypeOf((*MockResource)(nil).AddMessageObserver), o)
}

// AssignedToPlayer mocks base method.
func (m *MockResource) AssignedToPlayer(player ports.Player) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AssignedToPlayer", player)
}

// AssignedToPlayer indicates an expected call of AssignedToPlayer.
func (mr *MockResourceMockRecorder) AssignedToPlayer(player any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignedToPlayer", reflect.TypeOf((*MockResource)(nil).AssignedToPlayer), player)
}

// GetCardToBeDiscardedObserver mocks base method.
func (m *MockResource) GetCardToBeDiscardedObserver() ports.CardToBeDiscardedObserver {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCardToBeDiscardedObserver")
	ret0, _ := ret[0].(ports.CardToBeDiscardedObserver)
	return ret0
}

// GetCardToBeDiscardedObserver indicates an expected call of GetCardToBeDiscardedObserver.
func (mr *MockResourceMockRecorder) GetCardToBeDiscardedObserver() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCardToBeDiscardedObserver", reflect.TypeOf((*MockResource)(nil).GetCardToBeDiscardedObserver))
}

// GetID mocks base method.
func (m *MockResource) GetID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetID")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetID indicates an expected call of GetID.
func (mr *MockResourceMockRecorder) GetID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetID", reflect.TypeOf((*MockResource)(nil).GetID))
}

// GetMessageObserver mocks base method.
func (m *MockResource) GetMessageObserver() ports.MessageObserver {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessageObserver")
	ret0, _ := ret[0].(ports.MessageObserver)
	return ret0
}

// GetMessageObserver indicates an expected call of GetMessageObserver.
func (mr *MockResourceMockRecorder) GetMessageObserver() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessageObserver", reflect.TypeOf((*MockResource)(nil).GetMessageObserver))
}

// String mocks base method.
func (m *MockResource) String() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "String")
	ret0, _ := ret[0].(string)
	return ret0
}

// String indicates an expected call of String.
func (mr *MockResourceMockRecorder) String() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "String", reflect.TypeOf((*MockResource)(nil).String))
}

// Value mocks base method.
func (m *MockResource) Value() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Value")
	ret0, _ := ret[0].(int)
	return ret0
}

// Value indicates an expected call of Value.
func (mr *MockResourceMockRecorder) Value() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Value", reflect.TypeOf((*MockResource)(nil).Value))
}

// MockSpecialPower is a mock of SpecialPower interface.
type MockSpecialPower struct {
	ctrl     *gomock.Controller
	recorder *MockSpecialPowerMockRecorder
}

// MockSpecialPowerMockRecorder is the mock recorder for MockSpecialPower.
type MockSpecialPowerMockRecorder struct {
	mock *MockSpecialPower
}

// NewMockSpecialPower creates a new mock instance.
func NewMockSpecialPower(ctrl *gomock.Controller) *MockSpecialPower {
	mock := &MockSpecialPower{ctrl: ctrl}
	mock.recorder = &MockSpecialPowerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSpecialPower) EXPECT() *MockSpecialPowerMockRecorder {
	return m.recorder
}

// AddMessageObserver mocks base method.
func (m *MockSpecialPower) AddMessageObserver(o ports.MessageObserver) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddMessageObserver", o)
}

// AddMessageObserver indicates an expected call of AddMessageObserver.
func (mr *MockSpecialPowerMockRecorder) AddMessageObserver(o any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMessageObserver", reflect.TypeOf((*MockSpecialPower)(nil).AddMessageObserver), o)
}

// AssignedToPlayer mocks base method.
func (m *MockSpecialPower) AssignedToPlayer(player ports.Player) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AssignedToPlayer", player)
}

// AssignedToPlayer indicates an expected call of AssignedToPlayer.
func (mr *MockSpecialPowerMockRecorder) AssignedToPlayer(player any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignedToPlayer", reflect.TypeOf((*MockSpecialPower)(nil).AssignedToPlayer), player)
}

// AttackedBy mocks base method.
func (m *MockSpecialPower) AttackedBy() []ports.Weapon {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AttackedBy")
	ret0, _ := ret[0].([]ports.Weapon)
	return ret0
}

// AttackedBy indicates an expected call of AttackedBy.
func (mr *MockSpecialPowerMockRecorder) AttackedBy() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AttackedBy", reflect.TypeOf((*MockSpecialPower)(nil).AttackedBy))
}

// DamageAmount mocks base method.
func (m *MockSpecialPower) DamageAmount() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DamageAmount")
	ret0, _ := ret[0].(int)
	return ret0
}

// DamageAmount indicates an expected call of DamageAmount.
func (mr *MockSpecialPowerMockRecorder) DamageAmount() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DamageAmount", reflect.TypeOf((*MockSpecialPower)(nil).DamageAmount))
}

// Destroyed mocks base method.
func (m *MockSpecialPower) Destroyed() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Destroyed")
}

// Destroyed indicates an expected call of Destroyed.
func (mr *MockSpecialPowerMockRecorder) Destroyed() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Destroyed", reflect.TypeOf((*MockSpecialPower)(nil).Destroyed))
}

// GetCardToBeDiscardedObserver mocks base method.
func (m *MockSpecialPower) GetCardToBeDiscardedObserver() ports.CardToBeDiscardedObserver {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCardToBeDiscardedObserver")
	ret0, _ := ret[0].(ports.CardToBeDiscardedObserver)
	return ret0
}

// GetCardToBeDiscardedObserver indicates an expected call of GetCardToBeDiscardedObserver.
func (mr *MockSpecialPowerMockRecorder) GetCardToBeDiscardedObserver() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCardToBeDiscardedObserver", reflect.TypeOf((*MockSpecialPower)(nil).GetCardToBeDiscardedObserver))
}

// GetID mocks base method.
func (m *MockSpecialPower) GetID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetID")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetID indicates an expected call of GetID.
func (mr *MockSpecialPowerMockRecorder) GetID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetID", reflect.TypeOf((*MockSpecialPower)(nil).GetID))
}

// GetMessageObserver mocks base method.
func (m *MockSpecialPower) GetMessageObserver() ports.MessageObserver {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessageObserver")
	ret0, _ := ret[0].(ports.MessageObserver)
	return ret0
}

// GetMessageObserver indicates an expected call of GetMessageObserver.
func (mr *MockSpecialPowerMockRecorder) GetMessageObserver() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessageObserver", reflect.TypeOf((*MockSpecialPower)(nil).GetMessageObserver))
}

// Health mocks base method.
func (m *MockSpecialPower) Health() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Health")
	ret0, _ := ret[0].(int)
	return ret0
}

// Health indicates an expected call of Health.
func (mr *MockSpecialPowerMockRecorder) Health() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Health", reflect.TypeOf((*MockSpecialPower)(nil).Health))
}

// ReceiveDamage mocks base method.
func (m *MockSpecialPower) ReceiveDamage(weapon ports.Weapon, multiplier int) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReceiveDamage", weapon, multiplier)
	ret0, _ := ret[0].(bool)
	return ret0
}

// ReceiveDamage indicates an expected call of ReceiveDamage.
func (mr *MockSpecialPowerMockRecorder) ReceiveDamage(weapon, multiplier any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReceiveDamage", reflect.TypeOf((*MockSpecialPower)(nil).ReceiveDamage), weapon, multiplier)
}

// String mocks base method.
func (m *MockSpecialPower) String() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "String")
	ret0, _ := ret[0].(string)
	return ret0
}

// String indicates an expected call of String.
func (mr *MockSpecialPowerMockRecorder) String() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "String", reflect.TypeOf((*MockSpecialPower)(nil).String))
}

// Type mocks base method.
func (m *MockSpecialPower) Type() ports.WeaponType {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Type")
	ret0, _ := ret[0].(ports.WeaponType)
	return ret0
}

// Type indicates an expected call of Type.
func (mr *MockSpecialPowerMockRecorder) Type() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Type", reflect.TypeOf((*MockSpecialPower)(nil).Type))
}

// Use mocks base method.
func (m *MockSpecialPower) Use(usedBy, target ports.Warrior) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Use", usedBy, target)
	ret0, _ := ret[0].(error)
	return ret0
}

// Use indicates an expected call of Use.
func (mr *MockSpecialPowerMockRecorder) Use(usedBy, target any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Use", reflect.TypeOf((*MockSpecialPower)(nil).Use), usedBy, target)
}

// MockSpy is a mock of Spy interface.
type MockSpy struct {
	ctrl     *gomock.Controller
	recorder *MockSpyMockRecorder
}

// MockSpyMockRecorder is the mock recorder for MockSpy.
type MockSpyMockRecorder struct {
	mock *MockSpy
}

// NewMockSpy creates a new mock instance.
func NewMockSpy(ctrl *gomock.Controller) *MockSpy {
	mock := &MockSpy{ctrl: ctrl}
	mock.recorder = &MockSpyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSpy) EXPECT() *MockSpyMockRecorder {
	return m.recorder
}

// AddMessageObserver mocks base method.
func (m *MockSpy) AddMessageObserver(o ports.MessageObserver) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddMessageObserver", o)
}

// AddMessageObserver indicates an expected call of AddMessageObserver.
func (mr *MockSpyMockRecorder) AddMessageObserver(o any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMessageObserver", reflect.TypeOf((*MockSpy)(nil).AddMessageObserver), o)
}

// AssignedToPlayer mocks base method.
func (m *MockSpy) AssignedToPlayer(player ports.Player) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AssignedToPlayer", player)
}

// AssignedToPlayer indicates an expected call of AssignedToPlayer.
func (mr *MockSpyMockRecorder) AssignedToPlayer(player any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignedToPlayer", reflect.TypeOf((*MockSpy)(nil).AssignedToPlayer), player)
}

// CanSpy mocks base method.
func (m *MockSpy) CanSpy() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CanSpy")
}

// CanSpy indicates an expected call of CanSpy.
func (mr *MockSpyMockRecorder) CanSpy() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CanSpy", reflect.TypeOf((*MockSpy)(nil).CanSpy))
}

// GetCardToBeDiscardedObserver mocks base method.
func (m *MockSpy) GetCardToBeDiscardedObserver() ports.CardToBeDiscardedObserver {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCardToBeDiscardedObserver")
	ret0, _ := ret[0].(ports.CardToBeDiscardedObserver)
	return ret0
}

// GetCardToBeDiscardedObserver indicates an expected call of GetCardToBeDiscardedObserver.
func (mr *MockSpyMockRecorder) GetCardToBeDiscardedObserver() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCardToBeDiscardedObserver", reflect.TypeOf((*MockSpy)(nil).GetCardToBeDiscardedObserver))
}

// GetID mocks base method.
func (m *MockSpy) GetID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetID")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetID indicates an expected call of GetID.
func (mr *MockSpyMockRecorder) GetID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetID", reflect.TypeOf((*MockSpy)(nil).GetID))
}

// GetMessageObserver mocks base method.
func (m *MockSpy) GetMessageObserver() ports.MessageObserver {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessageObserver")
	ret0, _ := ret[0].(ports.MessageObserver)
	return ret0
}

// GetMessageObserver indicates an expected call of GetMessageObserver.
func (mr *MockSpyMockRecorder) GetMessageObserver() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessageObserver", reflect.TypeOf((*MockSpy)(nil).GetMessageObserver))
}

// String mocks base method.
func (m *MockSpy) String() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "String")
	ret0, _ := ret[0].(string)
	return ret0
}

// String indicates an expected call of String.
func (mr *MockSpyMockRecorder) String() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "String", reflect.TypeOf((*MockSpy)(nil).String))
}

// MockThief is a mock of Thief interface.
type MockThief struct {
	ctrl     *gomock.Controller
	recorder *MockThiefMockRecorder
}

// MockThiefMockRecorder is the mock recorder for MockThief.
type MockThiefMockRecorder struct {
	mock *MockThief
}

// NewMockThief creates a new mock instance.
func NewMockThief(ctrl *gomock.Controller) *MockThief {
	mock := &MockThief{ctrl: ctrl}
	mock.recorder = &MockThiefMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockThief) EXPECT() *MockThiefMockRecorder {
	return m.recorder
}

// AddMessageObserver mocks base method.
func (m *MockThief) AddMessageObserver(o ports.MessageObserver) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddMessageObserver", o)
}

// AddMessageObserver indicates an expected call of AddMessageObserver.
func (mr *MockThiefMockRecorder) AddMessageObserver(o any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMessageObserver", reflect.TypeOf((*MockThief)(nil).AddMessageObserver), o)
}

// AssignedToPlayer mocks base method.
func (m *MockThief) AssignedToPlayer(player ports.Player) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AssignedToPlayer", player)
}

// AssignedToPlayer indicates an expected call of AssignedToPlayer.
func (mr *MockThiefMockRecorder) AssignedToPlayer(player any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignedToPlayer", reflect.TypeOf((*MockThief)(nil).AssignedToPlayer), player)
}

// CanSteal mocks base method.
func (m *MockThief) CanSteal() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CanSteal")
}

// CanSteal indicates an expected call of CanSteal.
func (mr *MockThiefMockRecorder) CanSteal() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CanSteal", reflect.TypeOf((*MockThief)(nil).CanSteal))
}

// GetCardToBeDiscardedObserver mocks base method.
func (m *MockThief) GetCardToBeDiscardedObserver() ports.CardToBeDiscardedObserver {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCardToBeDiscardedObserver")
	ret0, _ := ret[0].(ports.CardToBeDiscardedObserver)
	return ret0
}

// GetCardToBeDiscardedObserver indicates an expected call of GetCardToBeDiscardedObserver.
func (mr *MockThiefMockRecorder) GetCardToBeDiscardedObserver() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCardToBeDiscardedObserver", reflect.TypeOf((*MockThief)(nil).GetCardToBeDiscardedObserver))
}

// GetID mocks base method.
func (m *MockThief) GetID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetID")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetID indicates an expected call of GetID.
func (mr *MockThiefMockRecorder) GetID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetID", reflect.TypeOf((*MockThief)(nil).GetID))
}

// GetMessageObserver mocks base method.
func (m *MockThief) GetMessageObserver() ports.MessageObserver {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessageObserver")
	ret0, _ := ret[0].(ports.MessageObserver)
	return ret0
}

// GetMessageObserver indicates an expected call of GetMessageObserver.
func (mr *MockThiefMockRecorder) GetMessageObserver() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessageObserver", reflect.TypeOf((*MockThief)(nil).GetMessageObserver))
}

// String mocks base method.
func (m *MockThief) String() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "String")
	ret0, _ := ret[0].(string)
	return ret0
}

// String indicates an expected call of String.
func (mr *MockThiefMockRecorder) String() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "String", reflect.TypeOf((*MockThief)(nil).String))
}

// MockWarrior is a mock of Warrior interface.
type MockWarrior struct {
	ctrl     *gomock.Controller
	recorder *MockWarriorMockRecorder
}

// MockWarriorMockRecorder is the mock recorder for MockWarrior.
type MockWarriorMockRecorder struct {
	mock *MockWarrior
}

// NewMockWarrior creates a new mock instance.
func NewMockWarrior(ctrl *gomock.Controller) *MockWarrior {
	mock := &MockWarrior{ctrl: ctrl}
	mock.recorder = &MockWarriorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWarrior) EXPECT() *MockWarriorMockRecorder {
	return m.recorder
}

// AddMessageObserver mocks base method.
func (m *MockWarrior) AddMessageObserver(o ports.MessageObserver) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddMessageObserver", o)
}

// AddMessageObserver indicates an expected call of AddMessageObserver.
func (mr *MockWarriorMockRecorder) AddMessageObserver(o any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMessageObserver", reflect.TypeOf((*MockWarrior)(nil).AddMessageObserver), o)
}

// AddWarriorDeadObserver mocks base method.
func (m *MockWarrior) AddWarriorDeadObserver(o ports.WarriorDeadObserver) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddWarriorDeadObserver", o)
}

// AddWarriorDeadObserver indicates an expected call of AddWarriorDeadObserver.
func (mr *MockWarriorMockRecorder) AddWarriorDeadObserver(o any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddWarriorDeadObserver", reflect.TypeOf((*MockWarrior)(nil).AddWarriorDeadObserver), o)
}

// AssignedToPlayer mocks base method.
func (m *MockWarrior) AssignedToPlayer(player ports.Player) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AssignedToPlayer", player)
}

// AssignedToPlayer indicates an expected call of AssignedToPlayer.
func (mr *MockWarriorMockRecorder) AssignedToPlayer(player any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignedToPlayer", reflect.TypeOf((*MockWarrior)(nil).AssignedToPlayer), player)
}

// Attack mocks base method.
func (m *MockWarrior) Attack(target ports.Attackable, weapon ports.Weapon) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Attack", target, weapon)
	ret0, _ := ret[0].(error)
	return ret0
}

// Attack indicates an expected call of Attack.
func (mr *MockWarriorMockRecorder) Attack(target, weapon any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Attack", reflect.TypeOf((*MockWarrior)(nil).Attack), target, weapon)
}

// AttackedBy mocks base method.
func (m *MockWarrior) AttackedBy() []ports.Weapon {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AttackedBy")
	ret0, _ := ret[0].([]ports.Weapon)
	return ret0
}

// AttackedBy indicates an expected call of AttackedBy.
func (mr *MockWarriorMockRecorder) AttackedBy() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AttackedBy", reflect.TypeOf((*MockWarrior)(nil).AttackedBy))
}

// GetCardToBeDiscardedObserver mocks base method.
func (m *MockWarrior) GetCardToBeDiscardedObserver() ports.CardToBeDiscardedObserver {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCardToBeDiscardedObserver")
	ret0, _ := ret[0].(ports.CardToBeDiscardedObserver)
	return ret0
}

// GetCardToBeDiscardedObserver indicates an expected call of GetCardToBeDiscardedObserver.
func (mr *MockWarriorMockRecorder) GetCardToBeDiscardedObserver() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCardToBeDiscardedObserver", reflect.TypeOf((*MockWarrior)(nil).GetCardToBeDiscardedObserver))
}

// GetID mocks base method.
func (m *MockWarrior) GetID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetID")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetID indicates an expected call of GetID.
func (mr *MockWarriorMockRecorder) GetID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetID", reflect.TypeOf((*MockWarrior)(nil).GetID))
}

// GetMessageObserver mocks base method.
func (m *MockWarrior) GetMessageObserver() ports.MessageObserver {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessageObserver")
	ret0, _ := ret[0].(ports.MessageObserver)
	return ret0
}

// GetMessageObserver indicates an expected call of GetMessageObserver.
func (mr *MockWarriorMockRecorder) GetMessageObserver() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessageObserver", reflect.TypeOf((*MockWarrior)(nil).GetMessageObserver))
}

// Heal mocks base method.
func (m *MockWarrior) Heal(powerCard ports.SpecialPower) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Heal", powerCard)
}

// Heal indicates an expected call of Heal.
func (mr *MockWarriorMockRecorder) Heal(powerCard any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Heal", reflect.TypeOf((*MockWarrior)(nil).Heal), powerCard)
}

// Health mocks base method.
func (m *MockWarrior) Health() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Health")
	ret0, _ := ret[0].(int)
	return ret0
}

// Health indicates an expected call of Health.
func (mr *MockWarriorMockRecorder) Health() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Health", reflect.TypeOf((*MockWarrior)(nil).Health))
}

// InstantKill mocks base method.
func (m *MockWarrior) InstantKill(sp ports.SpecialPower) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "InstantKill", sp)
}

// InstantKill indicates an expected call of InstantKill.
func (mr *MockWarriorMockRecorder) InstantKill(sp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InstantKill", reflect.TypeOf((*MockWarrior)(nil).InstantKill), sp)
}

// IsDamaged mocks base method.
func (m *MockWarrior) IsDamaged() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsDamaged")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsDamaged indicates an expected call of IsDamaged.
func (mr *MockWarriorMockRecorder) IsDamaged() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsDamaged", reflect.TypeOf((*MockWarrior)(nil).IsDamaged))
}

// IsProtected mocks base method.
func (m *MockWarrior) IsProtected() (bool, ports.Card) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsProtected")
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(ports.Card)
	return ret0, ret1
}

// IsProtected indicates an expected call of IsProtected.
func (mr *MockWarriorMockRecorder) IsProtected() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsProtected", reflect.TypeOf((*MockWarrior)(nil).IsProtected))
}

// Protect mocks base method.
func (m *MockWarrior) Protect(powerCard ports.SpecialPower) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Protect", powerCard)
	ret0, _ := ret[0].(error)
	return ret0
}

// Protect indicates an expected call of Protect.
func (mr *MockWarriorMockRecorder) Protect(powerCard any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Protect", reflect.TypeOf((*MockWarrior)(nil).Protect), powerCard)
}

// ReceiveDamage mocks base method.
func (m *MockWarrior) ReceiveDamage(weapon ports.Weapon, multiplier int) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReceiveDamage", weapon, multiplier)
	ret0, _ := ret[0].(bool)
	return ret0
}

// ReceiveDamage indicates an expected call of ReceiveDamage.
func (mr *MockWarriorMockRecorder) ReceiveDamage(weapon, multiplier any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReceiveDamage", reflect.TypeOf((*MockWarrior)(nil).ReceiveDamage), weapon, multiplier)
}

// String mocks base method.
func (m *MockWarrior) String() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "String")
	ret0, _ := ret[0].(string)
	return ret0
}

// String indicates an expected call of String.
func (mr *MockWarriorMockRecorder) String() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "String", reflect.TypeOf((*MockWarrior)(nil).String))
}

// Type mocks base method.
func (m *MockWarrior) Type() ports.WarriorType {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Type")
	ret0, _ := ret[0].(ports.WarriorType)
	return ret0
}

// Type indicates an expected call of Type.
func (mr *MockWarriorMockRecorder) Type() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Type", reflect.TypeOf((*MockWarrior)(nil).Type))
}

// MockWeapon is a mock of Weapon interface.
type MockWeapon struct {
	ctrl     *gomock.Controller
	recorder *MockWeaponMockRecorder
}

// MockWeaponMockRecorder is the mock recorder for MockWeapon.
type MockWeaponMockRecorder struct {
	mock *MockWeapon
}

// NewMockWeapon creates a new mock instance.
func NewMockWeapon(ctrl *gomock.Controller) *MockWeapon {
	mock := &MockWeapon{ctrl: ctrl}
	mock.recorder = &MockWeaponMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWeapon) EXPECT() *MockWeaponMockRecorder {
	return m.recorder
}

// AddMessageObserver mocks base method.
func (m *MockWeapon) AddMessageObserver(o ports.MessageObserver) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddMessageObserver", o)
}

// AddMessageObserver indicates an expected call of AddMessageObserver.
func (mr *MockWeaponMockRecorder) AddMessageObserver(o any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMessageObserver", reflect.TypeOf((*MockWeapon)(nil).AddMessageObserver), o)
}

// AssignedToPlayer mocks base method.
func (m *MockWeapon) AssignedToPlayer(player ports.Player) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AssignedToPlayer", player)
}

// AssignedToPlayer indicates an expected call of AssignedToPlayer.
func (mr *MockWeaponMockRecorder) AssignedToPlayer(player any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignedToPlayer", reflect.TypeOf((*MockWeapon)(nil).AssignedToPlayer), player)
}

// DamageAmount mocks base method.
func (m *MockWeapon) DamageAmount() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DamageAmount")
	ret0, _ := ret[0].(int)
	return ret0
}

// DamageAmount indicates an expected call of DamageAmount.
func (mr *MockWeaponMockRecorder) DamageAmount() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DamageAmount", reflect.TypeOf((*MockWeapon)(nil).DamageAmount))
}

// GetCardToBeDiscardedObserver mocks base method.
func (m *MockWeapon) GetCardToBeDiscardedObserver() ports.CardToBeDiscardedObserver {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCardToBeDiscardedObserver")
	ret0, _ := ret[0].(ports.CardToBeDiscardedObserver)
	return ret0
}

// GetCardToBeDiscardedObserver indicates an expected call of GetCardToBeDiscardedObserver.
func (mr *MockWeaponMockRecorder) GetCardToBeDiscardedObserver() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCardToBeDiscardedObserver", reflect.TypeOf((*MockWeapon)(nil).GetCardToBeDiscardedObserver))
}

// GetID mocks base method.
func (m *MockWeapon) GetID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetID")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetID indicates an expected call of GetID.
func (mr *MockWeaponMockRecorder) GetID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetID", reflect.TypeOf((*MockWeapon)(nil).GetID))
}

// GetMessageObserver mocks base method.
func (m *MockWeapon) GetMessageObserver() ports.MessageObserver {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessageObserver")
	ret0, _ := ret[0].(ports.MessageObserver)
	return ret0
}

// GetMessageObserver indicates an expected call of GetMessageObserver.
func (mr *MockWeaponMockRecorder) GetMessageObserver() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessageObserver", reflect.TypeOf((*MockWeapon)(nil).GetMessageObserver))
}

// String mocks base method.
func (m *MockWeapon) String() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "String")
	ret0, _ := ret[0].(string)
	return ret0
}

// String indicates an expected call of String.
func (mr *MockWeaponMockRecorder) String() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "String", reflect.TypeOf((*MockWeapon)(nil).String))
}

// Type mocks base method.
func (m *MockWeapon) Type() ports.WeaponType {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Type")
	ret0, _ := ret[0].(ports.WeaponType)
	return ret0
}

// Type indicates an expected call of Type.
func (mr *MockWeaponMockRecorder) Type() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Type", reflect.TypeOf((*MockWeapon)(nil).Type))
}

// MockDragon is a mock of Dragon interface.
type MockDragon struct {
	ctrl     *gomock.Controller
	recorder *MockDragonMockRecorder
}

// MockDragonMockRecorder is the mock recorder for MockDragon.
type MockDragonMockRecorder struct {
	mock *MockDragon
}

// NewMockDragon creates a new mock instance.
func NewMockDragon(ctrl *gomock.Controller) *MockDragon {
	mock := &MockDragon{ctrl: ctrl}
	mock.recorder = &MockDragonMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDragon) EXPECT() *MockDragonMockRecorder {
	return m.recorder
}

// AddMessageObserver mocks base method.
func (m *MockDragon) AddMessageObserver(o ports.MessageObserver) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddMessageObserver", o)
}

// AddMessageObserver indicates an expected call of AddMessageObserver.
func (mr *MockDragonMockRecorder) AddMessageObserver(o any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMessageObserver", reflect.TypeOf((*MockDragon)(nil).AddMessageObserver), o)
}

// AddWarriorDeadObserver mocks base method.
func (m *MockDragon) AddWarriorDeadObserver(o ports.WarriorDeadObserver) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddWarriorDeadObserver", o)
}

// AddWarriorDeadObserver indicates an expected call of AddWarriorDeadObserver.
func (mr *MockDragonMockRecorder) AddWarriorDeadObserver(o any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddWarriorDeadObserver", reflect.TypeOf((*MockDragon)(nil).AddWarriorDeadObserver), o)
}

// AssignedToPlayer mocks base method.
func (m *MockDragon) AssignedToPlayer(player ports.Player) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AssignedToPlayer", player)
}

// AssignedToPlayer indicates an expected call of AssignedToPlayer.
func (mr *MockDragonMockRecorder) AssignedToPlayer(player any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignedToPlayer", reflect.TypeOf((*MockDragon)(nil).AssignedToPlayer), player)
}

// Attack mocks base method.
func (m *MockDragon) Attack(target ports.Attackable, weapon ports.Weapon) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Attack", target, weapon)
	ret0, _ := ret[0].(error)
	return ret0
}

// Attack indicates an expected call of Attack.
func (mr *MockDragonMockRecorder) Attack(target, weapon any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Attack", reflect.TypeOf((*MockDragon)(nil).Attack), target, weapon)
}

// AttackedBy mocks base method.
func (m *MockDragon) AttackedBy() []ports.Weapon {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AttackedBy")
	ret0, _ := ret[0].([]ports.Weapon)
	return ret0
}

// AttackedBy indicates an expected call of AttackedBy.
func (mr *MockDragonMockRecorder) AttackedBy() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AttackedBy", reflect.TypeOf((*MockDragon)(nil).AttackedBy))
}

// GetCardToBeDiscardedObserver mocks base method.
func (m *MockDragon) GetCardToBeDiscardedObserver() ports.CardToBeDiscardedObserver {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCardToBeDiscardedObserver")
	ret0, _ := ret[0].(ports.CardToBeDiscardedObserver)
	return ret0
}

// GetCardToBeDiscardedObserver indicates an expected call of GetCardToBeDiscardedObserver.
func (mr *MockDragonMockRecorder) GetCardToBeDiscardedObserver() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCardToBeDiscardedObserver", reflect.TypeOf((*MockDragon)(nil).GetCardToBeDiscardedObserver))
}

// GetID mocks base method.
func (m *MockDragon) GetID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetID")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetID indicates an expected call of GetID.
func (mr *MockDragonMockRecorder) GetID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetID", reflect.TypeOf((*MockDragon)(nil).GetID))
}

// GetMessageObserver mocks base method.
func (m *MockDragon) GetMessageObserver() ports.MessageObserver {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessageObserver")
	ret0, _ := ret[0].(ports.MessageObserver)
	return ret0
}

// GetMessageObserver indicates an expected call of GetMessageObserver.
func (mr *MockDragonMockRecorder) GetMessageObserver() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessageObserver", reflect.TypeOf((*MockDragon)(nil).GetMessageObserver))
}

// Heal mocks base method.
func (m *MockDragon) Heal(powerCard ports.SpecialPower) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Heal", powerCard)
}

// Heal indicates an expected call of Heal.
func (mr *MockDragonMockRecorder) Heal(powerCard any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Heal", reflect.TypeOf((*MockDragon)(nil).Heal), powerCard)
}

// Health mocks base method.
func (m *MockDragon) Health() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Health")
	ret0, _ := ret[0].(int)
	return ret0
}

// Health indicates an expected call of Health.
func (mr *MockDragonMockRecorder) Health() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Health", reflect.TypeOf((*MockDragon)(nil).Health))
}

// InstantKill mocks base method.
func (m *MockDragon) InstantKill(sp ports.SpecialPower) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "InstantKill", sp)
}

// InstantKill indicates an expected call of InstantKill.
func (mr *MockDragonMockRecorder) InstantKill(sp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InstantKill", reflect.TypeOf((*MockDragon)(nil).InstantKill), sp)
}

// IsDamaged mocks base method.
func (m *MockDragon) IsDamaged() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsDamaged")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsDamaged indicates an expected call of IsDamaged.
func (mr *MockDragonMockRecorder) IsDamaged() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsDamaged", reflect.TypeOf((*MockDragon)(nil).IsDamaged))
}

// IsProtected mocks base method.
func (m *MockDragon) IsProtected() (bool, ports.Card) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsProtected")
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(ports.Card)
	return ret0, ret1
}

// IsProtected indicates an expected call of IsProtected.
func (mr *MockDragonMockRecorder) IsProtected() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsProtected", reflect.TypeOf((*MockDragon)(nil).IsProtected))
}

// Protect mocks base method.
func (m *MockDragon) Protect(powerCard ports.SpecialPower) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Protect", powerCard)
	ret0, _ := ret[0].(error)
	return ret0
}

// Protect indicates an expected call of Protect.
func (mr *MockDragonMockRecorder) Protect(powerCard any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Protect", reflect.TypeOf((*MockDragon)(nil).Protect), powerCard)
}

// ReceiveDamage mocks base method.
func (m *MockDragon) ReceiveDamage(weapon ports.Weapon, multiplier int) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReceiveDamage", weapon, multiplier)
	ret0, _ := ret[0].(bool)
	return ret0
}

// ReceiveDamage indicates an expected call of ReceiveDamage.
func (mr *MockDragonMockRecorder) ReceiveDamage(weapon, multiplier any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReceiveDamage", reflect.TypeOf((*MockDragon)(nil).ReceiveDamage), weapon, multiplier)
}

// String mocks base method.
func (m *MockDragon) String() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "String")
	ret0, _ := ret[0].(string)
	return ret0
}

// String indicates an expected call of String.
func (mr *MockDragonMockRecorder) String() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "String", reflect.TypeOf((*MockDragon)(nil).String))
}

// Type mocks base method.
func (m *MockDragon) Type() ports.WarriorType {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Type")
	ret0, _ := ret[0].(ports.WarriorType)
	return ret0
}

// Type indicates an expected call of Type.
func (mr *MockDragonMockRecorder) Type() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Type", reflect.TypeOf((*MockDragon)(nil).Type))
}

// MockKnight is a mock of Knight interface.
type MockKnight struct {
	ctrl     *gomock.Controller
	recorder *MockKnightMockRecorder
}

// MockKnightMockRecorder is the mock recorder for MockKnight.
type MockKnightMockRecorder struct {
	mock *MockKnight
}

// NewMockKnight creates a new mock instance.
func NewMockKnight(ctrl *gomock.Controller) *MockKnight {
	mock := &MockKnight{ctrl: ctrl}
	mock.recorder = &MockKnightMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKnight) EXPECT() *MockKnightMockRecorder {
	return m.recorder
}

// AddMessageObserver mocks base method.
func (m *MockKnight) AddMessageObserver(o ports.MessageObserver) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddMessageObserver", o)
}

// AddMessageObserver indicates an expected call of AddMessageObserver.
func (mr *MockKnightMockRecorder) AddMessageObserver(o any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMessageObserver", reflect.TypeOf((*MockKnight)(nil).AddMessageObserver), o)
}

// AddWarriorDeadObserver mocks base method.
func (m *MockKnight) AddWarriorDeadObserver(o ports.WarriorDeadObserver) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddWarriorDeadObserver", o)
}

// AddWarriorDeadObserver indicates an expected call of AddWarriorDeadObserver.
func (mr *MockKnightMockRecorder) AddWarriorDeadObserver(o any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddWarriorDeadObserver", reflect.TypeOf((*MockKnight)(nil).AddWarriorDeadObserver), o)
}

// AssignedToPlayer mocks base method.
func (m *MockKnight) AssignedToPlayer(player ports.Player) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AssignedToPlayer", player)
}

// AssignedToPlayer indicates an expected call of AssignedToPlayer.
func (mr *MockKnightMockRecorder) AssignedToPlayer(player any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignedToPlayer", reflect.TypeOf((*MockKnight)(nil).AssignedToPlayer), player)
}

// Attack mocks base method.
func (m *MockKnight) Attack(target ports.Attackable, weapon ports.Weapon) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Attack", target, weapon)
	ret0, _ := ret[0].(error)
	return ret0
}

// Attack indicates an expected call of Attack.
func (mr *MockKnightMockRecorder) Attack(target, weapon any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Attack", reflect.TypeOf((*MockKnight)(nil).Attack), target, weapon)
}

// AttackedBy mocks base method.
func (m *MockKnight) AttackedBy() []ports.Weapon {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AttackedBy")
	ret0, _ := ret[0].([]ports.Weapon)
	return ret0
}

// AttackedBy indicates an expected call of AttackedBy.
func (mr *MockKnightMockRecorder) AttackedBy() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AttackedBy", reflect.TypeOf((*MockKnight)(nil).AttackedBy))
}

// GetCardToBeDiscardedObserver mocks base method.
func (m *MockKnight) GetCardToBeDiscardedObserver() ports.CardToBeDiscardedObserver {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCardToBeDiscardedObserver")
	ret0, _ := ret[0].(ports.CardToBeDiscardedObserver)
	return ret0
}

// GetCardToBeDiscardedObserver indicates an expected call of GetCardToBeDiscardedObserver.
func (mr *MockKnightMockRecorder) GetCardToBeDiscardedObserver() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCardToBeDiscardedObserver", reflect.TypeOf((*MockKnight)(nil).GetCardToBeDiscardedObserver))
}

// GetID mocks base method.
func (m *MockKnight) GetID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetID")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetID indicates an expected call of GetID.
func (mr *MockKnightMockRecorder) GetID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetID", reflect.TypeOf((*MockKnight)(nil).GetID))
}

// GetMessageObserver mocks base method.
func (m *MockKnight) GetMessageObserver() ports.MessageObserver {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessageObserver")
	ret0, _ := ret[0].(ports.MessageObserver)
	return ret0
}

// GetMessageObserver indicates an expected call of GetMessageObserver.
func (mr *MockKnightMockRecorder) GetMessageObserver() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessageObserver", reflect.TypeOf((*MockKnight)(nil).GetMessageObserver))
}

// Heal mocks base method.
func (m *MockKnight) Heal(powerCard ports.SpecialPower) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Heal", powerCard)
}

// Heal indicates an expected call of Heal.
func (mr *MockKnightMockRecorder) Heal(powerCard any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Heal", reflect.TypeOf((*MockKnight)(nil).Heal), powerCard)
}

// Health mocks base method.
func (m *MockKnight) Health() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Health")
	ret0, _ := ret[0].(int)
	return ret0
}

// Health indicates an expected call of Health.
func (mr *MockKnightMockRecorder) Health() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Health", reflect.TypeOf((*MockKnight)(nil).Health))
}

// InstantKill mocks base method.
func (m *MockKnight) InstantKill(sp ports.SpecialPower) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "InstantKill", sp)
}

// InstantKill indicates an expected call of InstantKill.
func (mr *MockKnightMockRecorder) InstantKill(sp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InstantKill", reflect.TypeOf((*MockKnight)(nil).InstantKill), sp)
}

// IsDamaged mocks base method.
func (m *MockKnight) IsDamaged() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsDamaged")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsDamaged indicates an expected call of IsDamaged.
func (mr *MockKnightMockRecorder) IsDamaged() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsDamaged", reflect.TypeOf((*MockKnight)(nil).IsDamaged))
}

// IsProtected mocks base method.
func (m *MockKnight) IsProtected() (bool, ports.Card) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsProtected")
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(ports.Card)
	return ret0, ret1
}

// IsProtected indicates an expected call of IsProtected.
func (mr *MockKnightMockRecorder) IsProtected() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsProtected", reflect.TypeOf((*MockKnight)(nil).IsProtected))
}

// Protect mocks base method.
func (m *MockKnight) Protect(powerCard ports.SpecialPower) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Protect", powerCard)
	ret0, _ := ret[0].(error)
	return ret0
}

// Protect indicates an expected call of Protect.
func (mr *MockKnightMockRecorder) Protect(powerCard any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Protect", reflect.TypeOf((*MockKnight)(nil).Protect), powerCard)
}

// ReceiveDamage mocks base method.
func (m *MockKnight) ReceiveDamage(weapon ports.Weapon, multiplier int) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReceiveDamage", weapon, multiplier)
	ret0, _ := ret[0].(bool)
	return ret0
}

// ReceiveDamage indicates an expected call of ReceiveDamage.
func (mr *MockKnightMockRecorder) ReceiveDamage(weapon, multiplier any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReceiveDamage", reflect.TypeOf((*MockKnight)(nil).ReceiveDamage), weapon, multiplier)
}

// String mocks base method.
func (m *MockKnight) String() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "String")
	ret0, _ := ret[0].(string)
	return ret0
}

// String indicates an expected call of String.
func (mr *MockKnightMockRecorder) String() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "String", reflect.TypeOf((*MockKnight)(nil).String))
}

// Type mocks base method.
func (m *MockKnight) Type() ports.WarriorType {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Type")
	ret0, _ := ret[0].(ports.WarriorType)
	return ret0
}

// Type indicates an expected call of Type.
func (mr *MockKnightMockRecorder) Type() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Type", reflect.TypeOf((*MockKnight)(nil).Type))
}

// MockArcher is a mock of Archer interface.
type MockArcher struct {
	ctrl     *gomock.Controller
	recorder *MockArcherMockRecorder
}

// MockArcherMockRecorder is the mock recorder for MockArcher.
type MockArcherMockRecorder struct {
	mock *MockArcher
}

// NewMockArcher creates a new mock instance.
func NewMockArcher(ctrl *gomock.Controller) *MockArcher {
	mock := &MockArcher{ctrl: ctrl}
	mock.recorder = &MockArcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockArcher) EXPECT() *MockArcherMockRecorder {
	return m.recorder
}

// AddMessageObserver mocks base method.
func (m *MockArcher) AddMessageObserver(o ports.MessageObserver) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddMessageObserver", o)
}

// AddMessageObserver indicates an expected call of AddMessageObserver.
func (mr *MockArcherMockRecorder) AddMessageObserver(o any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMessageObserver", reflect.TypeOf((*MockArcher)(nil).AddMessageObserver), o)
}

// AddWarriorDeadObserver mocks base method.
func (m *MockArcher) AddWarriorDeadObserver(o ports.WarriorDeadObserver) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddWarriorDeadObserver", o)
}

// AddWarriorDeadObserver indicates an expected call of AddWarriorDeadObserver.
func (mr *MockArcherMockRecorder) AddWarriorDeadObserver(o any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddWarriorDeadObserver", reflect.TypeOf((*MockArcher)(nil).AddWarriorDeadObserver), o)
}

// AssignedToPlayer mocks base method.
func (m *MockArcher) AssignedToPlayer(player ports.Player) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AssignedToPlayer", player)
}

// AssignedToPlayer indicates an expected call of AssignedToPlayer.
func (mr *MockArcherMockRecorder) AssignedToPlayer(player any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignedToPlayer", reflect.TypeOf((*MockArcher)(nil).AssignedToPlayer), player)
}

// Attack mocks base method.
func (m *MockArcher) Attack(target ports.Attackable, weapon ports.Weapon) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Attack", target, weapon)
	ret0, _ := ret[0].(error)
	return ret0
}

// Attack indicates an expected call of Attack.
func (mr *MockArcherMockRecorder) Attack(target, weapon any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Attack", reflect.TypeOf((*MockArcher)(nil).Attack), target, weapon)
}

// AttackedBy mocks base method.
func (m *MockArcher) AttackedBy() []ports.Weapon {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AttackedBy")
	ret0, _ := ret[0].([]ports.Weapon)
	return ret0
}

// AttackedBy indicates an expected call of AttackedBy.
func (mr *MockArcherMockRecorder) AttackedBy() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AttackedBy", reflect.TypeOf((*MockArcher)(nil).AttackedBy))
}

// GetCardToBeDiscardedObserver mocks base method.
func (m *MockArcher) GetCardToBeDiscardedObserver() ports.CardToBeDiscardedObserver {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCardToBeDiscardedObserver")
	ret0, _ := ret[0].(ports.CardToBeDiscardedObserver)
	return ret0
}

// GetCardToBeDiscardedObserver indicates an expected call of GetCardToBeDiscardedObserver.
func (mr *MockArcherMockRecorder) GetCardToBeDiscardedObserver() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCardToBeDiscardedObserver", reflect.TypeOf((*MockArcher)(nil).GetCardToBeDiscardedObserver))
}

// GetID mocks base method.
func (m *MockArcher) GetID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetID")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetID indicates an expected call of GetID.
func (mr *MockArcherMockRecorder) GetID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetID", reflect.TypeOf((*MockArcher)(nil).GetID))
}

// GetMessageObserver mocks base method.
func (m *MockArcher) GetMessageObserver() ports.MessageObserver {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessageObserver")
	ret0, _ := ret[0].(ports.MessageObserver)
	return ret0
}

// GetMessageObserver indicates an expected call of GetMessageObserver.
func (mr *MockArcherMockRecorder) GetMessageObserver() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessageObserver", reflect.TypeOf((*MockArcher)(nil).GetMessageObserver))
}

// Heal mocks base method.
func (m *MockArcher) Heal(powerCard ports.SpecialPower) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Heal", powerCard)
}

// Heal indicates an expected call of Heal.
func (mr *MockArcherMockRecorder) Heal(powerCard any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Heal", reflect.TypeOf((*MockArcher)(nil).Heal), powerCard)
}

// Health mocks base method.
func (m *MockArcher) Health() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Health")
	ret0, _ := ret[0].(int)
	return ret0
}

// Health indicates an expected call of Health.
func (mr *MockArcherMockRecorder) Health() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Health", reflect.TypeOf((*MockArcher)(nil).Health))
}

// InstantKill mocks base method.
func (m *MockArcher) InstantKill(sp ports.SpecialPower) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "InstantKill", sp)
}

// InstantKill indicates an expected call of InstantKill.
func (mr *MockArcherMockRecorder) InstantKill(sp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InstantKill", reflect.TypeOf((*MockArcher)(nil).InstantKill), sp)
}

// IsDamaged mocks base method.
func (m *MockArcher) IsDamaged() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsDamaged")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsDamaged indicates an expected call of IsDamaged.
func (mr *MockArcherMockRecorder) IsDamaged() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsDamaged", reflect.TypeOf((*MockArcher)(nil).IsDamaged))
}

// IsProtected mocks base method.
func (m *MockArcher) IsProtected() (bool, ports.Card) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsProtected")
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(ports.Card)
	return ret0, ret1
}

// IsProtected indicates an expected call of IsProtected.
func (mr *MockArcherMockRecorder) IsProtected() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsProtected", reflect.TypeOf((*MockArcher)(nil).IsProtected))
}

// Protect mocks base method.
func (m *MockArcher) Protect(powerCard ports.SpecialPower) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Protect", powerCard)
	ret0, _ := ret[0].(error)
	return ret0
}

// Protect indicates an expected call of Protect.
func (mr *MockArcherMockRecorder) Protect(powerCard any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Protect", reflect.TypeOf((*MockArcher)(nil).Protect), powerCard)
}

// ReceiveDamage mocks base method.
func (m *MockArcher) ReceiveDamage(weapon ports.Weapon, multiplier int) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReceiveDamage", weapon, multiplier)
	ret0, _ := ret[0].(bool)
	return ret0
}

// ReceiveDamage indicates an expected call of ReceiveDamage.
func (mr *MockArcherMockRecorder) ReceiveDamage(weapon, multiplier any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReceiveDamage", reflect.TypeOf((*MockArcher)(nil).ReceiveDamage), weapon, multiplier)
}

// String mocks base method.
func (m *MockArcher) String() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "String")
	ret0, _ := ret[0].(string)
	return ret0
}

// String indicates an expected call of String.
func (mr *MockArcherMockRecorder) String() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "String", reflect.TypeOf((*MockArcher)(nil).String))
}

// Type mocks base method.
func (m *MockArcher) Type() ports.WarriorType {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Type")
	ret0, _ := ret[0].(ports.WarriorType)
	return ret0
}

// Type indicates an expected call of Type.
func (mr *MockArcherMockRecorder) Type() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Type", reflect.TypeOf((*MockArcher)(nil).Type))
}

// MockMage is a mock of Mage interface.
type MockMage struct {
	ctrl     *gomock.Controller
	recorder *MockMageMockRecorder
}

// MockMageMockRecorder is the mock recorder for MockMage.
type MockMageMockRecorder struct {
	mock *MockMage
}

// NewMockMage creates a new mock instance.
func NewMockMage(ctrl *gomock.Controller) *MockMage {
	mock := &MockMage{ctrl: ctrl}
	mock.recorder = &MockMageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMage) EXPECT() *MockMageMockRecorder {
	return m.recorder
}

// AddMessageObserver mocks base method.
func (m *MockMage) AddMessageObserver(o ports.MessageObserver) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddMessageObserver", o)
}

// AddMessageObserver indicates an expected call of AddMessageObserver.
func (mr *MockMageMockRecorder) AddMessageObserver(o any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMessageObserver", reflect.TypeOf((*MockMage)(nil).AddMessageObserver), o)
}

// AddWarriorDeadObserver mocks base method.
func (m *MockMage) AddWarriorDeadObserver(o ports.WarriorDeadObserver) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddWarriorDeadObserver", o)
}

// AddWarriorDeadObserver indicates an expected call of AddWarriorDeadObserver.
func (mr *MockMageMockRecorder) AddWarriorDeadObserver(o any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddWarriorDeadObserver", reflect.TypeOf((*MockMage)(nil).AddWarriorDeadObserver), o)
}

// AssignedToPlayer mocks base method.
func (m *MockMage) AssignedToPlayer(player ports.Player) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AssignedToPlayer", player)
}

// AssignedToPlayer indicates an expected call of AssignedToPlayer.
func (mr *MockMageMockRecorder) AssignedToPlayer(player any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignedToPlayer", reflect.TypeOf((*MockMage)(nil).AssignedToPlayer), player)
}

// Attack mocks base method.
func (m *MockMage) Attack(target ports.Attackable, weapon ports.Weapon) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Attack", target, weapon)
	ret0, _ := ret[0].(error)
	return ret0
}

// Attack indicates an expected call of Attack.
func (mr *MockMageMockRecorder) Attack(target, weapon any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Attack", reflect.TypeOf((*MockMage)(nil).Attack), target, weapon)
}

// AttackedBy mocks base method.
func (m *MockMage) AttackedBy() []ports.Weapon {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AttackedBy")
	ret0, _ := ret[0].([]ports.Weapon)
	return ret0
}

// AttackedBy indicates an expected call of AttackedBy.
func (mr *MockMageMockRecorder) AttackedBy() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AttackedBy", reflect.TypeOf((*MockMage)(nil).AttackedBy))
}

// GetCardToBeDiscardedObserver mocks base method.
func (m *MockMage) GetCardToBeDiscardedObserver() ports.CardToBeDiscardedObserver {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCardToBeDiscardedObserver")
	ret0, _ := ret[0].(ports.CardToBeDiscardedObserver)
	return ret0
}

// GetCardToBeDiscardedObserver indicates an expected call of GetCardToBeDiscardedObserver.
func (mr *MockMageMockRecorder) GetCardToBeDiscardedObserver() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCardToBeDiscardedObserver", reflect.TypeOf((*MockMage)(nil).GetCardToBeDiscardedObserver))
}

// GetID mocks base method.
func (m *MockMage) GetID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetID")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetID indicates an expected call of GetID.
func (mr *MockMageMockRecorder) GetID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetID", reflect.TypeOf((*MockMage)(nil).GetID))
}

// GetMessageObserver mocks base method.
func (m *MockMage) GetMessageObserver() ports.MessageObserver {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessageObserver")
	ret0, _ := ret[0].(ports.MessageObserver)
	return ret0
}

// GetMessageObserver indicates an expected call of GetMessageObserver.
func (mr *MockMageMockRecorder) GetMessageObserver() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessageObserver", reflect.TypeOf((*MockMage)(nil).GetMessageObserver))
}

// Heal mocks base method.
func (m *MockMage) Heal(powerCard ports.SpecialPower) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Heal", powerCard)
}

// Heal indicates an expected call of Heal.
func (mr *MockMageMockRecorder) Heal(powerCard any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Heal", reflect.TypeOf((*MockMage)(nil).Heal), powerCard)
}

// Health mocks base method.
func (m *MockMage) Health() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Health")
	ret0, _ := ret[0].(int)
	return ret0
}

// Health indicates an expected call of Health.
func (mr *MockMageMockRecorder) Health() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Health", reflect.TypeOf((*MockMage)(nil).Health))
}

// InstantKill mocks base method.
func (m *MockMage) InstantKill(sp ports.SpecialPower) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "InstantKill", sp)
}

// InstantKill indicates an expected call of InstantKill.
func (mr *MockMageMockRecorder) InstantKill(sp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InstantKill", reflect.TypeOf((*MockMage)(nil).InstantKill), sp)
}

// IsDamaged mocks base method.
func (m *MockMage) IsDamaged() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsDamaged")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsDamaged indicates an expected call of IsDamaged.
func (mr *MockMageMockRecorder) IsDamaged() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsDamaged", reflect.TypeOf((*MockMage)(nil).IsDamaged))
}

// IsProtected mocks base method.
func (m *MockMage) IsProtected() (bool, ports.Card) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsProtected")
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(ports.Card)
	return ret0, ret1
}

// IsProtected indicates an expected call of IsProtected.
func (mr *MockMageMockRecorder) IsProtected() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsProtected", reflect.TypeOf((*MockMage)(nil).IsProtected))
}

// Protect mocks base method.
func (m *MockMage) Protect(powerCard ports.SpecialPower) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Protect", powerCard)
	ret0, _ := ret[0].(error)
	return ret0
}

// Protect indicates an expected call of Protect.
func (mr *MockMageMockRecorder) Protect(powerCard any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Protect", reflect.TypeOf((*MockMage)(nil).Protect), powerCard)
}

// ReceiveDamage mocks base method.
func (m *MockMage) ReceiveDamage(weapon ports.Weapon, multiplier int) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReceiveDamage", weapon, multiplier)
	ret0, _ := ret[0].(bool)
	return ret0
}

// ReceiveDamage indicates an expected call of ReceiveDamage.
func (mr *MockMageMockRecorder) ReceiveDamage(weapon, multiplier any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReceiveDamage", reflect.TypeOf((*MockMage)(nil).ReceiveDamage), weapon, multiplier)
}

// String mocks base method.
func (m *MockMage) String() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "String")
	ret0, _ := ret[0].(string)
	return ret0
}

// String indicates an expected call of String.
func (mr *MockMageMockRecorder) String() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "String", reflect.TypeOf((*MockMage)(nil).String))
}

// Type mocks base method.
func (m *MockMage) Type() ports.WarriorType {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Type")
	ret0, _ := ret[0].(ports.WarriorType)
	return ret0
}

// Type indicates an expected call of Type.
func (mr *MockMageMockRecorder) Type() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Type", reflect.TypeOf((*MockMage)(nil).Type))
}

// MockSword is a mock of Sword interface.
type MockSword struct {
	ctrl     *gomock.Controller
	recorder *MockSwordMockRecorder
}

// MockSwordMockRecorder is the mock recorder for MockSword.
type MockSwordMockRecorder struct {
	mock *MockSword
}

// NewMockSword creates a new mock instance.
func NewMockSword(ctrl *gomock.Controller) *MockSword {
	mock := &MockSword{ctrl: ctrl}
	mock.recorder = &MockSwordMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSword) EXPECT() *MockSwordMockRecorder {
	return m.recorder
}

// AddMessageObserver mocks base method.
func (m *MockSword) AddMessageObserver(o ports.MessageObserver) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddMessageObserver", o)
}

// AddMessageObserver indicates an expected call of AddMessageObserver.
func (mr *MockSwordMockRecorder) AddMessageObserver(o any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMessageObserver", reflect.TypeOf((*MockSword)(nil).AddMessageObserver), o)
}

// AssignedToPlayer mocks base method.
func (m *MockSword) AssignedToPlayer(player ports.Player) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AssignedToPlayer", player)
}

// AssignedToPlayer indicates an expected call of AssignedToPlayer.
func (mr *MockSwordMockRecorder) AssignedToPlayer(player any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignedToPlayer", reflect.TypeOf((*MockSword)(nil).AssignedToPlayer), player)
}

// DamageAmount mocks base method.
func (m *MockSword) DamageAmount() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DamageAmount")
	ret0, _ := ret[0].(int)
	return ret0
}

// DamageAmount indicates an expected call of DamageAmount.
func (mr *MockSwordMockRecorder) DamageAmount() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DamageAmount", reflect.TypeOf((*MockSword)(nil).DamageAmount))
}

// GetCardToBeDiscardedObserver mocks base method.
func (m *MockSword) GetCardToBeDiscardedObserver() ports.CardToBeDiscardedObserver {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCardToBeDiscardedObserver")
	ret0, _ := ret[0].(ports.CardToBeDiscardedObserver)
	return ret0
}

// GetCardToBeDiscardedObserver indicates an expected call of GetCardToBeDiscardedObserver.
func (mr *MockSwordMockRecorder) GetCardToBeDiscardedObserver() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCardToBeDiscardedObserver", reflect.TypeOf((*MockSword)(nil).GetCardToBeDiscardedObserver))
}

// GetID mocks base method.
func (m *MockSword) GetID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetID")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetID indicates an expected call of GetID.
func (mr *MockSwordMockRecorder) GetID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetID", reflect.TypeOf((*MockSword)(nil).GetID))
}

// GetMessageObserver mocks base method.
func (m *MockSword) GetMessageObserver() ports.MessageObserver {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessageObserver")
	ret0, _ := ret[0].(ports.MessageObserver)
	return ret0
}

// GetMessageObserver indicates an expected call of GetMessageObserver.
func (mr *MockSwordMockRecorder) GetMessageObserver() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessageObserver", reflect.TypeOf((*MockSword)(nil).GetMessageObserver))
}

// String mocks base method.
func (m *MockSword) String() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "String")
	ret0, _ := ret[0].(string)
	return ret0
}

// String indicates an expected call of String.
func (mr *MockSwordMockRecorder) String() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "String", reflect.TypeOf((*MockSword)(nil).String))
}

// Type mocks base method.
func (m *MockSword) Type() ports.WeaponType {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Type")
	ret0, _ := ret[0].(ports.WeaponType)
	return ret0
}

// Type indicates an expected call of Type.
func (mr *MockSwordMockRecorder) Type() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Type", reflect.TypeOf((*MockSword)(nil).Type))
}

// MockArrow is a mock of Arrow interface.
type MockArrow struct {
	ctrl     *gomock.Controller
	recorder *MockArrowMockRecorder
}

// MockArrowMockRecorder is the mock recorder for MockArrow.
type MockArrowMockRecorder struct {
	mock *MockArrow
}

// NewMockArrow creates a new mock instance.
func NewMockArrow(ctrl *gomock.Controller) *MockArrow {
	mock := &MockArrow{ctrl: ctrl}
	mock.recorder = &MockArrowMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockArrow) EXPECT() *MockArrowMockRecorder {
	return m.recorder
}

// AddMessageObserver mocks base method.
func (m *MockArrow) AddMessageObserver(o ports.MessageObserver) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddMessageObserver", o)
}

// AddMessageObserver indicates an expected call of AddMessageObserver.
func (mr *MockArrowMockRecorder) AddMessageObserver(o any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMessageObserver", reflect.TypeOf((*MockArrow)(nil).AddMessageObserver), o)
}

// AssignedToPlayer mocks base method.
func (m *MockArrow) AssignedToPlayer(player ports.Player) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AssignedToPlayer", player)
}

// AssignedToPlayer indicates an expected call of AssignedToPlayer.
func (mr *MockArrowMockRecorder) AssignedToPlayer(player any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignedToPlayer", reflect.TypeOf((*MockArrow)(nil).AssignedToPlayer), player)
}

// DamageAmount mocks base method.
func (m *MockArrow) DamageAmount() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DamageAmount")
	ret0, _ := ret[0].(int)
	return ret0
}

// DamageAmount indicates an expected call of DamageAmount.
func (mr *MockArrowMockRecorder) DamageAmount() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DamageAmount", reflect.TypeOf((*MockArrow)(nil).DamageAmount))
}

// GetCardToBeDiscardedObserver mocks base method.
func (m *MockArrow) GetCardToBeDiscardedObserver() ports.CardToBeDiscardedObserver {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCardToBeDiscardedObserver")
	ret0, _ := ret[0].(ports.CardToBeDiscardedObserver)
	return ret0
}

// GetCardToBeDiscardedObserver indicates an expected call of GetCardToBeDiscardedObserver.
func (mr *MockArrowMockRecorder) GetCardToBeDiscardedObserver() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCardToBeDiscardedObserver", reflect.TypeOf((*MockArrow)(nil).GetCardToBeDiscardedObserver))
}

// GetID mocks base method.
func (m *MockArrow) GetID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetID")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetID indicates an expected call of GetID.
func (mr *MockArrowMockRecorder) GetID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetID", reflect.TypeOf((*MockArrow)(nil).GetID))
}

// GetMessageObserver mocks base method.
func (m *MockArrow) GetMessageObserver() ports.MessageObserver {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessageObserver")
	ret0, _ := ret[0].(ports.MessageObserver)
	return ret0
}

// GetMessageObserver indicates an expected call of GetMessageObserver.
func (mr *MockArrowMockRecorder) GetMessageObserver() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessageObserver", reflect.TypeOf((*MockArrow)(nil).GetMessageObserver))
}

// String mocks base method.
func (m *MockArrow) String() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "String")
	ret0, _ := ret[0].(string)
	return ret0
}

// String indicates an expected call of String.
func (mr *MockArrowMockRecorder) String() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "String", reflect.TypeOf((*MockArrow)(nil).String))
}

// Type mocks base method.
func (m *MockArrow) Type() ports.WeaponType {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Type")
	ret0, _ := ret[0].(ports.WeaponType)
	return ret0
}

// Type indicates an expected call of Type.
func (mr *MockArrowMockRecorder) Type() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Type", reflect.TypeOf((*MockArrow)(nil).Type))
}

// MockPoison is a mock of Poison interface.
type MockPoison struct {
	ctrl     *gomock.Controller
	recorder *MockPoisonMockRecorder
}

// MockPoisonMockRecorder is the mock recorder for MockPoison.
type MockPoisonMockRecorder struct {
	mock *MockPoison
}

// NewMockPoison creates a new mock instance.
func NewMockPoison(ctrl *gomock.Controller) *MockPoison {
	mock := &MockPoison{ctrl: ctrl}
	mock.recorder = &MockPoisonMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPoison) EXPECT() *MockPoisonMockRecorder {
	return m.recorder
}

// AddMessageObserver mocks base method.
func (m *MockPoison) AddMessageObserver(o ports.MessageObserver) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddMessageObserver", o)
}

// AddMessageObserver indicates an expected call of AddMessageObserver.
func (mr *MockPoisonMockRecorder) AddMessageObserver(o any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMessageObserver", reflect.TypeOf((*MockPoison)(nil).AddMessageObserver), o)
}

// AssignedToPlayer mocks base method.
func (m *MockPoison) AssignedToPlayer(player ports.Player) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AssignedToPlayer", player)
}

// AssignedToPlayer indicates an expected call of AssignedToPlayer.
func (mr *MockPoisonMockRecorder) AssignedToPlayer(player any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignedToPlayer", reflect.TypeOf((*MockPoison)(nil).AssignedToPlayer), player)
}

// DamageAmount mocks base method.
func (m *MockPoison) DamageAmount() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DamageAmount")
	ret0, _ := ret[0].(int)
	return ret0
}

// DamageAmount indicates an expected call of DamageAmount.
func (mr *MockPoisonMockRecorder) DamageAmount() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DamageAmount", reflect.TypeOf((*MockPoison)(nil).DamageAmount))
}

// GetCardToBeDiscardedObserver mocks base method.
func (m *MockPoison) GetCardToBeDiscardedObserver() ports.CardToBeDiscardedObserver {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCardToBeDiscardedObserver")
	ret0, _ := ret[0].(ports.CardToBeDiscardedObserver)
	return ret0
}

// GetCardToBeDiscardedObserver indicates an expected call of GetCardToBeDiscardedObserver.
func (mr *MockPoisonMockRecorder) GetCardToBeDiscardedObserver() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCardToBeDiscardedObserver", reflect.TypeOf((*MockPoison)(nil).GetCardToBeDiscardedObserver))
}

// GetID mocks base method.
func (m *MockPoison) GetID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetID")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetID indicates an expected call of GetID.
func (mr *MockPoisonMockRecorder) GetID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetID", reflect.TypeOf((*MockPoison)(nil).GetID))
}

// GetMessageObserver mocks base method.
func (m *MockPoison) GetMessageObserver() ports.MessageObserver {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessageObserver")
	ret0, _ := ret[0].(ports.MessageObserver)
	return ret0
}

// GetMessageObserver indicates an expected call of GetMessageObserver.
func (mr *MockPoisonMockRecorder) GetMessageObserver() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessageObserver", reflect.TypeOf((*MockPoison)(nil).GetMessageObserver))
}

// String mocks base method.
func (m *MockPoison) String() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "String")
	ret0, _ := ret[0].(string)
	return ret0
}

// String indicates an expected call of String.
func (mr *MockPoisonMockRecorder) String() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "String", reflect.TypeOf((*MockPoison)(nil).String))
}

// Type mocks base method.
func (m *MockPoison) Type() ports.WeaponType {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Type")
	ret0, _ := ret[0].(ports.WeaponType)
	return ret0
}

// Type indicates an expected call of Type.
func (mr *MockPoisonMockRecorder) Type() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Type", reflect.TypeOf((*MockPoison)(nil).Type))
}
