// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/domain/cards/cardbase.go
//
// Generated by this command:
//
//	mockgen -package mocks -source ./internal/domain/cards/cardbase.go -destination ./test/mocks/card_mocks.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	cards "github.com/alelopezbcn/thecampaign/internal/domain/cards"
	gomock "go.uber.org/mock/gomock"
)

// MockCard is a mock of Card interface.
type MockCard struct {
	ctrl     *gomock.Controller
	recorder *MockCardMockRecorder
}

// MockCardMockRecorder is the mock recorder for MockCard.
type MockCardMockRecorder struct {
	mock *MockCard
}

// NewMockCard creates a new mock instance.
func NewMockCard(ctrl *gomock.Controller) *MockCard {
	mock := &MockCard{ctrl: ctrl}
	mock.recorder = &MockCardMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCard) EXPECT() *MockCardMockRecorder {
	return m.recorder
}

// AddCardMovedToPileObserver mocks base method.
func (m *MockCard) AddCardMovedToPileObserver(observer cards.CardMovedToPileObserver) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddCardMovedToPileObserver", observer)
}

// AddCardMovedToPileObserver indicates an expected call of AddCardMovedToPileObserver.
func (mr *MockCardMockRecorder) AddCardMovedToPileObserver(observer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCardMovedToPileObserver", reflect.TypeOf((*MockCard)(nil).AddCardMovedToPileObserver), observer)
}

// GetCardMovedToPileObserver mocks base method.
func (m *MockCard) GetCardMovedToPileObserver() cards.CardMovedToPileObserver {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCardMovedToPileObserver")
	ret0, _ := ret[0].(cards.CardMovedToPileObserver)
	return ret0
}

// GetCardMovedToPileObserver indicates an expected call of GetCardMovedToPileObserver.
func (mr *MockCardMockRecorder) GetCardMovedToPileObserver() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCardMovedToPileObserver", reflect.TypeOf((*MockCard)(nil).GetCardMovedToPileObserver))
}

// GetID mocks base method.
func (m *MockCard) GetID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetID")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetID indicates an expected call of GetID.
func (mr *MockCardMockRecorder) GetID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetID", reflect.TypeOf((*MockCard)(nil).GetID))
}

// Name mocks base method.
func (m *MockCard) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockCardMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockCard)(nil).Name))
}

// MockCardMovedToPileObserver is a mock of CardMovedToPileObserver interface.
type MockCardMovedToPileObserver struct {
	ctrl     *gomock.Controller
	recorder *MockCardMovedToPileObserverMockRecorder
}

// MockCardMovedToPileObserverMockRecorder is the mock recorder for MockCardMovedToPileObserver.
type MockCardMovedToPileObserverMockRecorder struct {
	mock *MockCardMovedToPileObserver
}

// NewMockCardMovedToPileObserver creates a new mock instance.
func NewMockCardMovedToPileObserver(ctrl *gomock.Controller) *MockCardMovedToPileObserver {
	mock := &MockCardMovedToPileObserver{ctrl: ctrl}
	mock.recorder = &MockCardMovedToPileObserverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCardMovedToPileObserver) EXPECT() *MockCardMovedToPileObserverMockRecorder {
	return m.recorder
}

// OnCardMovedToPile mocks base method.
func (m *MockCardMovedToPileObserver) OnCardMovedToPile(card cards.Card) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnCardMovedToPile", card)
}

// OnCardMovedToPile indicates an expected call of OnCardMovedToPile.
func (mr *MockCardMovedToPileObserverMockRecorder) OnCardMovedToPile(card any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnCardMovedToPile", reflect.TypeOf((*MockCardMovedToPileObserver)(nil).OnCardMovedToPile), card)
}

// MockWarriorDeadObserver is a mock of WarriorDeadObserver interface.
type MockWarriorDeadObserver struct {
	ctrl     *gomock.Controller
	recorder *MockWarriorDeadObserverMockRecorder
}

// MockWarriorDeadObserverMockRecorder is the mock recorder for MockWarriorDeadObserver.
type MockWarriorDeadObserverMockRecorder struct {
	mock *MockWarriorDeadObserver
}

// NewMockWarriorDeadObserver creates a new mock instance.
func NewMockWarriorDeadObserver(ctrl *gomock.Controller) *MockWarriorDeadObserver {
	mock := &MockWarriorDeadObserver{ctrl: ctrl}
	mock.recorder = &MockWarriorDeadObserverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWarriorDeadObserver) EXPECT() *MockWarriorDeadObserverMockRecorder {
	return m.recorder
}

// OnWarriorDead mocks base method.
func (m *MockWarriorDeadObserver) OnWarriorDead(card cards.Warrior) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnWarriorDead", card)
}

// OnWarriorDead indicates an expected call of OnWarriorDead.
func (mr *MockWarriorDeadObserverMockRecorder) OnWarriorDead(card any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnWarriorDead", reflect.TypeOf((*MockWarriorDeadObserver)(nil).OnWarriorDead), card)
}
