// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/domain/ports/castle.go
//
// Generated by this command:
//
//	mockgen -package mocks -source ./internal/domain/ports/castle.go -destination ./test/mocks/castle_mocks.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	ports "github.com/alelopezbcn/thecampaign/internal/domain/ports"
	gomock "go.uber.org/mock/gomock"
)

// MockCastle is a mock of Castle interface.
type MockCastle struct {
	ctrl     *gomock.Controller
	recorder *MockCastleMockRecorder
}

// MockCastleMockRecorder is the mock recorder for MockCastle.
type MockCastleMockRecorder struct {
	mock *MockCastle
}

// NewMockCastle creates a new mock instance.
func NewMockCastle(ctrl *gomock.Controller) *MockCastle {
	mock := &MockCastle{ctrl: ctrl}
	mock.recorder = &MockCastleMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCastle) EXPECT() *MockCastleMockRecorder {
	return m.recorder
}

// CanBeAttacked mocks base method.
func (m *MockCastle) CanBeAttacked() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CanBeAttacked")
	ret0, _ := ret[0].(bool)
	return ret0
}

// CanBeAttacked indicates an expected call of CanBeAttacked.
func (mr *MockCastleMockRecorder) CanBeAttacked() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CanBeAttacked", reflect.TypeOf((*MockCastle)(nil).CanBeAttacked))
}

// Construct mocks base method.
func (m *MockCastle) Construct(card ports.Card) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Construct", card)
	ret0, _ := ret[0].(error)
	return ret0
}

// Construct indicates an expected call of Construct.
func (mr *MockCastleMockRecorder) Construct(card any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Construct", reflect.TypeOf((*MockCastle)(nil).Construct), card)
}

// GetID mocks base method.
func (m *MockCastle) GetID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetID")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetID indicates an expected call of GetID.
func (mr *MockCastleMockRecorder) GetID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetID", reflect.TypeOf((*MockCastle)(nil).GetID))
}

// IsConstructed mocks base method.
func (m *MockCastle) IsConstructed() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsConstructed")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsConstructed indicates an expected call of IsConstructed.
func (mr *MockCastleMockRecorder) IsConstructed() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsConstructed", reflect.TypeOf((*MockCastle)(nil).IsConstructed))
}

// RemoveGold mocks base method.
func (m *MockCastle) RemoveGold(position int) (ports.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveGold", position)
	ret0, _ := ret[0].(ports.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveGold indicates an expected call of RemoveGold.
func (mr *MockCastleMockRecorder) RemoveGold(position any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveGold", reflect.TypeOf((*MockCastle)(nil).RemoveGold), position)
}

// ResourceCards mocks base method.
func (m *MockCastle) ResourceCards() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResourceCards")
	ret0, _ := ret[0].(int)
	return ret0
}

// ResourceCards indicates an expected call of ResourceCards.
func (mr *MockCastleMockRecorder) ResourceCards() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResourceCards", reflect.TypeOf((*MockCastle)(nil).ResourceCards))
}

// String mocks base method.
func (m *MockCastle) String() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "String")
	ret0, _ := ret[0].(string)
	return ret0
}

// String indicates an expected call of String.
func (mr *MockCastleMockRecorder) String() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "String", reflect.TypeOf((*MockCastle)(nil).String))
}

// Value mocks base method.
func (m *MockCastle) Value() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Value")
	ret0, _ := ret[0].(int)
	return ret0
}

// Value indicates an expected call of Value.
func (mr *MockCastleMockRecorder) Value() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Value", reflect.TypeOf((*MockCastle)(nil).Value))
}
