// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/domain/board/castle.go
//
// Generated by this command:
//
//	mockgen -package mocks -source ./internal/domain/board/castle.go -destination ./test/mocks/castle_mocks.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	cards "github.com/alelopezbcn/thecampaign/internal/domain/cards"
	gomock "go.uber.org/mock/gomock"
)

// MockCastleReader is a mock of CastleReader interface.
type MockCastleReader struct {
	ctrl     *gomock.Controller
	recorder *MockCastleReaderMockRecorder
}

// MockCastleReaderMockRecorder is the mock recorder for MockCastleReader.
type MockCastleReaderMockRecorder struct {
	mock *MockCastleReader
}

// NewMockCastleReader creates a new mock instance.
func NewMockCastleReader(ctrl *gomock.Controller) *MockCastleReader {
	mock := &MockCastleReader{ctrl: ctrl}
	mock.recorder = &MockCastleReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCastleReader) EXPECT() *MockCastleReaderMockRecorder {
	return m.recorder
}

// CanBeAttacked mocks base method.
func (m *MockCastleReader) CanBeAttacked() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CanBeAttacked")
	ret0, _ := ret[0].(bool)
	return ret0
}

// CanBeAttacked indicates an expected call of CanBeAttacked.
func (mr *MockCastleReaderMockRecorder) CanBeAttacked() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CanBeAttacked", reflect.TypeOf((*MockCastleReader)(nil).CanBeAttacked))
}

// IsConstructed mocks base method.
func (m *MockCastleReader) IsConstructed() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsConstructed")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsConstructed indicates an expected call of IsConstructed.
func (mr *MockCastleReaderMockRecorder) IsConstructed() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsConstructed", reflect.TypeOf((*MockCastleReader)(nil).IsConstructed))
}

// IsProtected mocks base method.
func (m *MockCastleReader) IsProtected() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsProtected")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsProtected indicates an expected call of IsProtected.
func (mr *MockCastleReaderMockRecorder) IsProtected() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsProtected", reflect.TypeOf((*MockCastleReader)(nil).IsProtected))
}

// ResourceCards mocks base method.
func (m *MockCastleReader) ResourceCards() []cards.Resource {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResourceCards")
	ret0, _ := ret[0].([]cards.Resource)
	return ret0
}

// ResourceCards indicates an expected call of ResourceCards.
func (mr *MockCastleReaderMockRecorder) ResourceCards() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResourceCards", reflect.TypeOf((*MockCastleReader)(nil).ResourceCards))
}

// ResourceCardsCount mocks base method.
func (m *MockCastleReader) ResourceCardsCount() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResourceCardsCount")
	ret0, _ := ret[0].(int)
	return ret0
}

// ResourceCardsCount indicates an expected call of ResourceCardsCount.
func (mr *MockCastleReaderMockRecorder) ResourceCardsCount() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResourceCardsCount", reflect.TypeOf((*MockCastleReader)(nil).ResourceCardsCount))
}

// Value mocks base method.
func (m *MockCastleReader) Value() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Value")
	ret0, _ := ret[0].(int)
	return ret0
}

// Value indicates an expected call of Value.
func (mr *MockCastleReaderMockRecorder) Value() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Value", reflect.TypeOf((*MockCastleReader)(nil).Value))
}

// MockCastleMutator is a mock of CastleMutator interface.
type MockCastleMutator struct {
	ctrl     *gomock.Controller
	recorder *MockCastleMutatorMockRecorder
}

// MockCastleMutatorMockRecorder is the mock recorder for MockCastleMutator.
type MockCastleMutatorMockRecorder struct {
	mock *MockCastleMutator
}

// NewMockCastleMutator creates a new mock instance.
func NewMockCastleMutator(ctrl *gomock.Controller) *MockCastleMutator {
	mock := &MockCastleMutator{ctrl: ctrl}
	mock.recorder = &MockCastleMutatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCastleMutator) EXPECT() *MockCastleMutatorMockRecorder {
	return m.recorder
}

// Construct mocks base method.
func (m *MockCastleMutator) Construct(card cards.Card) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Construct", card)
	ret0, _ := ret[0].(error)
	return ret0
}

// Construct indicates an expected call of Construct.
func (mr *MockCastleMutatorMockRecorder) Construct(card any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Construct", reflect.TypeOf((*MockCastleMutator)(nil).Construct), card)
}

// ConsumeProtection mocks base method.
func (m *MockCastleMutator) ConsumeProtection() cards.Card {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConsumeProtection")
	ret0, _ := ret[0].(cards.Card)
	return ret0
}

// ConsumeProtection indicates an expected call of ConsumeProtection.
func (mr *MockCastleMutatorMockRecorder) ConsumeProtection() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConsumeProtection", reflect.TypeOf((*MockCastleMutator)(nil).ConsumeProtection))
}

// RemoveGold mocks base method.
func (m *MockCastleMutator) RemoveGold(position int) (cards.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveGold", position)
	ret0, _ := ret[0].(cards.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveGold indicates an expected call of RemoveGold.
func (mr *MockCastleMutatorMockRecorder) RemoveGold(position any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveGold", reflect.TypeOf((*MockCastleMutator)(nil).RemoveGold), position)
}

// Reset mocks base method.
func (m *MockCastleMutator) Reset() []cards.Card {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reset")
	ret0, _ := ret[0].([]cards.Card)
	return ret0
}

// Reset indicates an expected call of Reset.
func (mr *MockCastleMutatorMockRecorder) Reset() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reset", reflect.TypeOf((*MockCastleMutator)(nil).Reset))
}

// SetProtection mocks base method.
func (m *MockCastleMutator) SetProtection(f cards.Fortress) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetProtection", f)
}

// SetProtection indicates an expected call of SetProtection.
func (mr *MockCastleMutatorMockRecorder) SetProtection(f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetProtection", reflect.TypeOf((*MockCastleMutator)(nil).SetProtection), f)
}

// MockCastle is a mock of Castle interface.
type MockCastle struct {
	ctrl     *gomock.Controller
	recorder *MockCastleMockRecorder
}

// MockCastleMockRecorder is the mock recorder for MockCastle.
type MockCastleMockRecorder struct {
	mock *MockCastle
}

// NewMockCastle creates a new mock instance.
func NewMockCastle(ctrl *gomock.Controller) *MockCastle {
	mock := &MockCastle{ctrl: ctrl}
	mock.recorder = &MockCastleMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCastle) EXPECT() *MockCastleMockRecorder {
	return m.recorder
}

// CanBeAttacked mocks base method.
func (m *MockCastle) CanBeAttacked() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CanBeAttacked")
	ret0, _ := ret[0].(bool)
	return ret0
}

// CanBeAttacked indicates an expected call of CanBeAttacked.
func (mr *MockCastleMockRecorder) CanBeAttacked() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CanBeAttacked", reflect.TypeOf((*MockCastle)(nil).CanBeAttacked))
}

// Construct mocks base method.
func (m *MockCastle) Construct(card cards.Card) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Construct", card)
	ret0, _ := ret[0].(error)
	return ret0
}

// Construct indicates an expected call of Construct.
func (mr *MockCastleMockRecorder) Construct(card any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Construct", reflect.TypeOf((*MockCastle)(nil).Construct), card)
}

// ConsumeProtection mocks base method.
func (m *MockCastle) ConsumeProtection() cards.Card {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConsumeProtection")
	ret0, _ := ret[0].(cards.Card)
	return ret0
}

// ConsumeProtection indicates an expected call of ConsumeProtection.
func (mr *MockCastleMockRecorder) ConsumeProtection() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConsumeProtection", reflect.TypeOf((*MockCastle)(nil).ConsumeProtection))
}

// IsConstructed mocks base method.
func (m *MockCastle) IsConstructed() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsConstructed")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsConstructed indicates an expected call of IsConstructed.
func (mr *MockCastleMockRecorder) IsConstructed() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsConstructed", reflect.TypeOf((*MockCastle)(nil).IsConstructed))
}

// IsProtected mocks base method.
func (m *MockCastle) IsProtected() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsProtected")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsProtected indicates an expected call of IsProtected.
func (mr *MockCastleMockRecorder) IsProtected() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsProtected", reflect.TypeOf((*MockCastle)(nil).IsProtected))
}

// RemoveGold mocks base method.
func (m *MockCastle) RemoveGold(position int) (cards.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveGold", position)
	ret0, _ := ret[0].(cards.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveGold indicates an expected call of RemoveGold.
func (mr *MockCastleMockRecorder) RemoveGold(position any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveGold", reflect.TypeOf((*MockCastle)(nil).RemoveGold), position)
}

// Reset mocks base method.
func (m *MockCastle) Reset() []cards.Card {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reset")
	ret0, _ := ret[0].([]cards.Card)
	return ret0
}

// Reset indicates an expected call of Reset.
func (mr *MockCastleMockRecorder) Reset() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reset", reflect.TypeOf((*MockCastle)(nil).Reset))
}

// ResourceCards mocks base method.
func (m *MockCastle) ResourceCards() []cards.Resource {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResourceCards")
	ret0, _ := ret[0].([]cards.Resource)
	return ret0
}

// ResourceCards indicates an expected call of ResourceCards.
func (mr *MockCastleMockRecorder) ResourceCards() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResourceCards", reflect.TypeOf((*MockCastle)(nil).ResourceCards))
}

// ResourceCardsCount mocks base method.
func (m *MockCastle) ResourceCardsCount() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResourceCardsCount")
	ret0, _ := ret[0].(int)
	return ret0
}

// ResourceCardsCount indicates an expected call of ResourceCardsCount.
func (mr *MockCastleMockRecorder) ResourceCardsCount() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResourceCardsCount", reflect.TypeOf((*MockCastle)(nil).ResourceCardsCount))
}

// SetProtection mocks base method.
func (m *MockCastle) SetProtection(f cards.Fortress) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetProtection", f)
}

// SetProtection indicates an expected call of SetProtection.
func (mr *MockCastleMockRecorder) SetProtection(f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetProtection", reflect.TypeOf((*MockCastle)(nil).SetProtection), f)
}

// Value mocks base method.
func (m *MockCastle) Value() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Value")
	ret0, _ := ret[0].(int)
	return ret0
}

// Value indicates an expected call of Value.
func (mr *MockCastleMockRecorder) Value() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Value", reflect.TypeOf((*MockCastle)(nil).Value))
}

// MockCastleCompletionObserver is a mock of CastleCompletionObserver interface.
type MockCastleCompletionObserver struct {
	ctrl     *gomock.Controller
	recorder *MockCastleCompletionObserverMockRecorder
}

// MockCastleCompletionObserverMockRecorder is the mock recorder for MockCastleCompletionObserver.
type MockCastleCompletionObserverMockRecorder struct {
	mock *MockCastleCompletionObserver
}

// NewMockCastleCompletionObserver creates a new mock instance.
func NewMockCastleCompletionObserver(ctrl *gomock.Controller) *MockCastleCompletionObserver {
	mock := &MockCastleCompletionObserver{ctrl: ctrl}
	mock.recorder = &MockCastleCompletionObserverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCastleCompletionObserver) EXPECT() *MockCastleCompletionObserverMockRecorder {
	return m.recorder
}

// OnCastleCompletion mocks base method.
func (m *MockCastleCompletionObserver) OnCastleCompletion(playerName string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnCastleCompletion", playerName)
}

// OnCastleCompletion indicates an expected call of OnCastleCompletion.
func (mr *MockCastleCompletionObserverMockRecorder) OnCastleCompletion(playerName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnCastleCompletion", reflect.TypeOf((*MockCastleCompletionObserver)(nil).OnCastleCompletion), playerName)
}
