// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/domain/cards/catapult.go
//
// Generated by this command:
//
//	mockgen -package mocks -source ./internal/domain/cards/catapult.go -destination ./test/mocks/catapult_mocks.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	cards "github.com/alelopezbcn/thecampaign/internal/domain/cards"
	gomock "go.uber.org/mock/gomock"
)

// MockCastleTarget is a mock of CastleTarget interface.
type MockCastleTarget struct {
	ctrl     *gomock.Controller
	recorder *MockCastleTargetMockRecorder
}

// MockCastleTargetMockRecorder is the mock recorder for MockCastleTarget.
type MockCastleTargetMockRecorder struct {
	mock *MockCastleTarget
}

// NewMockCastleTarget creates a new mock instance.
func NewMockCastleTarget(ctrl *gomock.Controller) *MockCastleTarget {
	mock := &MockCastleTarget{ctrl: ctrl}
	mock.recorder = &MockCastleTargetMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCastleTarget) EXPECT() *MockCastleTargetMockRecorder {
	return m.recorder
}

// RemoveGold mocks base method.
func (m *MockCastleTarget) RemoveGold(position int) (cards.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveGold", position)
	ret0, _ := ret[0].(cards.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveGold indicates an expected call of RemoveGold.
func (mr *MockCastleTargetMockRecorder) RemoveGold(position any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveGold", reflect.TypeOf((*MockCastleTarget)(nil).RemoveGold), position)
}

// MockCatapult is a mock of Catapult interface.
type MockCatapult struct {
	ctrl     *gomock.Controller
	recorder *MockCatapultMockRecorder
}

// MockCatapultMockRecorder is the mock recorder for MockCatapult.
type MockCatapultMockRecorder struct {
	mock *MockCatapult
}

// NewMockCatapult creates a new mock instance.
func NewMockCatapult(ctrl *gomock.Controller) *MockCatapult {
	mock := &MockCatapult{ctrl: ctrl}
	mock.recorder = &MockCatapultMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCatapult) EXPECT() *MockCatapultMockRecorder {
	return m.recorder
}

// AddCardMovedToPileObserver mocks base method.
func (m *MockCatapult) AddCardMovedToPileObserver(observer cards.CardMovedToPileObserver) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddCardMovedToPileObserver", observer)
}

// AddCardMovedToPileObserver indicates an expected call of AddCardMovedToPileObserver.
func (mr *MockCatapultMockRecorder) AddCardMovedToPileObserver(observer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCardMovedToPileObserver", reflect.TypeOf((*MockCatapult)(nil).AddCardMovedToPileObserver), observer)
}

// Attack mocks base method.
func (m *MockCatapult) Attack(castle cards.CastleTarget, position int) (cards.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Attack", castle, position)
	ret0, _ := ret[0].(cards.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Attack indicates an expected call of Attack.
func (mr *MockCatapultMockRecorder) Attack(castle, position any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Attack", reflect.TypeOf((*MockCatapult)(nil).Attack), castle, position)
}

// GetCardMovedToPileObserver mocks base method.
func (m *MockCatapult) GetCardMovedToPileObserver() cards.CardMovedToPileObserver {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCardMovedToPileObserver")
	ret0, _ := ret[0].(cards.CardMovedToPileObserver)
	return ret0
}

// GetCardMovedToPileObserver indicates an expected call of GetCardMovedToPileObserver.
func (mr *MockCatapultMockRecorder) GetCardMovedToPileObserver() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCardMovedToPileObserver", reflect.TypeOf((*MockCatapult)(nil).GetCardMovedToPileObserver))
}

// GetID mocks base method.
func (m *MockCatapult) GetID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetID")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetID indicates an expected call of GetID.
func (mr *MockCatapultMockRecorder) GetID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetID", reflect.TypeOf((*MockCatapult)(nil).GetID))
}
