// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/domain/board/cemetery.go
//
// Generated by this command:
//
//	mockgen -package mocks -source ./internal/domain/board/cemetery.go -destination ./test/mocks/cemetery_mocks.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	cards "github.com/alelopezbcn/thecampaign/internal/domain/cards"
	gomock "go.uber.org/mock/gomock"
)

// MockCemetery is a mock of Cemetery interface.
type MockCemetery struct {
	ctrl     *gomock.Controller
	recorder *MockCemeteryMockRecorder
}

// MockCemeteryMockRecorder is the mock recorder for MockCemetery.
type MockCemeteryMockRecorder struct {
	mock *MockCemetery
}

// NewMockCemetery creates a new mock instance.
func NewMockCemetery(ctrl *gomock.Controller) *MockCemetery {
	mock := &MockCemetery{ctrl: ctrl}
	mock.recorder = &MockCemeteryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCemetery) EXPECT() *MockCemeteryMockRecorder {
	return m.recorder
}

// AddCorp mocks base method.
func (m *MockCemetery) AddCorp(arg0 cards.Warrior) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddCorp", arg0)
}

// AddCorp indicates an expected call of AddCorp.
func (mr *MockCemeteryMockRecorder) AddCorp(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCorp", reflect.TypeOf((*MockCemetery)(nil).AddCorp), arg0)
}

// Corps mocks base method.
func (m *MockCemetery) Corps() []cards.Warrior {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Corps")
	ret0, _ := ret[0].([]cards.Warrior)
	return ret0
}

// Corps indicates an expected call of Corps.
func (mr *MockCemeteryMockRecorder) Corps() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Corps", reflect.TypeOf((*MockCemetery)(nil).Corps))
}

// Count mocks base method.
func (m *MockCemetery) Count() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count")
	ret0, _ := ret[0].(int)
	return ret0
}

// Count indicates an expected call of Count.
func (mr *MockCemeteryMockRecorder) Count() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockCemetery)(nil).Count))
}

// GetLast mocks base method.
func (m *MockCemetery) GetLast() cards.Warrior {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLast")
	ret0, _ := ret[0].(cards.Warrior)
	return ret0
}

// GetLast indicates an expected call of GetLast.
func (mr *MockCemeteryMockRecorder) GetLast() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLast", reflect.TypeOf((*MockCemetery)(nil).GetLast))
}

// MockWarriorMovedToCemeteryObserver is a mock of WarriorMovedToCemeteryObserver interface.
type MockWarriorMovedToCemeteryObserver struct {
	ctrl     *gomock.Controller
	recorder *MockWarriorMovedToCemeteryObserverMockRecorder
}

// MockWarriorMovedToCemeteryObserverMockRecorder is the mock recorder for MockWarriorMovedToCemeteryObserver.
type MockWarriorMovedToCemeteryObserverMockRecorder struct {
	mock *MockWarriorMovedToCemeteryObserver
}

// NewMockWarriorMovedToCemeteryObserver creates a new mock instance.
func NewMockWarriorMovedToCemeteryObserver(ctrl *gomock.Controller) *MockWarriorMovedToCemeteryObserver {
	mock := &MockWarriorMovedToCemeteryObserver{ctrl: ctrl}
	mock.recorder = &MockWarriorMovedToCemeteryObserverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWarriorMovedToCemeteryObserver) EXPECT() *MockWarriorMovedToCemeteryObserverMockRecorder {
	return m.recorder
}

// OnWarriorMovedToCemetery mocks base method.
func (m *MockWarriorMovedToCemeteryObserver) OnWarriorMovedToCemetery(card cards.Warrior) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnWarriorMovedToCemetery", card)
}

// OnWarriorMovedToCemetery indicates an expected call of OnWarriorMovedToCemetery.
func (mr *MockWarriorMovedToCemeteryObserverMockRecorder) OnWarriorMovedToCemetery(card any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnWarriorMovedToCemetery", reflect.TypeOf((*MockWarriorMovedToCemeteryObserver)(nil).OnWarriorMovedToCemetery), card)
}
