// Code generated by MockGen. DO NOT EDIT.
// Source: ./backend/internal/domain/ports/dealer.go
//
// Generated by this command:
//
//	mockgen -package mocks -source ./backend/internal/domain/ports/dealer.go -destination ./backend/test/mocks/dealer_mocks.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	ports "github.com/alelopezbcn/thecampaign/internal/domain/ports"
	gomock "go.uber.org/mock/gomock"
)

// MockDealer is a mock of Dealer interface.
type MockDealer struct {
	ctrl     *gomock.Controller
	recorder *MockDealerMockRecorder
}

// MockDealerMockRecorder is the mock recorder for MockDealer.
type MockDealerMockRecorder struct {
	mock *MockDealer
}

// NewMockDealer creates a new mock instance.
func NewMockDealer(ctrl *gomock.Controller) *MockDealer {
	mock := &MockDealer{ctrl: ctrl}
	mock.recorder = &MockDealerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDealer) EXPECT() *MockDealerMockRecorder {
	return m.recorder
}

// OtherCards mocks base method.
func (m *MockDealer) OtherCards(playerCount int) []ports.Card {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OtherCards", playerCount)
	ret0, _ := ret[0].([]ports.Card)
	return ret0
}

// OtherCards indicates an expected call of OtherCards.
func (mr *MockDealerMockRecorder) OtherCards(playerCount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OtherCards", reflect.TypeOf((*MockDealer)(nil).OtherCards), playerCount)
}

// WarriorsCards mocks base method.
func (m *MockDealer) WarriorsCards(playerCount int) []ports.Card {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WarriorsCards", playerCount)
	ret0, _ := ret[0].([]ports.Card)
	return ret0
}

// WarriorsCards indicates an expected call of WarriorsCards.
func (mr *MockDealerMockRecorder) WarriorsCards(playerCount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WarriorsCards", reflect.TypeOf((*MockDealer)(nil).WarriorsCards), playerCount)
}
