// Code generated by MockGen. DO NOT EDIT.
// Source: ./backend/internal/domain/ports/deck.go
//
// Generated by this command:
//
//	mockgen -package mocks -source ./backend/internal/domain/ports/deck.go -destination ./backend/test/mocks/deck_mocks.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	ports "github.com/alelopezbcn/thecampaign/internal/domain/ports"
	gomock "go.uber.org/mock/gomock"
)

// MockDeck is a mock of Deck interface.
type MockDeck struct {
	ctrl     *gomock.Controller
	recorder *MockDeckMockRecorder
}

// MockDeckMockRecorder is the mock recorder for MockDeck.
type MockDeckMockRecorder struct {
	mock *MockDeck
}

// NewMockDeck creates a new mock instance.
func NewMockDeck(ctrl *gomock.Controller) *MockDeck {
	mock := &MockDeck{ctrl: ctrl}
	mock.recorder = &MockDeckMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeck) EXPECT() *MockDeckMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *MockDeck) Count() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count")
	ret0, _ := ret[0].(int)
	return ret0
}

// Count indicates an expected call of Count.
func (mr *MockDeckMockRecorder) Count() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockDeck)(nil).Count))
}

// Deal mocks base method.
func (m *MockDeck) Deal(players []ports.Player) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Deal", players)
}

// Deal indicates an expected call of Deal.
func (mr *MockDeckMockRecorder) Deal(players any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Deal", reflect.TypeOf((*MockDeck)(nil).Deal), players)
}

// DrawCards mocks base method.
func (m *MockDeck) DrawCards(count int, discardPile ports.DiscardPile) ([]ports.Card, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DrawCards", count, discardPile)
	ret0, _ := ret[0].([]ports.Card)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DrawCards indicates an expected call of DrawCards.
func (mr *MockDeckMockRecorder) DrawCards(count, discardPile any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DrawCards", reflect.TypeOf((*MockDeck)(nil).DrawCards), count, discardPile)
}

// Reveal mocks base method.
func (m *MockDeck) Reveal(n int) []ports.Card {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reveal", n)
	ret0, _ := ret[0].([]ports.Card)
	return ret0
}

// Reveal indicates an expected call of Reveal.
func (mr *MockDeckMockRecorder) Reveal(n any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reveal", reflect.TypeOf((*MockDeck)(nil).Reveal), n)
}
