// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/domain/cards/desertion.go
//
// Generated by this command:
//
//	mockgen -package mocks -source ./internal/domain/cards/desertion.go -destination ./test/mocks/desertion_mocks.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	cards "github.com/alelopezbcn/thecampaign/internal/domain/cards"
	gomock "go.uber.org/mock/gomock"
)

// MockDesertion is a mock of Desertion interface.
type MockDesertion struct {
	ctrl     *gomock.Controller
	recorder *MockDesertionMockRecorder
}

// MockDesertionMockRecorder is the mock recorder for MockDesertion.
type MockDesertionMockRecorder struct {
	mock *MockDesertion
}

// NewMockDesertion creates a new mock instance.
func NewMockDesertion(ctrl *gomock.Controller) *MockDesertion {
	mock := &MockDesertion{ctrl: ctrl}
	mock.recorder = &MockDesertionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDesertion) EXPECT() *MockDesertionMockRecorder {
	return m.recorder
}

// AddCardMovedToPileObserver mocks base method.
func (m *MockDesertion) AddCardMovedToPileObserver(observer cards.CardMovedToPileObserver) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddCardMovedToPileObserver", observer)
}

// AddCardMovedToPileObserver indicates an expected call of AddCardMovedToPileObserver.
func (mr *MockDesertionMockRecorder) AddCardMovedToPileObserver(observer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCardMovedToPileObserver", reflect.TypeOf((*MockDesertion)(nil).AddCardMovedToPileObserver), observer)
}

// CanDesertion mocks base method.
func (m *MockDesertion) CanDesertion() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CanDesertion")
}

// CanDesertion indicates an expected call of CanDesertion.
func (mr *MockDesertionMockRecorder) CanDesertion() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CanDesertion", reflect.TypeOf((*MockDesertion)(nil).CanDesertion))
}

// GetCardMovedToPileObserver mocks base method.
func (m *MockDesertion) GetCardMovedToPileObserver() cards.CardMovedToPileObserver {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCardMovedToPileObserver")
	ret0, _ := ret[0].(cards.CardMovedToPileObserver)
	return ret0
}

// GetCardMovedToPileObserver indicates an expected call of GetCardMovedToPileObserver.
func (mr *MockDesertionMockRecorder) GetCardMovedToPileObserver() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCardMovedToPileObserver", reflect.TypeOf((*MockDesertion)(nil).GetCardMovedToPileObserver))
}

// GetID mocks base method.
func (m *MockDesertion) GetID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetID")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetID indicates an expected call of GetID.
func (mr *MockDesertionMockRecorder) GetID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetID", reflect.TypeOf((*MockDesertion)(nil).GetID))
}

// Name mocks base method.
func (m *MockDesertion) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockDesertionMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockDesertion)(nil).Name))
}
