// Code generated by MockGen. DO NOT EDIT.
// Source: ./backend/internal/domain/ports/discardpile.go
//
// Generated by this command:
//
//	mockgen -package mocks -source ./backend/internal/domain/ports/discardpile.go -destination ./backend/test/mocks/discardpile_mocks.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	ports "github.com/alelopezbcn/thecampaign/internal/domain/ports"
	gomock "go.uber.org/mock/gomock"
)

// MockDiscardPile is a mock of DiscardPile interface.
type MockDiscardPile struct {
	ctrl     *gomock.Controller
	recorder *MockDiscardPileMockRecorder
}

// MockDiscardPileMockRecorder is the mock recorder for MockDiscardPile.
type MockDiscardPileMockRecorder struct {
	mock *MockDiscardPile
}

// NewMockDiscardPile creates a new mock instance.
func NewMockDiscardPile(ctrl *gomock.Controller) *MockDiscardPile {
	mock := &MockDiscardPile{ctrl: ctrl}
	mock.recorder = &MockDiscardPileMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDiscardPile) EXPECT() *MockDiscardPileMockRecorder {
	return m.recorder
}

// Cards mocks base method.
func (m *MockDiscardPile) Cards() []ports.Card {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cards")
	ret0, _ := ret[0].([]ports.Card)
	return ret0
}

// Cards indicates an expected call of Cards.
func (mr *MockDiscardPileMockRecorder) Cards() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cards", reflect.TypeOf((*MockDiscardPile)(nil).Cards))
}

// Count mocks base method.
func (m *MockDiscardPile) Count() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count")
	ret0, _ := ret[0].(int)
	return ret0
}

// Count indicates an expected call of Count.
func (mr *MockDiscardPileMockRecorder) Count() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockDiscardPile)(nil).Count))
}

// Discard mocks base method.
func (m *MockDiscardPile) Discard(arg0 ports.Card) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Discard", arg0)
}

// Discard indicates an expected call of Discard.
func (mr *MockDiscardPileMockRecorder) Discard(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Discard", reflect.TypeOf((*MockDiscardPile)(nil).Discard), arg0)
}

// Empty mocks base method.
func (m *MockDiscardPile) Empty() []ports.Card {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Empty")
	ret0, _ := ret[0].([]ports.Card)
	return ret0
}

// Empty indicates an expected call of Empty.
func (mr *MockDiscardPileMockRecorder) Empty() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Empty", reflect.TypeOf((*MockDiscardPile)(nil).Empty))
}

// GetLast mocks base method.
func (m *MockDiscardPile) GetLast() ports.Card {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLast")
	ret0, _ := ret[0].(ports.Card)
	return ret0
}

// GetLast indicates an expected call of GetLast.
func (mr *MockDiscardPileMockRecorder) GetLast() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLast", reflect.TypeOf((*MockDiscardPile)(nil).GetLast))
}
