// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/domain/ports/field.go
//
// Generated by this command:
//
//	mockgen -package mocks -source ./internal/domain/ports/field.go -destination ./test/mocks/field_mocks.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	ports "github.com/alelopezbcn/thecampaign/internal/domain/ports"
	gomock "go.uber.org/mock/gomock"
)

// MockField is a mock of Field interface.
type MockField struct {
	ctrl     *gomock.Controller
	recorder *MockFieldMockRecorder
}

// MockFieldMockRecorder is the mock recorder for MockField.
type MockFieldMockRecorder struct {
	mock *MockField
}

// NewMockField creates a new mock instance.
func NewMockField(ctrl *gomock.Controller) *MockField {
	mock := &MockField{ctrl: ctrl}
	mock.recorder = &MockFieldMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockField) EXPECT() *MockFieldMockRecorder {
	return m.recorder
}

// AddWarriors mocks base method.
func (m *MockField) AddWarriors(cards ...ports.Warrior) {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range cards {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "AddWarriors", varargs...)
}

// AddWarriors indicates an expected call of AddWarriors.
func (mr *MockFieldMockRecorder) AddWarriors(cards ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddWarriors", reflect.TypeOf((*MockField)(nil).AddWarriors), cards...)
}

// GetWarrior mocks base method.
func (m *MockField) GetWarrior(cardID string) (ports.Warrior, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWarrior", cardID)
	ret0, _ := ret[0].(ports.Warrior)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetWarrior indicates an expected call of GetWarrior.
func (mr *MockFieldMockRecorder) GetWarrior(cardID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWarrior", reflect.TypeOf((*MockField)(nil).GetWarrior), cardID)
}

// HasArcher mocks base method.
func (m *MockField) HasArcher() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasArcher")
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasArcher indicates an expected call of HasArcher.
func (mr *MockFieldMockRecorder) HasArcher() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasArcher", reflect.TypeOf((*MockField)(nil).HasArcher))
}

// HasDragon mocks base method.
func (m *MockField) HasDragon() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasDragon")
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasDragon indicates an expected call of HasDragon.
func (mr *MockFieldMockRecorder) HasDragon() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasDragon", reflect.TypeOf((*MockField)(nil).HasDragon))
}

// HasKnight mocks base method.
func (m *MockField) HasKnight() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasKnight")
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasKnight indicates an expected call of HasKnight.
func (mr *MockFieldMockRecorder) HasKnight() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasKnight", reflect.TypeOf((*MockField)(nil).HasKnight))
}

// HasMage mocks base method.
func (m *MockField) HasMage() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasMage")
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasMage indicates an expected call of HasMage.
func (mr *MockFieldMockRecorder) HasMage() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasMage", reflect.TypeOf((*MockField)(nil).HasMage))
}

// RemoveWarrior mocks base method.
func (m *MockField) RemoveWarrior(card ports.Warrior) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveWarrior", card)
	ret0, _ := ret[0].(bool)
	return ret0
}

// RemoveWarrior indicates an expected call of RemoveWarrior.
func (mr *MockFieldMockRecorder) RemoveWarrior(card any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveWarrior", reflect.TypeOf((*MockField)(nil).RemoveWarrior), card)
}

// Warriors mocks base method.
func (m *MockField) Warriors() []ports.Warrior {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Warriors")
	ret0, _ := ret[0].([]ports.Warrior)
	return ret0
}

// Warriors indicates an expected call of Warriors.
func (mr *MockFieldMockRecorder) Warriors() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Warriors", reflect.TypeOf((*MockField)(nil).Warriors))
}
