// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/domain/board/field.go
//
// Generated by this command:
//
//	mockgen -package mocks -source ./internal/domain/board/field.go -destination ./test/mocks/field_mocks.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	cards "github.com/alelopezbcn/thecampaign/internal/domain/cards"
	types "github.com/alelopezbcn/thecampaign/internal/domain/types"
	gomock "go.uber.org/mock/gomock"
)

// MockFieldReader is a mock of FieldReader interface.
type MockFieldReader struct {
	ctrl     *gomock.Controller
	recorder *MockFieldReaderMockRecorder
}

// MockFieldReaderMockRecorder is the mock recorder for MockFieldReader.
type MockFieldReaderMockRecorder struct {
	mock *MockFieldReader
}

// NewMockFieldReader creates a new mock instance.
func NewMockFieldReader(ctrl *gomock.Controller) *MockFieldReader {
	mock := &MockFieldReader{ctrl: ctrl}
	mock.recorder = &MockFieldReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected call of EXPECT.
func (m *MockFieldReader) EXPECT() *MockFieldReaderMockRecorder {
	return m.recorder
}

// GetWarrior mocks base method.
func (m *MockFieldReader) GetWarrior(cardID string) (cards.Warrior, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWarrior", cardID)
	ret0, _ := ret[0].(cards.Warrior)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetWarrior indicates an expected call of GetWarrior.
func (mr *MockFieldReaderMockRecorder) GetWarrior(cardID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWarrior", reflect.TypeOf((*MockFieldReader)(nil).GetWarrior), cardID)
}

// HasWarriorType mocks base method.
func (m *MockFieldReader) HasWarriorType(t types.WarriorType) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasWarriorType", t)
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasWarriorType indicates an expected call of HasWarriorType.
func (mr *MockFieldReaderMockRecorder) HasWarriorType(t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasWarriorType", reflect.TypeOf((*MockFieldReader)(nil).HasWarriorType), t)
}

// SlotCards mocks base method.
func (m *MockFieldReader) SlotCards() []cards.Card {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SlotCards")
	ret0, _ := ret[0].([]cards.Card)
	return ret0
}

// SlotCards indicates an expected call of SlotCards.
func (mr *MockFieldReaderMockRecorder) SlotCards() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SlotCards", reflect.TypeOf((*MockFieldReader)(nil).SlotCards))
}

// Warriors mocks base method.
func (m *MockFieldReader) Warriors() []cards.Warrior {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Warriors")
	ret0, _ := ret[0].([]cards.Warrior)
	return ret0
}

// Warriors indicates an expected call of Warriors.
func (mr *MockFieldReaderMockRecorder) Warriors() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Warriors", reflect.TypeOf((*MockFieldReader)(nil).Warriors))
}

// MockFieldMutator is a mock of FieldMutator interface.
type MockFieldMutator struct {
	ctrl     *gomock.Controller
	recorder *MockFieldMutatorMockRecorder
}

// MockFieldMutatorMockRecorder is the mock recorder for MockFieldMutator.
type MockFieldMutatorMockRecorder struct {
	mock *MockFieldMutator
}

// NewMockFieldMutator creates a new mock instance.
func NewMockFieldMutator(ctrl *gomock.Controller) *MockFieldMutator {
	mock := &MockFieldMutator{ctrl: ctrl}
	mock.recorder = &MockFieldMutatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected call of EXPECT.
func (m *MockFieldMutator) EXPECT() *MockFieldMutatorMockRecorder {
	return m.recorder
}

// AddWarriors mocks base method.
func (m *MockFieldMutator) AddWarriors(cards ...cards.Warrior) {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range cards {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "AddWarriors", varargs...)
}

// AddWarriors indicates an expected call of AddWarriors.
func (mr *MockFieldMutatorMockRecorder) AddWarriors(cards ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddWarriors", reflect.TypeOf((*MockFieldMutator)(nil).AddWarriors), cards...)
}

// RemoveWarrior mocks base method.
func (m *MockFieldMutator) RemoveWarrior(card cards.Warrior) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveWarrior", card)
	ret0, _ := ret[0].(bool)
	return ret0
}

// RemoveWarrior indicates an expected call of RemoveWarrior.
func (mr *MockFieldMutatorMockRecorder) RemoveWarrior(card any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveWarrior", reflect.TypeOf((*MockFieldMutator)(nil).RemoveWarrior), card)
}

// SetSlotCard mocks base method.
func (m *MockFieldMutator) SetSlotCard(c cards.Card) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetSlotCard", c)
}

// SetSlotCard indicates an expected call of SetSlotCard.
func (mr *MockFieldMutatorMockRecorder) SetSlotCard(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSlotCard", reflect.TypeOf((*MockFieldMutator)(nil).SetSlotCard), c)
}

// RemoveSlotCard mocks base method.
func (m *MockFieldMutator) RemoveSlotCard(c cards.Card) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RemoveSlotCard", c)
}

// RemoveSlotCard indicates an expected call of RemoveSlotCard.
func (mr *MockFieldMutatorMockRecorder) RemoveSlotCard(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveSlotCard", reflect.TypeOf((*MockFieldMutator)(nil).RemoveSlotCard), c)
}

// MockField is a mock of Field interface.
type MockField struct {
	ctrl     *gomock.Controller
	recorder *MockFieldMockRecorder
}

// MockFieldMockRecorder is the mock recorder for MockField.
type MockFieldMockRecorder struct {
	mock *MockField
}

// NewMockField creates a new mock instance.
func NewMockField(ctrl *gomock.Controller) *MockField {
	mock := &MockField{ctrl: ctrl}
	mock.recorder = &MockFieldMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected call of EXPECT.
func (m *MockField) EXPECT() *MockFieldMockRecorder {
	return m.recorder
}

// AddWarriors mocks base method.
func (m *MockField) AddWarriors(cards ...cards.Warrior) {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range cards {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "AddWarriors", varargs...)
}

// AddWarriors indicates an expected call of AddWarriors.
func (mr *MockFieldMockRecorder) AddWarriors(cards ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddWarriors", reflect.TypeOf((*MockField)(nil).AddWarriors), cards...)
}

// GetWarrior mocks base method.
func (m *MockField) GetWarrior(cardID string) (cards.Warrior, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWarrior", cardID)
	ret0, _ := ret[0].(cards.Warrior)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetWarrior indicates an expected call of GetWarrior.
func (mr *MockFieldMockRecorder) GetWarrior(cardID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWarrior", reflect.TypeOf((*MockField)(nil).GetWarrior), cardID)
}

// HasWarriorType mocks base method.
func (m *MockField) HasWarriorType(t types.WarriorType) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasWarriorType", t)
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasWarriorType indicates an expected call of HasWarriorType.
func (mr *MockFieldMockRecorder) HasWarriorType(t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasWarriorType", reflect.TypeOf((*MockField)(nil).HasWarriorType), t)
}

// RemoveWarrior mocks base method.
func (m *MockField) RemoveWarrior(card cards.Warrior) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveWarrior", card)
	ret0, _ := ret[0].(bool)
	return ret0
}

// RemoveWarrior indicates an expected call of RemoveWarrior.
func (mr *MockFieldMockRecorder) RemoveWarrior(card any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveWarrior", reflect.TypeOf((*MockField)(nil).RemoveWarrior), card)
}

// SlotCards mocks base method.
func (m *MockField) SlotCards() []cards.Card {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SlotCards")
	ret0, _ := ret[0].([]cards.Card)
	return ret0
}

// SlotCards indicates an expected call of SlotCards.
func (mr *MockFieldMockRecorder) SlotCards() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SlotCards", reflect.TypeOf((*MockField)(nil).SlotCards))
}

// SetSlotCard mocks base method.
func (m *MockField) SetSlotCard(c cards.Card) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetSlotCard", c)
}

// SetSlotCard indicates an expected call of SetSlotCard.
func (mr *MockFieldMockRecorder) SetSlotCard(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSlotCard", reflect.TypeOf((*MockField)(nil).SetSlotCard), c)
}

// RemoveSlotCard mocks base method.
func (m *MockField) RemoveSlotCard(c cards.Card) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RemoveSlotCard", c)
}

// RemoveSlotCard indicates an expected call of RemoveSlotCard.
func (mr *MockFieldMockRecorder) RemoveSlotCard(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveSlotCard", reflect.TypeOf((*MockField)(nil).RemoveSlotCard), c)
}

// Warriors mocks base method.
func (m *MockField) Warriors() []cards.Warrior {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Warriors")
	ret0, _ := ret[0].([]cards.Warrior)
	return ret0
}

// Warriors indicates an expected call of Warriors.
func (mr *MockFieldMockRecorder) Warriors() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Warriors", reflect.TypeOf((*MockField)(nil).Warriors))
}

// MockFieldWithoutWarriorsObserver is a mock of FieldWithoutWarriorsObserver interface.
type MockFieldWithoutWarriorsObserver struct {
	ctrl     *gomock.Controller
	recorder *MockFieldWithoutWarriorsObserverMockRecorder
}

// MockFieldWithoutWarriorsObserverMockRecorder is the mock recorder for MockFieldWithoutWarriorsObserver.
type MockFieldWithoutWarriorsObserverMockRecorder struct {
	mock *MockFieldWithoutWarriorsObserver
}

// NewMockFieldWithoutWarriorsObserver creates a new mock instance.
func NewMockFieldWithoutWarriorsObserver(ctrl *gomock.Controller) *MockFieldWithoutWarriorsObserver {
	mock := &MockFieldWithoutWarriorsObserver{ctrl: ctrl}
	mock.recorder = &MockFieldWithoutWarriorsObserverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected call of EXPECT.
func (m *MockFieldWithoutWarriorsObserver) EXPECT() *MockFieldWithoutWarriorsObserverMockRecorder {
	return m.recorder
}

// OnFieldWithoutWarriors mocks base method.
func (m *MockFieldWithoutWarriorsObserver) OnFieldWithoutWarriors(playerName string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnFieldWithoutWarriors", playerName)
}

// OnFieldWithoutWarriors indicates an expected call of OnFieldWithoutWarriors.
func (mr *MockFieldWithoutWarriorsObserverMockRecorder) OnFieldWithoutWarriors(playerName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnFieldWithoutWarriors", reflect.TypeOf((*MockFieldWithoutWarriorsObserver)(nil).OnFieldWithoutWarriors), playerName)
}
