// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/domain/gameactions/gameaction.go
//
// Generated by this command:
//
//	mockgen -package mocks -source ./internal/domain/gameactions/gameaction.go -destination ./test/mocks/gameaction_mocks.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	board "github.com/alelopezbcn/thecampaign/internal/domain/board"
	cards "github.com/alelopezbcn/thecampaign/internal/domain/cards"
	gameactions "github.com/alelopezbcn/thecampaign/internal/domain/gameactions"
	gamestatus "github.com/alelopezbcn/thecampaign/internal/domain/gamestatus"
	types "github.com/alelopezbcn/thecampaign/internal/domain/types"
	gomock "go.uber.org/mock/gomock"
)

// MockGame is a mock of Game interface.
type MockGame struct {
	ctrl     *gomock.Controller
	recorder *MockGameMockRecorder
}

// MockGameMockRecorder is the mock recorder for MockGame.
type MockGameMockRecorder struct {
	mock *MockGame
}

// NewMockGame creates a new mock instance.
func NewMockGame(ctrl *gomock.Controller) *MockGame {
	mock := &MockGame{ctrl: ctrl}
	mock.recorder = &MockGameMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGame) EXPECT() *MockGameMockRecorder {
	return m.recorder
}

// AddHistory mocks base method.
func (m *MockGame) AddHistory(msg string, cat types.Category) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddHistory", msg, cat)
}

// AddHistory indicates an expected call of AddHistory.
func (mr *MockGameMockRecorder) AddHistory(msg, cat any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddHistory", reflect.TypeOf((*MockGame)(nil).AddHistory), msg, cat)
}

// Allies mocks base method.
func (m *MockGame) Allies(playerIdx int) []board.Player {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Allies", playerIdx)
	ret0, _ := ret[0].([]board.Player)
	return ret0
}

// Allies indicates an expected call of Allies.
func (mr *MockGameMockRecorder) Allies(playerIdx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Allies", reflect.TypeOf((*MockGame)(nil).Allies), playerIdx)
}

// Board mocks base method.
func (m *MockGame) Board() board.Board {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Board")
	ret0, _ := ret[0].(board.Board)
	return ret0
}

// Board indicates an expected call of Board.
func (mr *MockGameMockRecorder) Board() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Board", reflect.TypeOf((*MockGame)(nil).Board))
}

// CurrentAction mocks base method.
func (m *MockGame) CurrentAction() types.PhaseType {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CurrentAction")
	ret0, _ := ret[0].(types.PhaseType)
	return ret0
}

// CurrentAction indicates an expected call of CurrentAction.
func (mr *MockGameMockRecorder) CurrentAction() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CurrentAction", reflect.TypeOf((*MockGame)(nil).CurrentAction))
}

// CurrentPlayer mocks base method.
func (m *MockGame) CurrentPlayer() board.Player {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CurrentPlayer")
	ret0, _ := ret[0].(board.Player)
	return ret0
}

// CurrentPlayer indicates an expected call of CurrentPlayer.
func (mr *MockGameMockRecorder) CurrentPlayer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CurrentPlayer", reflect.TypeOf((*MockGame)(nil).CurrentPlayer))
}

// DrawCards mocks base method.
func (m *MockGame) DrawCards(p board.Player, count int) ([]cards.Card, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DrawCards", p, count)
	ret0, _ := ret[0].([]cards.Card)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DrawCards indicates an expected call of DrawCards.
func (mr *MockGameMockRecorder) DrawCards(p, count any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DrawCards", reflect.TypeOf((*MockGame)(nil).DrawCards), p, count)
}

// Enemies mocks base method.
func (m *MockGame) Enemies(playerIdx int) []board.Player {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enemies", playerIdx)
	ret0, _ := ret[0].([]board.Player)
	return ret0
}

// Enemies indicates an expected call of Enemies.
func (mr *MockGameMockRecorder) Enemies(playerIdx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enemies", reflect.TypeOf((*MockGame)(nil).Enemies), playerIdx)
}

// GetPlayer mocks base method.
func (m *MockGame) GetPlayer(name string) board.Player {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlayer", name)
	ret0, _ := ret[0].(board.Player)
	return ret0
}

// GetPlayer indicates an expected call of GetPlayer.
func (mr *MockGameMockRecorder) GetPlayer(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlayer", reflect.TypeOf((*MockGame)(nil).GetPlayer), name)
}

// GetTargetPlayer mocks base method.
func (m *MockGame) GetTargetPlayer(playerName, targetPlayerName string) (board.Player, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTargetPlayer", playerName, targetPlayerName)
	ret0, _ := ret[0].(board.Player)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTargetPlayer indicates an expected call of GetTargetPlayer.
func (mr *MockGameMockRecorder) GetTargetPlayer(playerName, targetPlayerName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTargetPlayer", reflect.TypeOf((*MockGame)(nil).GetTargetPlayer), playerName, targetPlayerName)
}

// OnCardMovedToPile mocks base method.
func (m *MockGame) OnCardMovedToPile(card cards.Card) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnCardMovedToPile", card)
}

// OnCardMovedToPile indicates an expected call of OnCardMovedToPile.
func (mr *MockGameMockRecorder) OnCardMovedToPile(card any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnCardMovedToPile", reflect.TypeOf((*MockGame)(nil).OnCardMovedToPile), card)
}

// PlayerIndex mocks base method.
func (m *MockGame) PlayerIndex(name string) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PlayerIndex", name)
	ret0, _ := ret[0].(int)
	return ret0
}

// PlayerIndex indicates an expected call of PlayerIndex.
func (mr *MockGameMockRecorder) PlayerIndex(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PlayerIndex", reflect.TypeOf((*MockGame)(nil).PlayerIndex), name)
}

// SameTeam mocks base method.
func (m *MockGame) SameTeam(i, j int) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SameTeam", i, j)
	ret0, _ := ret[0].(bool)
	return ret0
}

// SameTeam indicates an expected call of SameTeam.
func (mr *MockGameMockRecorder) SameTeam(i, j any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SameTeam", reflect.TypeOf((*MockGame)(nil).SameTeam), i, j)
}

// SetCanForge mocks base method.
func (m *MockGame) SetCanForge(value bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetCanForge", value)
}

// SetCanForge indicates an expected call of SetCanForge.
func (mr *MockGameMockRecorder) SetCanForge(value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCanForge", reflect.TypeOf((*MockGame)(nil).SetCanForge), value)
}

// SetCanMoveWarrior mocks base method.
func (m *MockGame) SetCanMoveWarrior(value bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetCanMoveWarrior", value)
}

// SetCanMoveWarrior indicates an expected call of SetCanMoveWarrior.
func (mr *MockGameMockRecorder) SetCanMoveWarrior(value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCanMoveWarrior", reflect.TypeOf((*MockGame)(nil).SetCanMoveWarrior), value)
}

// SetCanTrade mocks base method.
func (m *MockGame) SetCanTrade(value bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetCanTrade", value)
}

// SetCanTrade indicates an expected call of SetCanTrade.
func (mr *MockGameMockRecorder) SetCanTrade(value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCanTrade", reflect.TypeOf((*MockGame)(nil).SetCanTrade), value)
}

// SetHasForged mocks base method.
func (m *MockGame) SetHasForged(value bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetHasForged", value)
}

// SetHasForged indicates an expected call of SetHasForged.
func (mr *MockGameMockRecorder) SetHasForged(value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetHasForged", reflect.TypeOf((*MockGame)(nil).SetHasForged), value)
}

// SetHasMovedWarrior mocks base method.
func (m *MockGame) SetHasMovedWarrior(value bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetHasMovedWarrior", value)
}

// SetHasMovedWarrior indicates an expected call of SetHasMovedWarrior.
func (mr *MockGameMockRecorder) SetHasMovedWarrior(value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetHasMovedWarrior", reflect.TypeOf((*MockGame)(nil).SetHasMovedWarrior), value)
}

// SetHasTraded mocks base method.
func (m *MockGame) SetHasTraded(value bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetHasTraded", value)
}

// SetHasTraded indicates an expected call of SetHasTraded.
func (mr *MockGameMockRecorder) SetHasTraded(value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetHasTraded", reflect.TypeOf((*MockGame)(nil).SetHasTraded), value)
}

// Status mocks base method.
func (m *MockGame) Status(viewer board.Player, newCards ...cards.Card) gamestatus.GameStatus {
	m.ctrl.T.Helper()
	varargs := []any{viewer}
	for _, a := range newCards {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Status", varargs...)
	ret0, _ := ret[0].(gamestatus.GameStatus)
	return ret0
}

// Status indicates an expected call of Status.
func (mr *MockGameMockRecorder) Status(viewer any, newCards ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{viewer}, newCards...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Status", reflect.TypeOf((*MockGame)(nil).Status), varargs...)
}

// StatusWithModal mocks base method.
func (m *MockGame) StatusWithModal(viewer board.Player, modalCards []cards.Card) gamestatus.GameStatus {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StatusWithModal", viewer, modalCards)
	ret0, _ := ret[0].(gamestatus.GameStatus)
	return ret0
}

// StatusWithModal indicates an expected call of StatusWithModal.
func (mr *MockGameMockRecorder) StatusWithModal(viewer, modalCards any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StatusWithModal", reflect.TypeOf((*MockGame)(nil).StatusWithModal), viewer, modalCards)
}

// SwitchTurn mocks base method.
func (m *MockGame) SwitchTurn() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SwitchTurn")
}

// SwitchTurn indicates an expected call of SwitchTurn.
func (mr *MockGameMockRecorder) SwitchTurn() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SwitchTurn", reflect.TypeOf((*MockGame)(nil).SwitchTurn))
}

// TurnState mocks base method.
func (m *MockGame) TurnState() types.TurnState {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TurnState")
	ret0, _ := ret[0].(types.TurnState)
	return ret0
}

// TurnState indicates an expected call of TurnState.
func (mr *MockGameMockRecorder) TurnState() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TurnState", reflect.TypeOf((*MockGame)(nil).TurnState))
}

// MockGameAction is a mock of GameAction interface.
type MockGameAction struct {
	ctrl     *gomock.Controller
	recorder *MockGameActionMockRecorder
}

// MockGameActionMockRecorder is the mock recorder for MockGameAction.
type MockGameActionMockRecorder struct {
	mock *MockGameAction
}

// NewMockGameAction creates a new mock instance.
func NewMockGameAction(ctrl *gomock.Controller) *MockGameAction {
	mock := &MockGameAction{ctrl: ctrl}
	mock.recorder = &MockGameActionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGameAction) EXPECT() *MockGameActionMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockGameAction) Execute(g gameactions.Game) (*gameactions.Result, func() gamestatus.GameStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", g)
	ret0, _ := ret[0].(*gameactions.Result)
	ret1, _ := ret[1].(func() gamestatus.GameStatus)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Execute indicates an expected call of Execute.
func (mr *MockGameActionMockRecorder) Execute(g any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockGameAction)(nil).Execute), g)
}

// NextPhase mocks base method.
func (m *MockGameAction) NextPhase() types.PhaseType {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NextPhase")
	ret0, _ := ret[0].(types.PhaseType)
	return ret0
}

// NextPhase indicates an expected call of NextPhase.
func (mr *MockGameActionMockRecorder) NextPhase() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NextPhase", reflect.TypeOf((*MockGameAction)(nil).NextPhase))
}

// PlayerName mocks base method.
func (m *MockGameAction) PlayerName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PlayerName")
	ret0, _ := ret[0].(string)
	return ret0
}

// PlayerName indicates an expected call of PlayerName.
func (mr *MockGameActionMockRecorder) PlayerName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PlayerName", reflect.TypeOf((*MockGameAction)(nil).PlayerName))
}

// Validate mocks base method.
func (m *MockGameAction) Validate(g gameactions.Game) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validate", g)
	ret0, _ := ret[0].(error)
	return ret0
}

// Validate indicates an expected call of Validate.
func (mr *MockGameActionMockRecorder) Validate(g any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockGameAction)(nil).Validate), g)
}
