// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/domain/gameactions/game_roles.go
//
// Generated by this command:
//
//	mockgen -package mocks -source ./internal/domain/gameactions/game_roles.go -destination ./test/mocks/gameroles_mocks.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	board "github.com/alelopezbcn/thecampaign/internal/domain/board"
	cards "github.com/alelopezbcn/thecampaign/internal/domain/cards"
	gamestatus "github.com/alelopezbcn/thecampaign/internal/domain/gamestatus"
	types "github.com/alelopezbcn/thecampaign/internal/domain/types"
	gomock "go.uber.org/mock/gomock"
)

// MockGamePlayers is a mock of GamePlayers interface.
type MockGamePlayers struct {
	ctrl     *gomock.Controller
	recorder *MockGamePlayersMockRecorder
}

// MockGamePlayersMockRecorder is the mock recorder for MockGamePlayers.
type MockGamePlayersMockRecorder struct {
	mock *MockGamePlayers
}

// NewMockGamePlayers creates a new mock instance.
func NewMockGamePlayers(ctrl *gomock.Controller) *MockGamePlayers {
	mock := &MockGamePlayers{ctrl: ctrl}
	mock.recorder = &MockGamePlayersMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGamePlayers) EXPECT() *MockGamePlayersMockRecorder {
	return m.recorder
}

// Allies mocks base method.
func (m *MockGamePlayers) Allies(playerIdx int) []board.Player {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Allies", playerIdx)
	ret0, _ := ret[0].([]board.Player)
	return ret0
}

// Allies indicates an expected call of Allies.
func (mr *MockGamePlayersMockRecorder) Allies(playerIdx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Allies", reflect.TypeOf((*MockGamePlayers)(nil).Allies), playerIdx)
}

// CurrentPlayer mocks base method.
func (m *MockGamePlayers) CurrentPlayer() board.Player {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CurrentPlayer")
	ret0, _ := ret[0].(board.Player)
	return ret0
}

// CurrentPlayer indicates an expected call of CurrentPlayer.
func (mr *MockGamePlayersMockRecorder) CurrentPlayer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CurrentPlayer", reflect.TypeOf((*MockGamePlayers)(nil).CurrentPlayer))
}

// Enemies mocks base method.
func (m *MockGamePlayers) Enemies(playerIdx int) []board.Player {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enemies", playerIdx)
	ret0, _ := ret[0].([]board.Player)
	return ret0
}

// Enemies indicates an expected call of Enemies.
func (mr *MockGamePlayersMockRecorder) Enemies(playerIdx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enemies", reflect.TypeOf((*MockGamePlayers)(nil).Enemies), playerIdx)
}

// GetPlayer mocks base method.
func (m *MockGamePlayers) GetPlayer(name string) board.Player {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlayer", name)
	ret0, _ := ret[0].(board.Player)
	return ret0
}

// GetPlayer indicates an expected call of GetPlayer.
func (mr *MockGamePlayersMockRecorder) GetPlayer(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlayer", reflect.TypeOf((*MockGamePlayers)(nil).GetPlayer), name)
}

// GetTargetPlayer mocks base method.
func (m *MockGamePlayers) GetTargetPlayer(playerName, targetPlayerName string) (board.Player, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTargetPlayer", playerName, targetPlayerName)
	ret0, _ := ret[0].(board.Player)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTargetPlayer indicates an expected call of GetTargetPlayer.
func (mr *MockGamePlayersMockRecorder) GetTargetPlayer(playerName, targetPlayerName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTargetPlayer", reflect.TypeOf((*MockGamePlayers)(nil).GetTargetPlayer), playerName, targetPlayerName)
}

// PlayerIndex mocks base method.
func (m *MockGamePlayers) PlayerIndex(name string) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PlayerIndex", name)
	ret0, _ := ret[0].(int)
	return ret0
}

// PlayerIndex indicates an expected call of PlayerIndex.
func (mr *MockGamePlayersMockRecorder) PlayerIndex(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PlayerIndex", reflect.TypeOf((*MockGamePlayers)(nil).PlayerIndex), name)
}

// SameTeam mocks base method.
func (m *MockGamePlayers) SameTeam(i, j int) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SameTeam", i, j)
	ret0, _ := ret[0].(bool)
	return ret0
}

// SameTeam indicates an expected call of SameTeam.
func (mr *MockGamePlayersMockRecorder) SameTeam(i, j any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SameTeam", reflect.TypeOf((*MockGamePlayers)(nil).SameTeam), i, j)
}

// MockGameTurn is a mock of GameTurn interface.
type MockGameTurn struct {
	ctrl     *gomock.Controller
	recorder *MockGameTurnMockRecorder
}

// MockGameTurnMockRecorder is the mock recorder for MockGameTurn.
type MockGameTurnMockRecorder struct {
	mock *MockGameTurn
}

// NewMockGameTurn creates a new mock instance.
func NewMockGameTurn(ctrl *gomock.Controller) *MockGameTurn {
	mock := &MockGameTurn{ctrl: ctrl}
	mock.recorder = &MockGameTurnMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGameTurn) EXPECT() *MockGameTurnMockRecorder {
	return m.recorder
}

// CurrentAction mocks base method.
func (m *MockGameTurn) CurrentAction() types.PhaseType {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CurrentAction")
	ret0, _ := ret[0].(types.PhaseType)
	return ret0
}

// CurrentAction indicates an expected call of CurrentAction.
func (mr *MockGameTurnMockRecorder) CurrentAction() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CurrentAction", reflect.TypeOf((*MockGameTurn)(nil).CurrentAction))
}

// SwitchTurn mocks base method.
func (m *MockGameTurn) SwitchTurn() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SwitchTurn")
}

// SwitchTurn indicates an expected call of SwitchTurn.
func (mr *MockGameTurnMockRecorder) SwitchTurn() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SwitchTurn", reflect.TypeOf((*MockGameTurn)(nil).SwitchTurn))
}

// TurnState mocks base method.
func (m *MockGameTurn) TurnState() types.TurnState {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TurnState")
	ret0, _ := ret[0].(types.TurnState)
	return ret0
}

// TurnState indicates an expected call of TurnState.
func (mr *MockGameTurnMockRecorder) TurnState() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TurnState", reflect.TypeOf((*MockGameTurn)(nil).TurnState))
}

// MockGameTurnFlags is a mock of GameTurnFlags interface.
type MockGameTurnFlags struct {
	ctrl     *gomock.Controller
	recorder *MockGameTurnFlagsMockRecorder
}

// MockGameTurnFlagsMockRecorder is the mock recorder for MockGameTurnFlags.
type MockGameTurnFlagsMockRecorder struct {
	mock *MockGameTurnFlags
}

// NewMockGameTurnFlags creates a new mock instance.
func NewMockGameTurnFlags(ctrl *gomock.Controller) *MockGameTurnFlags {
	mock := &MockGameTurnFlags{ctrl: ctrl}
	mock.recorder = &MockGameTurnFlagsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGameTurnFlags) EXPECT() *MockGameTurnFlagsMockRecorder {
	return m.recorder
}

// SetCanForge mocks base method.
func (m *MockGameTurnFlags) SetCanForge(value bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetCanForge", value)
}

// SetCanForge indicates an expected call of SetCanForge.
func (mr *MockGameTurnFlagsMockRecorder) SetCanForge(value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCanForge", reflect.TypeOf((*MockGameTurnFlags)(nil).SetCanForge), value)
}

// SetCanMoveWarrior mocks base method.
func (m *MockGameTurnFlags) SetCanMoveWarrior(value bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetCanMoveWarrior", value)
}

// SetCanMoveWarrior indicates an expected call of SetCanMoveWarrior.
func (mr *MockGameTurnFlagsMockRecorder) SetCanMoveWarrior(value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCanMoveWarrior", reflect.TypeOf((*MockGameTurnFlags)(nil).SetCanMoveWarrior), value)
}

// SetCanTrade mocks base method.
func (m *MockGameTurnFlags) SetCanTrade(value bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetCanTrade", value)
}

// SetCanTrade indicates an expected call of SetCanTrade.
func (mr *MockGameTurnFlagsMockRecorder) SetCanTrade(value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCanTrade", reflect.TypeOf((*MockGameTurnFlags)(nil).SetCanTrade), value)
}

// SetHasForged mocks base method.
func (m *MockGameTurnFlags) SetHasForged(value bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetHasForged", value)
}

// SetHasForged indicates an expected call of SetHasForged.
func (mr *MockGameTurnFlagsMockRecorder) SetHasForged(value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetHasForged", reflect.TypeOf((*MockGameTurnFlags)(nil).SetHasForged), value)
}

// SetHasMovedWarrior mocks base method.
func (m *MockGameTurnFlags) SetHasMovedWarrior(value bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetHasMovedWarrior", value)
}

// SetHasMovedWarrior indicates an expected call of SetHasMovedWarrior.
func (mr *MockGameTurnFlagsMockRecorder) SetHasMovedWarrior(value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetHasMovedWarrior", reflect.TypeOf((*MockGameTurnFlags)(nil).SetHasMovedWarrior), value)
}

// SetHasTraded mocks base method.
func (m *MockGameTurnFlags) SetHasTraded(value bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetHasTraded", value)
}

// SetHasTraded indicates an expected call of SetHasTraded.
func (mr *MockGameTurnFlagsMockRecorder) SetHasTraded(value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetHasTraded", reflect.TypeOf((*MockGameTurnFlags)(nil).SetHasTraded), value)
}

// MockGameStatusProvider is a mock of GameStatusProvider interface.
type MockGameStatusProvider struct {
	ctrl     *gomock.Controller
	recorder *MockGameStatusProviderMockRecorder
}

// MockGameStatusProviderMockRecorder is the mock recorder for MockGameStatusProvider.
type MockGameStatusProviderMockRecorder struct {
	mock *MockGameStatusProvider
}

// NewMockGameStatusProvider creates a new mock instance.
func NewMockGameStatusProvider(ctrl *gomock.Controller) *MockGameStatusProvider {
	mock := &MockGameStatusProvider{ctrl: ctrl}
	mock.recorder = &MockGameStatusProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGameStatusProvider) EXPECT() *MockGameStatusProviderMockRecorder {
	return m.recorder
}

// Status mocks base method.
func (m *MockGameStatusProvider) Status(viewer board.Player, newCards ...cards.Card) gamestatus.GameStatus {
	m.ctrl.T.Helper()
	varargs := []any{viewer}
	for _, a := range newCards {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Status", varargs...)
	ret0, _ := ret[0].(gamestatus.GameStatus)
	return ret0
}

// Status indicates an expected call of Status.
func (mr *MockGameStatusProviderMockRecorder) Status(viewer any, newCards ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{viewer}, newCards...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Status", reflect.TypeOf((*MockGameStatusProvider)(nil).Status), varargs...)
}

// StatusWithModal mocks base method.
func (m *MockGameStatusProvider) StatusWithModal(viewer board.Player, modalCards []cards.Card) gamestatus.GameStatus {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StatusWithModal", viewer, modalCards)
	ret0, _ := ret[0].(gamestatus.GameStatus)
	return ret0
}

// StatusWithModal indicates an expected call of StatusWithModal.
func (mr *MockGameStatusProviderMockRecorder) StatusWithModal(viewer, modalCards any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StatusWithModal", reflect.TypeOf((*MockGameStatusProvider)(nil).StatusWithModal), viewer, modalCards)
}

// MockGameCards is a mock of GameCards interface.
type MockGameCards struct {
	ctrl     *gomock.Controller
	recorder *MockGameCardsMockRecorder
}

// MockGameCardsMockRecorder is the mock recorder for MockGameCards.
type MockGameCardsMockRecorder struct {
	mock *MockGameCards
}

// NewMockGameCards creates a new mock instance.
func NewMockGameCards(ctrl *gomock.Controller) *MockGameCards {
	mock := &MockGameCards{ctrl: ctrl}
	mock.recorder = &MockGameCardsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGameCards) EXPECT() *MockGameCardsMockRecorder {
	return m.recorder
}

// DrawCards mocks base method.
func (m *MockGameCards) DrawCards(p board.Player, count int) ([]cards.Card, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DrawCards", p, count)
	ret0, _ := ret[0].([]cards.Card)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DrawCards indicates an expected call of DrawCards.
func (mr *MockGameCardsMockRecorder) DrawCards(p, count any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DrawCards", reflect.TypeOf((*MockGameCards)(nil).DrawCards), p, count)
}

// OnCardMovedToPile mocks base method.
func (m *MockGameCards) OnCardMovedToPile(card cards.Card) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnCardMovedToPile", card)
}

// OnCardMovedToPile indicates an expected call of OnCardMovedToPile.
func (mr *MockGameCardsMockRecorder) OnCardMovedToPile(card any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnCardMovedToPile", reflect.TypeOf((*MockGameCards)(nil).OnCardMovedToPile), card)
}

// MockGameHistory is a mock of GameHistory interface.
type MockGameHistory struct {
	ctrl     *gomock.Controller
	recorder *MockGameHistoryMockRecorder
}

// MockGameHistoryMockRecorder is the mock recorder for MockGameHistory.
type MockGameHistoryMockRecorder struct {
	mock *MockGameHistory
}

// NewMockGameHistory creates a new mock instance.
func NewMockGameHistory(ctrl *gomock.Controller) *MockGameHistory {
	mock := &MockGameHistory{ctrl: ctrl}
	mock.recorder = &MockGameHistoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGameHistory) EXPECT() *MockGameHistoryMockRecorder {
	return m.recorder
}

// AddHistory mocks base method.
func (m *MockGameHistory) AddHistory(msg string, cat types.Category) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddHistory", msg, cat)
}

// AddHistory indicates an expected call of AddHistory.
func (mr *MockGameHistoryMockRecorder) AddHistory(msg, cat any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddHistory", reflect.TypeOf((*MockGameHistory)(nil).AddHistory), msg, cat)
}

// MockGameBoard is a mock of GameBoard interface.
type MockGameBoard struct {
	ctrl     *gomock.Controller
	recorder *MockGameBoardMockRecorder
}

// MockGameBoardMockRecorder is the mock recorder for MockGameBoard.
type MockGameBoardMockRecorder struct {
	mock *MockGameBoard
}

// NewMockGameBoard creates a new mock instance.
func NewMockGameBoard(ctrl *gomock.Controller) *MockGameBoard {
	mock := &MockGameBoard{ctrl: ctrl}
	mock.recorder = &MockGameBoardMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGameBoard) EXPECT() *MockGameBoardMockRecorder {
	return m.recorder
}

// Board mocks base method.
func (m *MockGameBoard) Board() board.Board {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Board")
	ret0, _ := ret[0].(board.Board)
	return ret0
}

// Board indicates an expected call of Board.
func (mr *MockGameBoardMockRecorder) Board() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Board", reflect.TypeOf((*MockGameBoard)(nil).Board))
}
