// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/domain/ports/hand.go
//
// Generated by this command:
//
//	mockgen -package ports -source ./internal/domain/ports/hand.go -destination ./test/mocks/hand_mocks.go
//

// Package ports is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	ports "github.com/alelopezbcn/thecampaign/internal/domain/ports"
	gomock "go.uber.org/mock/gomock"
)

// MockHand is a mock of Hand interface.
type MockHand struct {
	ctrl     *gomock.Controller
	recorder *MockHandMockRecorder
}

// MockHandMockRecorder is the mock recorder for MockHand.
type MockHandMockRecorder struct {
	mock *MockHand
}

// NewMockHand creates a new mock instance.
func NewMockHand(ctrl *gomock.Controller) *MockHand {
	mock := &MockHand{ctrl: ctrl}
	mock.recorder = &MockHandMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHand) EXPECT() *MockHandMockRecorder {
	return m.recorder
}

// AddCards mocks base method.
func (m *MockHand) AddCards(cards ...ports.Card) error {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range cards {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AddCards", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddCards indicates an expected call of AddCards.
func (mr *MockHandMockRecorder) AddCards(cards ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCards", reflect.TypeOf((*MockHand)(nil).AddCards), cards...)
}

// CanAddCards mocks base method.
func (m *MockHand) CanAddCards(count int) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CanAddCards", count)
	ret0, _ := ret[0].(bool)
	return ret0
}

// CanAddCards indicates an expected call of CanAddCards.
func (mr *MockHandMockRecorder) CanAddCards(count any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CanAddCards", reflect.TypeOf((*MockHand)(nil).CanAddCards), count)
}

// GetCard mocks base method.
func (m *MockHand) GetCard(cardID string) (ports.Card, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCard", cardID)
	ret0, _ := ret[0].(ports.Card)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetCard indicates an expected call of GetCard.
func (mr *MockHandMockRecorder) GetCard(cardID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCard", reflect.TypeOf((*MockHand)(nil).GetCard), cardID)
}

// RemoveCard mocks base method.
func (m *MockHand) RemoveCard(card ports.Card) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveCard", card)
	ret0, _ := ret[0].(bool)
	return ret0
}

// RemoveCard indicates an expected call of RemoveCard.
func (mr *MockHandMockRecorder) RemoveCard(card any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveCard", reflect.TypeOf((*MockHand)(nil).RemoveCard), card)
}

// ShowCards mocks base method.
func (m *MockHand) ShowCards() []ports.Card {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShowCards")
	ret0, _ := ret[0].([]ports.Card)
	return ret0
}

// ShowCards indicates an expected call of ShowCards.
func (mr *MockHandMockRecorder) ShowCards() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShowCards", reflect.TypeOf((*MockHand)(nil).ShowCards))
}
