// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/domain/cards/harpoon.go
//
// Generated by this command:
//
//	mockgen -package mocks -source ./internal/domain/cards/harpoon.go -destination ./test/mocks/harpoon_mocks.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	cards "github.com/alelopezbcn/thecampaign/internal/domain/cards"
	types "github.com/alelopezbcn/thecampaign/internal/domain/types"
	gomock "go.uber.org/mock/gomock"
)

// MockHarpoon is a mock of Harpoon interface.
type MockHarpoon struct {
	ctrl     *gomock.Controller
	recorder *MockHarpoonMockRecorder
}

// MockHarpoonMockRecorder is the mock recorder for MockHarpoon.
type MockHarpoonMockRecorder struct {
	mock *MockHarpoon
}

// NewMockHarpoon creates a new mock instance.
func NewMockHarpoon(ctrl *gomock.Controller) *MockHarpoon {
	mock := &MockHarpoon{ctrl: ctrl}
	mock.recorder = &MockHarpoonMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHarpoon) EXPECT() *MockHarpoonMockRecorder {
	return m.recorder
}

// AddCardMovedToPileObserver mocks base method.
func (m *MockHarpoon) AddCardMovedToPileObserver(observer cards.CardMovedToPileObserver) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddCardMovedToPileObserver", observer)
}

// AddCardMovedToPileObserver indicates an expected call of AddCardMovedToPileObserver.
func (mr *MockHarpoonMockRecorder) AddCardMovedToPileObserver(observer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCardMovedToPileObserver", reflect.TypeOf((*MockHarpoon)(nil).AddCardMovedToPileObserver), observer)
}

// Attack mocks base method.
func (m *MockHarpoon) Attack(target cards.Dragon) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Attack", target)
	ret0, _ := ret[0].(error)
	return ret0
}

// Attack indicates an expected call of Attack.
func (mr *MockHarpoonMockRecorder) Attack(target any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Attack", reflect.TypeOf((*MockHarpoon)(nil).Attack), target)
}

// CanConstruct mocks base method.
func (m *MockHarpoon) CanConstruct() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CanConstruct")
	ret0, _ := ret[0].(bool)
	return ret0
}

// CanConstruct indicates an expected call of CanConstruct.
func (mr *MockHarpoonMockRecorder) CanConstruct() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CanConstruct", reflect.TypeOf((*MockHarpoon)(nil).CanConstruct))
}

// DamageAmount mocks base method.
func (m *MockHarpoon) DamageAmount() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DamageAmount")
	ret0, _ := ret[0].(int)
	return ret0
}

// DamageAmount indicates an expected call of DamageAmount.
func (mr *MockHarpoonMockRecorder) DamageAmount() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DamageAmount", reflect.TypeOf((*MockHarpoon)(nil).DamageAmount))
}

// GetCardMovedToPileObserver mocks base method.
func (m *MockHarpoon) GetCardMovedToPileObserver() cards.CardMovedToPileObserver {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCardMovedToPileObserver")
	ret0, _ := ret[0].(cards.CardMovedToPileObserver)
	return ret0
}

// GetCardMovedToPileObserver indicates an expected call of GetCardMovedToPileObserver.
func (mr *MockHarpoonMockRecorder) GetCardMovedToPileObserver() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCardMovedToPileObserver", reflect.TypeOf((*MockHarpoon)(nil).GetCardMovedToPileObserver))
}

// GetID mocks base method.
func (m *MockHarpoon) GetID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetID")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetID indicates an expected call of GetID.
func (mr *MockHarpoonMockRecorder) GetID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetID", reflect.TypeOf((*MockHarpoon)(nil).GetID))
}

// MultiplierFactor mocks base method.
func (m *MockHarpoon) MultiplierFactor(target cards.Warrior) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MultiplierFactor", target)
	ret0, _ := ret[0].(int)
	return ret0
}

// MultiplierFactor indicates an expected call of MultiplierFactor.
func (mr *MockHarpoonMockRecorder) MultiplierFactor(target any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MultiplierFactor", reflect.TypeOf((*MockHarpoon)(nil).MultiplierFactor), target)
}

// String mocks base method.
func (m *MockHarpoon) String() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "String")
	ret0, _ := ret[0].(string)
	return ret0
}

// String indicates an expected call of String.
func (mr *MockHarpoonMockRecorder) String() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "String", reflect.TypeOf((*MockHarpoon)(nil).String))
}

// Type mocks base method.
func (m *MockHarpoon) Type() types.WeaponType {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Type")
	ret0, _ := ret[0].(types.WeaponType)
	return ret0
}

// Type indicates an expected call of Type.
func (mr *MockHarpoonMockRecorder) Type() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Type", reflect.TypeOf((*MockHarpoon)(nil).Type))
}
