// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/domain/ports/observers.go
//
// Generated by this command:
//
//	mockgen -package mocks -source ./internal/domain/ports/observers.go -destination ./test/mocks/observers_mocks.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	ports "github.com/alelopezbcn/thecampaign/internal/domain/ports"
	gomock "go.uber.org/mock/gomock"
)

// MockCardMovedToPileObserver is a mock of CardMovedToPileObserver interface.
type MockCardMovedToPileObserver struct {
	ctrl     *gomock.Controller
	recorder *MockCardMovedToPileObserverMockRecorder
}

// MockCardMovedToPileObserverMockRecorder is the mock recorder for MockCardMovedToPileObserver.
type MockCardMovedToPileObserverMockRecorder struct {
	mock *MockCardMovedToPileObserver
}

// NewMockCardMovedToPileObserver creates a new mock instance.
func NewMockCardMovedToPileObserver(ctrl *gomock.Controller) *MockCardMovedToPileObserver {
	mock := &MockCardMovedToPileObserver{ctrl: ctrl}
	mock.recorder = &MockCardMovedToPileObserverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCardMovedToPileObserver) EXPECT() *MockCardMovedToPileObserverMockRecorder {
	return m.recorder
}

// OnCardMovedToPile mocks base method.
func (m *MockCardMovedToPileObserver) OnCardMovedToPile(card ports.Card) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnCardMovedToPile", card)
}

// OnCardMovedToPile indicates an expected call of OnCardMovedToPile.
func (mr *MockCardMovedToPileObserverMockRecorder) OnCardMovedToPile(card any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnCardMovedToPile", reflect.TypeOf((*MockCardMovedToPileObserver)(nil).OnCardMovedToPile), card)
}

// MockWarriorDeadObserver is a mock of WarriorDeadObserver interface.
type MockWarriorDeadObserver struct {
	ctrl     *gomock.Controller
	recorder *MockWarriorDeadObserverMockRecorder
}

// MockWarriorDeadObserverMockRecorder is the mock recorder for MockWarriorDeadObserver.
type MockWarriorDeadObserverMockRecorder struct {
	mock *MockWarriorDeadObserver
}

// NewMockWarriorDeadObserver creates a new mock instance.
func NewMockWarriorDeadObserver(ctrl *gomock.Controller) *MockWarriorDeadObserver {
	mock := &MockWarriorDeadObserver{ctrl: ctrl}
	mock.recorder = &MockWarriorDeadObserverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWarriorDeadObserver) EXPECT() *MockWarriorDeadObserverMockRecorder {
	return m.recorder
}

// OnWarriorDead mocks base method.
func (m *MockWarriorDeadObserver) OnWarriorDead(card ports.Warrior) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnWarriorDead", card)
}

// OnWarriorDead indicates an expected call of OnWarriorDead.
func (mr *MockWarriorDeadObserverMockRecorder) OnWarriorDead(card any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnWarriorDead", reflect.TypeOf((*MockWarriorDeadObserver)(nil).OnWarriorDead), card)
}

// MockWarriorMovedToCemeteryObserver is a mock of WarriorMovedToCemeteryObserver interface.
type MockWarriorMovedToCemeteryObserver struct {
	ctrl     *gomock.Controller
	recorder *MockWarriorMovedToCemeteryObserverMockRecorder
}

// MockWarriorMovedToCemeteryObserverMockRecorder is the mock recorder for MockWarriorMovedToCemeteryObserver.
type MockWarriorMovedToCemeteryObserverMockRecorder struct {
	mock *MockWarriorMovedToCemeteryObserver
}

// NewMockWarriorMovedToCemeteryObserver creates a new mock instance.
func NewMockWarriorMovedToCemeteryObserver(ctrl *gomock.Controller) *MockWarriorMovedToCemeteryObserver {
	mock := &MockWarriorMovedToCemeteryObserver{ctrl: ctrl}
	mock.recorder = &MockWarriorMovedToCemeteryObserverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWarriorMovedToCemeteryObserver) EXPECT() *MockWarriorMovedToCemeteryObserverMockRecorder {
	return m.recorder
}

// OnWarriorMovedToCemetery mocks base method.
func (m *MockWarriorMovedToCemeteryObserver) OnWarriorMovedToCemetery(card ports.Warrior) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnWarriorMovedToCemetery", card)
}

// OnWarriorMovedToCemetery indicates an expected call of OnWarriorMovedToCemetery.
func (mr *MockWarriorMovedToCemeteryObserverMockRecorder) OnWarriorMovedToCemetery(card any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnWarriorMovedToCemetery", reflect.TypeOf((*MockWarriorMovedToCemeteryObserver)(nil).OnWarriorMovedToCemetery), card)
}

// MockCastleCompletionObserver is a mock of CastleCompletionObserver interface.
type MockCastleCompletionObserver struct {
	ctrl     *gomock.Controller
	recorder *MockCastleCompletionObserverMockRecorder
}

// MockCastleCompletionObserverMockRecorder is the mock recorder for MockCastleCompletionObserver.
type MockCastleCompletionObserverMockRecorder struct {
	mock *MockCastleCompletionObserver
}

// NewMockCastleCompletionObserver creates a new mock instance.
func NewMockCastleCompletionObserver(ctrl *gomock.Controller) *MockCastleCompletionObserver {
	mock := &MockCastleCompletionObserver{ctrl: ctrl}
	mock.recorder = &MockCastleCompletionObserverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCastleCompletionObserver) EXPECT() *MockCastleCompletionObserverMockRecorder {
	return m.recorder
}

// OnCastleCompletion mocks base method.
func (m *MockCastleCompletionObserver) OnCastleCompletion(p ports.Player) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnCastleCompletion", p)
}

// OnCastleCompletion indicates an expected call of OnCastleCompletion.
func (mr *MockCastleCompletionObserverMockRecorder) OnCastleCompletion(p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnCastleCompletion", reflect.TypeOf((*MockCastleCompletionObserver)(nil).OnCastleCompletion), p)
}

// MockFieldWithoutWarriorsObserver is a mock of FieldWithoutWarriorsObserver interface.
type MockFieldWithoutWarriorsObserver struct {
	ctrl     *gomock.Controller
	recorder *MockFieldWithoutWarriorsObserverMockRecorder
}

// MockFieldWithoutWarriorsObserverMockRecorder is the mock recorder for MockFieldWithoutWarriorsObserver.
type MockFieldWithoutWarriorsObserverMockRecorder struct {
	mock *MockFieldWithoutWarriorsObserver
}

// NewMockFieldWithoutWarriorsObserver creates a new mock instance.
func NewMockFieldWithoutWarriorsObserver(ctrl *gomock.Controller) *MockFieldWithoutWarriorsObserver {
	mock := &MockFieldWithoutWarriorsObserver{ctrl: ctrl}
	mock.recorder = &MockFieldWithoutWarriorsObserverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFieldWithoutWarriorsObserver) EXPECT() *MockFieldWithoutWarriorsObserverMockRecorder {
	return m.recorder
}

// OnFieldWithoutWarriors mocks base method.
func (m *MockFieldWithoutWarriorsObserver) OnFieldWithoutWarriors(p ports.Player) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnFieldWithoutWarriors", p)
}

// OnFieldWithoutWarriors indicates an expected call of OnFieldWithoutWarriors.
func (mr *MockFieldWithoutWarriorsObserverMockRecorder) OnFieldWithoutWarriors(p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnFieldWithoutWarriors", reflect.TypeOf((*MockFieldWithoutWarriorsObserver)(nil).OnFieldWithoutWarriors), p)
}
