// Code generated by MockGen. DO NOT EDIT.
// Source: ./backend/internal/domain/ports/player.go
//
// Generated by this command:
//
//	mockgen -package mocks -source ./backend/internal/domain/ports/player.go -destination ./backend/test/mocks/player_mocks.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	ports "github.com/alelopezbcn/thecampaign/internal/domain/ports"
	gomock "go.uber.org/mock/gomock"
)

// MockPlayer is a mock of Player interface.
type MockPlayer struct {
	ctrl     *gomock.Controller
	recorder *MockPlayerMockRecorder
}

// MockPlayerMockRecorder is the mock recorder for MockPlayer.
type MockPlayerMockRecorder struct {
	mock *MockPlayer
}

// NewMockPlayer creates a new mock instance.
func NewMockPlayer(ctrl *gomock.Controller) *MockPlayer {
	mock := &MockPlayer{ctrl: ctrl}
	mock.recorder = &MockPlayerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPlayer) EXPECT() *MockPlayerMockRecorder {
	return m.recorder
}

// Attack mocks base method.
func (m *MockPlayer) Attack(target ports.Attackable, weapon ports.Weapon) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Attack", target, weapon)
	ret0, _ := ret[0].(error)
	return ret0
}

// Attack indicates an expected call of Attack.
func (mr *MockPlayerMockRecorder) Attack(target, weapon any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Attack", reflect.TypeOf((*MockPlayer)(nil).Attack), target, weapon)
}

// CanAttack mocks base method.
func (m *MockPlayer) CanAttack() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CanAttack")
	ret0, _ := ret[0].(bool)
	return ret0
}

// CanAttack indicates an expected call of CanAttack.
func (mr *MockPlayerMockRecorder) CanAttack() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CanAttack", reflect.TypeOf((*MockPlayer)(nil).CanAttack))
}

// CanBuy mocks base method.
func (m *MockPlayer) CanBuy() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CanBuy")
	ret0, _ := ret[0].(bool)
	return ret0
}

// CanBuy indicates an expected call of CanBuy.
func (mr *MockPlayerMockRecorder) CanBuy() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CanBuy", reflect.TypeOf((*MockPlayer)(nil).CanBuy))
}

// CanBuyWith mocks base method.
func (m *MockPlayer) CanBuyWith(resource ports.Resource) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CanBuyWith", resource)
	ret0, _ := ret[0].(bool)
	return ret0
}

// CanBuyWith indicates an expected call of CanBuyWith.
func (mr *MockPlayerMockRecorder) CanBuyWith(resource any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CanBuyWith", reflect.TypeOf((*MockPlayer)(nil).CanBuyWith), resource)
}

// CanConstruct mocks base method.
func (m *MockPlayer) CanConstruct() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CanConstruct")
	ret0, _ := ret[0].(bool)
	return ret0
}

// CanConstruct indicates an expected call of CanConstruct.
func (mr *MockPlayerMockRecorder) CanConstruct() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CanConstruct", reflect.TypeOf((*MockPlayer)(nil).CanConstruct))
}

// CanTakeCards mocks base method.
func (m *MockPlayer) CanTakeCards(count int) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CanTakeCards", count)
	ret0, _ := ret[0].(bool)
	return ret0
}

// CanTakeCards indicates an expected call of CanTakeCards.
func (mr *MockPlayerMockRecorder) CanTakeCards(count any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CanTakeCards", reflect.TypeOf((*MockPlayer)(nil).CanTakeCards), count)
}

// CanTradeCards mocks base method.
func (m *MockPlayer) CanTradeCards() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CanTradeCards")
	ret0, _ := ret[0].(bool)
	return ret0
}

// CanTradeCards indicates an expected call of CanTradeCards.
func (mr *MockPlayerMockRecorder) CanTradeCards() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CanTradeCards", reflect.TypeOf((*MockPlayer)(nil).CanTradeCards))
}

// CardStolenFromHand mocks base method.
func (m *MockPlayer) CardStolenFromHand(position int) (ports.Card, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CardStolenFromHand", position)
	ret0, _ := ret[0].(ports.Card)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CardStolenFromHand indicates an expected call of CardStolenFromHand.
func (mr *MockPlayerMockRecorder) CardStolenFromHand(position any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CardStolenFromHand", reflect.TypeOf((*MockPlayer)(nil).CardStolenFromHand), position)
}

// CardsInHand mocks base method.
func (m *MockPlayer) CardsInHand() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CardsInHand")
	ret0, _ := ret[0].(int)
	return ret0
}

// CardsInHand indicates an expected call of CardsInHand.
func (mr *MockPlayerMockRecorder) CardsInHand() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CardsInHand", reflect.TypeOf((*MockPlayer)(nil).CardsInHand))
}

// Castle mocks base method.
func (m *MockPlayer) Castle() ports.Castle {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Castle")
	ret0, _ := ret[0].(ports.Castle)
	return ret0
}

// Castle indicates an expected call of Castle.
func (mr *MockPlayerMockRecorder) Castle() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Castle", reflect.TypeOf((*MockPlayer)(nil).Castle))
}

// Catapult mocks base method.
func (m *MockPlayer) Catapult() ports.Catapult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Catapult")
	ret0, _ := ret[0].(ports.Catapult)
	return ret0
}

// Catapult indicates an expected call of Catapult.
func (mr *MockPlayerMockRecorder) Catapult() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Catapult", reflect.TypeOf((*MockPlayer)(nil).Catapult))
}

// Construct mocks base method.
func (m *MockPlayer) Construct(cardID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Construct", cardID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Construct indicates an expected call of Construct.
func (mr *MockPlayerMockRecorder) Construct(cardID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Construct", reflect.TypeOf((*MockPlayer)(nil).Construct), cardID)
}

// Field mocks base method.
func (m *MockPlayer) Field() ports.Field {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Field")
	ret0, _ := ret[0].(ports.Field)
	return ret0
}

// Field indicates an expected call of Field.
func (mr *MockPlayerMockRecorder) Field() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Field", reflect.TypeOf((*MockPlayer)(nil).Field))
}

// GetCardFromField mocks base method.
func (m *MockPlayer) GetCardFromField(cardID string) (ports.Card, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCardFromField", cardID)
	ret0, _ := ret[0].(ports.Card)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetCardFromField indicates an expected call of GetCardFromField.
func (mr *MockPlayerMockRecorder) GetCardFromField(cardID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCardFromField", reflect.TypeOf((*MockPlayer)(nil).GetCardFromField), cardID)
}

// GetCardFromHand mocks base method.
func (m *MockPlayer) GetCardFromHand(cardID string) (ports.Card, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCardFromHand", cardID)
	ret0, _ := ret[0].(ports.Card)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetCardFromHand indicates an expected call of GetCardFromHand.
func (mr *MockPlayerMockRecorder) GetCardFromHand(cardID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCardFromHand", reflect.TypeOf((*MockPlayer)(nil).GetCardFromHand), cardID)
}

// GiveCards mocks base method.
func (m *MockPlayer) GiveCards(cardIDs ...string) ([]ports.Card, error) {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range cardIDs {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GiveCards", varargs...)
	ret0, _ := ret[0].([]ports.Card)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GiveCards indicates an expected call of GiveCards.
func (mr *MockPlayerMockRecorder) GiveCards(cardIDs ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GiveCards", reflect.TypeOf((*MockPlayer)(nil).GiveCards), cardIDs...)
}

// Hand mocks base method.
func (m *MockPlayer) Hand() ports.Hand {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Hand")
	ret0, _ := ret[0].(ports.Hand)
	return ret0
}

// Hand indicates an expected call of Hand.
func (mr *MockPlayerMockRecorder) Hand() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Hand", reflect.TypeOf((*MockPlayer)(nil).Hand))
}

// HasCatapult mocks base method.
func (m *MockPlayer) HasCatapult() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasCatapult")
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasCatapult indicates an expected call of HasCatapult.
func (mr *MockPlayerMockRecorder) HasCatapult() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasCatapult", reflect.TypeOf((*MockPlayer)(nil).HasCatapult))
}

// HasSpy mocks base method.
func (m *MockPlayer) HasSpy() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasSpy")
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasSpy indicates an expected call of HasSpy.
func (mr *MockPlayerMockRecorder) HasSpy() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasSpy", reflect.TypeOf((*MockPlayer)(nil).HasSpy))
}

// HasThief mocks base method.
func (m *MockPlayer) HasThief() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasThief")
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasThief indicates an expected call of HasThief.
func (mr *MockPlayerMockRecorder) HasThief() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasThief", reflect.TypeOf((*MockPlayer)(nil).HasThief))
}

// HasWarriorsInHand mocks base method.
func (m *MockPlayer) HasWarriorsInHand() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasWarriorsInHand")
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasWarriorsInHand indicates an expected call of HasWarriorsInHand.
func (mr *MockPlayerMockRecorder) HasWarriorsInHand() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasWarriorsInHand", reflect.TypeOf((*MockPlayer)(nil).HasWarriorsInHand))
}

// Idx mocks base method.
func (m *MockPlayer) Idx() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Idx")
	ret0, _ := ret[0].(int)
	return ret0
}

// Idx indicates an expected call of Idx.
func (mr *MockPlayerMockRecorder) Idx() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Idx", reflect.TypeOf((*MockPlayer)(nil).Idx))
}

// MoveCardToField mocks base method.
func (m *MockPlayer) MoveCardToField(cardID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MoveCardToField", cardID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MoveCardToField indicates an expected call of MoveCardToField.
func (mr *MockPlayerMockRecorder) MoveCardToField(cardID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MoveCardToField", reflect.TypeOf((*MockPlayer)(nil).MoveCardToField), cardID)
}

// Name mocks base method.
func (m *MockPlayer) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockPlayerMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockPlayer)(nil).Name))
}

// Spy mocks base method.
func (m *MockPlayer) Spy() ports.Spy {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Spy")
	ret0, _ := ret[0].(ports.Spy)
	return ret0
}

// Spy indicates an expected call of Spy.
func (mr *MockPlayerMockRecorder) Spy() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Spy", reflect.TypeOf((*MockPlayer)(nil).Spy))
}

// TakeCards mocks base method.
func (m *MockPlayer) TakeCards(cards ...ports.Card) bool {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range cards {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "TakeCards", varargs...)
	ret0, _ := ret[0].(bool)
	return ret0
}

// TakeCards indicates an expected call of TakeCards.
func (mr *MockPlayerMockRecorder) TakeCards(cards ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TakeCards", reflect.TypeOf((*MockPlayer)(nil).TakeCards), cards...)
}

// Thief mocks base method.
func (m *MockPlayer) Thief() ports.Thief {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Thief")
	ret0, _ := ret[0].(ports.Thief)
	return ret0
}

// Thief indicates an expected call of Thief.
func (mr *MockPlayerMockRecorder) Thief() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Thief", reflect.TypeOf((*MockPlayer)(nil).Thief))
}

// UseSpecialPower mocks base method.
func (m *MockPlayer) UseSpecialPower(usedBy, usedOn ports.Warrior, specialPowerCard ports.SpecialPower) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UseSpecialPower", usedBy, usedOn, specialPowerCard)
	ret0, _ := ret[0].(error)
	return ret0
}

// UseSpecialPower indicates an expected call of UseSpecialPower.
func (mr *MockPlayerMockRecorder) UseSpecialPower(usedBy, usedOn, specialPowerCard any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UseSpecialPower", reflect.TypeOf((*MockPlayer)(nil).UseSpecialPower), usedBy, usedOn, specialPowerCard)
}
