// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/domain/cards/sabotage.go
//
// Generated by this command:
//
//	mockgen -package mocks -source ./internal/domain/cards/sabotage.go -destination ./test/mocks/sabotage_mocks.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	cards "github.com/alelopezbcn/thecampaign/internal/domain/cards"
	gomock "go.uber.org/mock/gomock"
)

// MockSabotage is a mock of Sabotage interface.
type MockSabotage struct {
	ctrl     *gomock.Controller
	recorder *MockSabotageMockRecorder
}

// MockSabotageMockRecorder is the mock recorder for MockSabotage.
type MockSabotageMockRecorder struct {
	mock *MockSabotage
}

// NewMockSabotage creates a new mock instance.
func NewMockSabotage(ctrl *gomock.Controller) *MockSabotage {
	mock := &MockSabotage{ctrl: ctrl}
	mock.recorder = &MockSabotageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSabotage) EXPECT() *MockSabotageMockRecorder {
	return m.recorder
}

// AddCardMovedToPileObserver mocks base method.
func (m *MockSabotage) AddCardMovedToPileObserver(observer cards.CardMovedToPileObserver) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddCardMovedToPileObserver", observer)
}

// AddCardMovedToPileObserver indicates an expected call of AddCardMovedToPileObserver.
func (mr *MockSabotageMockRecorder) AddCardMovedToPileObserver(observer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCardMovedToPileObserver", reflect.TypeOf((*MockSabotage)(nil).AddCardMovedToPileObserver), observer)
}

// CanSabotage mocks base method.
func (m *MockSabotage) CanSabotage() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CanSabotage")
}

// CanSabotage indicates an expected call of CanSabotage.
func (mr *MockSabotageMockRecorder) CanSabotage() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CanSabotage", reflect.TypeOf((*MockSabotage)(nil).CanSabotage))
}

// GetCardMovedToPileObserver mocks base method.
func (m *MockSabotage) GetCardMovedToPileObserver() cards.CardMovedToPileObserver {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCardMovedToPileObserver")
	ret0, _ := ret[0].(cards.CardMovedToPileObserver)
	return ret0
}

// GetCardMovedToPileObserver indicates an expected call of GetCardMovedToPileObserver.
func (mr *MockSabotageMockRecorder) GetCardMovedToPileObserver() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCardMovedToPileObserver", reflect.TypeOf((*MockSabotage)(nil).GetCardMovedToPileObserver))
}

// GetID mocks base method.
func (m *MockSabotage) GetID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetID")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetID indicates an expected call of GetID.
func (mr *MockSabotageMockRecorder) GetID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetID", reflect.TypeOf((*MockSabotage)(nil).GetID))
}

// Name mocks base method.
func (m *MockSabotage) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockSabotageMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockSabotage)(nil).Name))
}
