// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/domain/cards/specialpower.go
//
// Generated by this command:
//
//	mockgen -package mocks -source ./internal/domain/cards/specialpower.go -destination ./test/mocks/specialpower_mocks.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	cards "github.com/alelopezbcn/thecampaign/internal/domain/cards"
	types "github.com/alelopezbcn/thecampaign/internal/domain/types"
	gomock "go.uber.org/mock/gomock"
)

// MockSpecialPower is a mock of SpecialPower interface.
type MockSpecialPower struct {
	ctrl     *gomock.Controller
	recorder *MockSpecialPowerMockRecorder
}

// MockSpecialPowerMockRecorder is the mock recorder for MockSpecialPower.
type MockSpecialPowerMockRecorder struct {
	mock *MockSpecialPower
}

// NewMockSpecialPower creates a new mock instance.
func NewMockSpecialPower(ctrl *gomock.Controller) *MockSpecialPower {
	mock := &MockSpecialPower{ctrl: ctrl}
	mock.recorder = &MockSpecialPowerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSpecialPower) EXPECT() *MockSpecialPowerMockRecorder {
	return m.recorder
}

// AddCardMovedToPileObserver mocks base method.
func (m *MockSpecialPower) AddCardMovedToPileObserver(observer cards.CardMovedToPileObserver) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddCardMovedToPileObserver", observer)
}

// AddCardMovedToPileObserver indicates an expected call of AddCardMovedToPileObserver.
func (mr *MockSpecialPowerMockRecorder) AddCardMovedToPileObserver(observer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCardMovedToPileObserver", reflect.TypeOf((*MockSpecialPower)(nil).AddCardMovedToPileObserver), observer)
}

// AttackedBy mocks base method.
func (m *MockSpecialPower) AttackedBy() []cards.Weapon {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AttackedBy")
	ret0, _ := ret[0].([]cards.Weapon)
	return ret0
}

// AttackedBy indicates an expected call of AttackedBy.
func (mr *MockSpecialPowerMockRecorder) AttackedBy() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AttackedBy", reflect.TypeOf((*MockSpecialPower)(nil).AttackedBy))
}

// BeAttacked mocks base method.
func (m *MockSpecialPower) BeAttacked(weapon cards.Weapon) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeAttacked", weapon)
	ret0, _ := ret[0].(error)
	return ret0
}

// BeAttacked indicates an expected call of BeAttacked.
func (mr *MockSpecialPowerMockRecorder) BeAttacked(weapon any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeAttacked", reflect.TypeOf((*MockSpecialPower)(nil).BeAttacked), weapon)
}

// CanBeTraded mocks base method.
func (m *MockSpecialPower) CanBeTraded() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CanBeTraded")
	ret0, _ := ret[0].(bool)
	return ret0
}

// CanBeTraded indicates an expected call of CanBeTraded.
func (mr *MockSpecialPowerMockRecorder) CanBeTraded() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CanBeTraded", reflect.TypeOf((*MockSpecialPower)(nil).CanBeTraded))
}

// CanBeUsedWith mocks base method.
func (m *MockSpecialPower) CanBeUsedWith(field cards.FieldChecker) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CanBeUsedWith", field)
	ret0, _ := ret[0].(bool)
	return ret0
}

// CanBeUsedWith indicates an expected call of CanBeUsedWith.
func (mr *MockSpecialPowerMockRecorder) CanBeUsedWith(field any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CanBeUsedWith", reflect.TypeOf((*MockSpecialPower)(nil).CanBeUsedWith), field)
}

// CanConstruct mocks base method.
func (m *MockSpecialPower) CanConstruct() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CanConstruct")
	ret0, _ := ret[0].(bool)
	return ret0
}

// CanConstruct indicates an expected call of CanConstruct.
func (mr *MockSpecialPowerMockRecorder) CanConstruct() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CanConstruct", reflect.TypeOf((*MockSpecialPower)(nil).CanConstruct))
}

// DamageAmount mocks base method.
func (m *MockSpecialPower) DamageAmount() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DamageAmount")
	ret0, _ := ret[0].(int)
	return ret0
}

// DamageAmount indicates an expected call of DamageAmount.
func (mr *MockSpecialPowerMockRecorder) DamageAmount() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DamageAmount", reflect.TypeOf((*MockSpecialPower)(nil).DamageAmount))
}

// Destroyed mocks base method.
func (m *MockSpecialPower) Destroyed() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Destroyed")
}

// Destroyed indicates an expected call of Destroyed.
func (mr *MockSpecialPowerMockRecorder) Destroyed() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Destroyed", reflect.TypeOf((*MockSpecialPower)(nil).Destroyed))
}

// GetCardMovedToPileObserver mocks base method.
func (m *MockSpecialPower) GetCardMovedToPileObserver() cards.CardMovedToPileObserver {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCardMovedToPileObserver")
	ret0, _ := ret[0].(cards.CardMovedToPileObserver)
	return ret0
}

// GetCardMovedToPileObserver indicates an expected call of GetCardMovedToPileObserver.
func (mr *MockSpecialPowerMockRecorder) GetCardMovedToPileObserver() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCardMovedToPileObserver", reflect.TypeOf((*MockSpecialPower)(nil).GetCardMovedToPileObserver))
}

// GetID mocks base method.
func (m *MockSpecialPower) GetID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetID")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetID indicates an expected call of GetID.
func (mr *MockSpecialPowerMockRecorder) GetID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetID", reflect.TypeOf((*MockSpecialPower)(nil).GetID))
}

// Health mocks base method.
func (m *MockSpecialPower) Health() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Health")
	ret0, _ := ret[0].(int)
	return ret0
}

// Health indicates an expected call of Health.
func (mr *MockSpecialPowerMockRecorder) Health() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Health", reflect.TypeOf((*MockSpecialPower)(nil).Health))
}

// MultiplierFactor mocks base method.
func (m *MockSpecialPower) MultiplierFactor(target cards.Warrior) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MultiplierFactor", target)
	ret0, _ := ret[0].(int)
	return ret0
}

// MultiplierFactor indicates an expected call of MultiplierFactor.
func (mr *MockSpecialPowerMockRecorder) MultiplierFactor(target any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MultiplierFactor", reflect.TypeOf((*MockSpecialPower)(nil).MultiplierFactor), target)
}

// Name mocks base method.
func (m *MockSpecialPower) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockSpecialPowerMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockSpecialPower)(nil).Name))
}

// ReceiveDamage mocks base method.
func (m *MockSpecialPower) ReceiveDamage(weapon cards.Weapon, multiplier int) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReceiveDamage", weapon, multiplier)
	ret0, _ := ret[0].(bool)
	return ret0
}

// ReceiveDamage indicates an expected call of ReceiveDamage.
func (mr *MockSpecialPowerMockRecorder) ReceiveDamage(weapon, multiplier any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReceiveDamage", reflect.TypeOf((*MockSpecialPower)(nil).ReceiveDamage), weapon, multiplier)
}

// String mocks base method.
func (m *MockSpecialPower) String() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "String")
	ret0, _ := ret[0].(string)
	return ret0
}

// String indicates an expected call of String.
func (mr *MockSpecialPowerMockRecorder) String() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "String", reflect.TypeOf((*MockSpecialPower)(nil).String))
}

// Type mocks base method.
func (m *MockSpecialPower) Type() types.WeaponType {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Type")
	ret0, _ := ret[0].(types.WeaponType)
	return ret0
}

// Type indicates an expected call of Type.
func (mr *MockSpecialPowerMockRecorder) Type() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Type", reflect.TypeOf((*MockSpecialPower)(nil).Type))
}

// Use mocks base method.
func (m *MockSpecialPower) Use(usedBy, target cards.Warrior) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Use", usedBy, target)
	ret0, _ := ret[0].(error)
	return ret0
}

// Use indicates an expected call of Use.
func (mr *MockSpecialPowerMockRecorder) Use(usedBy, target any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Use", reflect.TypeOf((*MockSpecialPower)(nil).Use), usedBy, target)
}
