// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/domain/cards/spy.go
//
// Generated by this command:
//
//	mockgen -package mocks -source ./internal/domain/cards/spy.go -destination ./test/mocks/spy_mocks.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	cards "github.com/alelopezbcn/thecampaign/internal/domain/cards"
	gomock "go.uber.org/mock/gomock"
)

// MockSpy is a mock of Spy interface.
type MockSpy struct {
	ctrl     *gomock.Controller
	recorder *MockSpyMockRecorder
}

// MockSpyMockRecorder is the mock recorder for MockSpy.
type MockSpyMockRecorder struct {
	mock *MockSpy
}

// NewMockSpy creates a new mock instance.
func NewMockSpy(ctrl *gomock.Controller) *MockSpy {
	mock := &MockSpy{ctrl: ctrl}
	mock.recorder = &MockSpyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSpy) EXPECT() *MockSpyMockRecorder {
	return m.recorder
}

// AddCardMovedToPileObserver mocks base method.
func (m *MockSpy) AddCardMovedToPileObserver(observer cards.CardMovedToPileObserver) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddCardMovedToPileObserver", observer)
}

// AddCardMovedToPileObserver indicates an expected call of AddCardMovedToPileObserver.
func (mr *MockSpyMockRecorder) AddCardMovedToPileObserver(observer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCardMovedToPileObserver", reflect.TypeOf((*MockSpy)(nil).AddCardMovedToPileObserver), observer)
}

// CanSpy mocks base method.
func (m *MockSpy) CanSpy() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CanSpy")
}

// CanSpy indicates an expected call of CanSpy.
func (mr *MockSpyMockRecorder) CanSpy() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CanSpy", reflect.TypeOf((*MockSpy)(nil).CanSpy))
}

// GetCardMovedToPileObserver mocks base method.
func (m *MockSpy) GetCardMovedToPileObserver() cards.CardMovedToPileObserver {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCardMovedToPileObserver")
	ret0, _ := ret[0].(cards.CardMovedToPileObserver)
	return ret0
}

// GetCardMovedToPileObserver indicates an expected call of GetCardMovedToPileObserver.
func (mr *MockSpyMockRecorder) GetCardMovedToPileObserver() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCardMovedToPileObserver", reflect.TypeOf((*MockSpy)(nil).GetCardMovedToPileObserver))
}

// GetID mocks base method.
func (m *MockSpy) GetID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetID")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetID indicates an expected call of GetID.
func (mr *MockSpyMockRecorder) GetID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetID", reflect.TypeOf((*MockSpy)(nil).GetID))
}

// Name mocks base method.
func (m *MockSpy) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockSpyMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockSpy)(nil).Name))
}
