// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/domain/cards/thief.go
//
// Generated by this command:
//
//	mockgen -package mocks -source ./internal/domain/cards/thief.go -destination ./test/mocks/thief_mocks.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	cards "github.com/alelopezbcn/thecampaign/internal/domain/cards"
	gomock "go.uber.org/mock/gomock"
)

// MockThief is a mock of Thief interface.
type MockThief struct {
	ctrl     *gomock.Controller
	recorder *MockThiefMockRecorder
}

// MockThiefMockRecorder is the mock recorder for MockThief.
type MockThiefMockRecorder struct {
	mock *MockThief
}

// NewMockThief creates a new mock instance.
func NewMockThief(ctrl *gomock.Controller) *MockThief {
	mock := &MockThief{ctrl: ctrl}
	mock.recorder = &MockThiefMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockThief) EXPECT() *MockThiefMockRecorder {
	return m.recorder
}

// AddCardMovedToPileObserver mocks base method.
func (m *MockThief) AddCardMovedToPileObserver(observer cards.CardMovedToPileObserver) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddCardMovedToPileObserver", observer)
}

// AddCardMovedToPileObserver indicates an expected call of AddCardMovedToPileObserver.
func (mr *MockThiefMockRecorder) AddCardMovedToPileObserver(observer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCardMovedToPileObserver", reflect.TypeOf((*MockThief)(nil).AddCardMovedToPileObserver), observer)
}

// CanSteal mocks base method.
func (m *MockThief) CanSteal() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CanSteal")
}

// CanSteal indicates an expected call of CanSteal.
func (mr *MockThiefMockRecorder) CanSteal() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CanSteal", reflect.TypeOf((*MockThief)(nil).CanSteal))
}

// GetCardMovedToPileObserver mocks base method.
func (m *MockThief) GetCardMovedToPileObserver() cards.CardMovedToPileObserver {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCardMovedToPileObserver")
	ret0, _ := ret[0].(cards.CardMovedToPileObserver)
	return ret0
}

// GetCardMovedToPileObserver indicates an expected call of GetCardMovedToPileObserver.
func (mr *MockThiefMockRecorder) GetCardMovedToPileObserver() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCardMovedToPileObserver", reflect.TypeOf((*MockThief)(nil).GetCardMovedToPileObserver))
}

// GetID mocks base method.
func (m *MockThief) GetID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetID")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetID indicates an expected call of GetID.
func (mr *MockThiefMockRecorder) GetID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetID", reflect.TypeOf((*MockThief)(nil).GetID))
}

// Name mocks base method.
func (m *MockThief) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockThiefMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockThief)(nil).Name))
}
