// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/domain/cards/treason.go
//
// Generated by this command:
//
//	mockgen -package mocks -source ./internal/domain/cards/treason.go -destination ./test/mocks/treason_mocks.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	cards "github.com/alelopezbcn/thecampaign/internal/domain/cards"
	gomock "go.uber.org/mock/gomock"
)

// MockTreason is a mock of Treason interface.
type MockTreason struct {
	ctrl     *gomock.Controller
	recorder *MockTreasonMockRecorder
}

// MockTreasonMockRecorder is the mock recorder for MockTreason.
type MockTreasonMockRecorder struct {
	mock *MockTreason
}

// NewMockTreason creates a new mock instance.
func NewMockTreason(ctrl *gomock.Controller) *MockTreason {
	mock := &MockTreason{ctrl: ctrl}
	mock.recorder = &MockTreasonMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTreason) EXPECT() *MockTreasonMockRecorder {
	return m.recorder
}

// AddCardMovedToPileObserver mocks base method.
func (m *MockTreason) AddCardMovedToPileObserver(observer cards.CardMovedToPileObserver) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddCardMovedToPileObserver", observer)
}

// AddCardMovedToPileObserver indicates an expected call of AddCardMovedToPileObserver.
func (mr *MockTreasonMockRecorder) AddCardMovedToPileObserver(observer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCardMovedToPileObserver", reflect.TypeOf((*MockTreason)(nil).AddCardMovedToPileObserver), observer)
}

// CanTreason mocks base method.
func (m *MockTreason) CanTreason() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CanTreason")
}

// CanTreason indicates an expected call of CanTreason.
func (mr *MockTreasonMockRecorder) CanTreason() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CanTreason", reflect.TypeOf((*MockTreason)(nil).CanTreason))
}

// GetCardMovedToPileObserver mocks base method.
func (m *MockTreason) GetCardMovedToPileObserver() cards.CardMovedToPileObserver {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCardMovedToPileObserver")
	ret0, _ := ret[0].(cards.CardMovedToPileObserver)
	return ret0
}

// GetCardMovedToPileObserver indicates an expected call of GetCardMovedToPileObserver.
func (mr *MockTreasonMockRecorder) GetCardMovedToPileObserver() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCardMovedToPileObserver", reflect.TypeOf((*MockTreason)(nil).GetCardMovedToPileObserver))
}

// GetID mocks base method.
func (m *MockTreason) GetID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetID")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetID indicates an expected call of GetID.
func (mr *MockTreasonMockRecorder) GetID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetID", reflect.TypeOf((*MockTreason)(nil).GetID))
}

// Name mocks base method.
func (m *MockTreason) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockTreasonMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockTreason)(nil).Name))
}
