// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/domain/cards/warriors.go
//
// Generated by this command:
//
//	mockgen -package mocks -source ./internal/domain/cards/warriors.go -destination ./test/mocks/warrior_mocks.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	cards "github.com/alelopezbcn/thecampaign/internal/domain/cards"
	types "github.com/alelopezbcn/thecampaign/internal/domain/types"
	gomock "go.uber.org/mock/gomock"
)

// MockWarrior is a mock of Warrior interface.
type MockWarrior struct {
	ctrl     *gomock.Controller
	recorder *MockWarriorMockRecorder
}

// MockWarriorMockRecorder is the mock recorder for MockWarrior.
type MockWarriorMockRecorder struct {
	mock *MockWarrior
}

// NewMockWarrior creates a new mock instance.
func NewMockWarrior(ctrl *gomock.Controller) *MockWarrior {
	mock := &MockWarrior{ctrl: ctrl}
	mock.recorder = &MockWarriorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWarrior) EXPECT() *MockWarriorMockRecorder {
	return m.recorder
}

// AddCardMovedToPileObserver mocks base method.
func (m *MockWarrior) AddCardMovedToPileObserver(observer cards.CardMovedToPileObserver) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddCardMovedToPileObserver", observer)
}

// AddCardMovedToPileObserver indicates an expected call of AddCardMovedToPileObserver.
func (mr *MockWarriorMockRecorder) AddCardMovedToPileObserver(observer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCardMovedToPileObserver", reflect.TypeOf((*MockWarrior)(nil).AddCardMovedToPileObserver), observer)
}

// AddWarriorDeadObserver mocks base method.
func (m *MockWarrior) AddWarriorDeadObserver(o cards.WarriorDeadObserver) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddWarriorDeadObserver", o)
}

// AddWarriorDeadObserver indicates an expected call of AddWarriorDeadObserver.
func (mr *MockWarriorMockRecorder) AddWarriorDeadObserver(o any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddWarriorDeadObserver", reflect.TypeOf((*MockWarrior)(nil).AddWarriorDeadObserver), o)
}

// AttackedBy mocks base method.
func (m *MockWarrior) AttackedBy() []cards.Weapon {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AttackedBy")
	ret0, _ := ret[0].([]cards.Weapon)
	return ret0
}

// AttackedBy indicates an expected call of AttackedBy.
func (mr *MockWarriorMockRecorder) AttackedBy() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AttackedBy", reflect.TypeOf((*MockWarrior)(nil).AttackedBy))
}

// BeAttacked mocks base method.
func (m *MockWarrior) BeAttacked(weapon cards.Weapon) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeAttacked", weapon)
	ret0, _ := ret[0].(error)
	return ret0
}

// BeAttacked indicates an expected call of BeAttacked.
func (mr *MockWarriorMockRecorder) BeAttacked(weapon any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeAttacked", reflect.TypeOf((*MockWarrior)(nil).BeAttacked), weapon)
}

// GetCardMovedToPileObserver mocks base method.
func (m *MockWarrior) GetCardMovedToPileObserver() cards.CardMovedToPileObserver {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCardMovedToPileObserver")
	ret0, _ := ret[0].(cards.CardMovedToPileObserver)
	return ret0
}

// GetCardMovedToPileObserver indicates an expected call of GetCardMovedToPileObserver.
func (mr *MockWarriorMockRecorder) GetCardMovedToPileObserver() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCardMovedToPileObserver", reflect.TypeOf((*MockWarrior)(nil).GetCardMovedToPileObserver))
}

// GetID mocks base method.
func (m *MockWarrior) GetID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetID")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetID indicates an expected call of GetID.
func (mr *MockWarriorMockRecorder) GetID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetID", reflect.TypeOf((*MockWarrior)(nil).GetID))
}

// Heal mocks base method.
func (m *MockWarrior) Heal(powerCard cards.SpecialPower) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Heal", powerCard)
}

// Heal indicates an expected call of Heal.
func (mr *MockWarriorMockRecorder) Heal(powerCard any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Heal", reflect.TypeOf((*MockWarrior)(nil).Heal), powerCard)
}

// Health mocks base method.
func (m *MockWarrior) Health() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Health")
	ret0, _ := ret[0].(int)
	return ret0
}

// Health indicates an expected call of Health.
func (mr *MockWarriorMockRecorder) Health() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Health", reflect.TypeOf((*MockWarrior)(nil).Health))
}

// InstantKill mocks base method.
func (m *MockWarrior) InstantKill(sp cards.SpecialPower) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "InstantKill", sp)
}

// InstantKill indicates an expected call of InstantKill.
func (mr *MockWarriorMockRecorder) InstantKill(sp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InstantKill", reflect.TypeOf((*MockWarrior)(nil).InstantKill), sp)
}

// Resurrect mocks base method.
func (m *MockWarrior) Resurrect() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Resurrect")
}

// Resurrect indicates an expected call of Resurrect.
func (mr *MockWarriorMockRecorder) Resurrect() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resurrect", reflect.TypeOf((*MockWarrior)(nil).Resurrect))
}

// IsDamaged mocks base method.
func (m *MockWarrior) IsDamaged() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsDamaged")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsDamaged indicates an expected call of IsDamaged.
func (mr *MockWarriorMockRecorder) IsDamaged() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsDamaged", reflect.TypeOf((*MockWarrior)(nil).IsDamaged))
}

// IsProtected mocks base method.
func (m *MockWarrior) IsProtected() (bool, cards.SpecialPower) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsProtected")
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(cards.SpecialPower)
	return ret0, ret1
}

// IsProtected indicates an expected call of IsProtected.
func (mr *MockWarriorMockRecorder) IsProtected() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsProtected", reflect.TypeOf((*MockWarrior)(nil).IsProtected))
}

// Name mocks base method.
func (m *MockWarrior) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockWarriorMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockWarrior)(nil).Name))
}

// Protect mocks base method.
func (m *MockWarrior) Protect(powerCard cards.SpecialPower) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Protect", powerCard)
	ret0, _ := ret[0].(error)
	return ret0
}

// Protect indicates an expected call of Protect.
func (mr *MockWarriorMockRecorder) Protect(powerCard any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Protect", reflect.TypeOf((*MockWarrior)(nil).Protect), powerCard)
}

// ReceiveDamage mocks base method.
func (m *MockWarrior) ReceiveDamage(weapon cards.Weapon, multiplier int) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReceiveDamage", weapon, multiplier)
	ret0, _ := ret[0].(bool)
	return ret0
}

// ReceiveDamage indicates an expected call of ReceiveDamage.
func (mr *MockWarriorMockRecorder) ReceiveDamage(weapon, multiplier any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReceiveDamage", reflect.TypeOf((*MockWarrior)(nil).ReceiveDamage), weapon, multiplier)
}

// String mocks base method.
func (m *MockWarrior) String() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "String")
	ret0, _ := ret[0].(string)
	return ret0
}

// String indicates an expected call of String.
func (mr *MockWarriorMockRecorder) String() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "String", reflect.TypeOf((*MockWarrior)(nil).String))
}

// Type mocks base method.
func (m *MockWarrior) Type() types.WarriorType {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Type")
	ret0, _ := ret[0].(types.WarriorType)
	return ret0
}

// Type indicates an expected call of Type.
func (mr *MockWarriorMockRecorder) Type() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Type", reflect.TypeOf((*MockWarrior)(nil).Type))
}
