// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/domain/cards/weapons.go
//
// Generated by this command:
//
//	mockgen -package mocks -source ./internal/domain/cards/weapons.go -destination ./test/mocks/weapon_mocks.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	cards "github.com/alelopezbcn/thecampaign/internal/domain/cards"
	types "github.com/alelopezbcn/thecampaign/internal/domain/types"
	gomock "go.uber.org/mock/gomock"
)

// MockWeapon is a mock of Weapon interface.
type MockWeapon struct {
	ctrl     *gomock.Controller
	recorder *MockWeaponMockRecorder
}

// MockWeaponMockRecorder is the mock recorder for MockWeapon.
type MockWeaponMockRecorder struct {
	mock *MockWeapon
}

// NewMockWeapon creates a new mock instance.
func NewMockWeapon(ctrl *gomock.Controller) *MockWeapon {
	mock := &MockWeapon{ctrl: ctrl}
	mock.recorder = &MockWeaponMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWeapon) EXPECT() *MockWeaponMockRecorder {
	return m.recorder
}

// AddCardMovedToPileObserver mocks base method.
func (m *MockWeapon) AddCardMovedToPileObserver(observer cards.CardMovedToPileObserver) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddCardMovedToPileObserver", observer)
}

// AddCardMovedToPileObserver indicates an expected call of AddCardMovedToPileObserver.
func (mr *MockWeaponMockRecorder) AddCardMovedToPileObserver(observer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCardMovedToPileObserver", reflect.TypeOf((*MockWeapon)(nil).AddCardMovedToPileObserver), observer)
}

// CanConstruct mocks base method.
func (m *MockWeapon) CanConstruct() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CanConstruct")
	ret0, _ := ret[0].(bool)
	return ret0
}

// CanConstruct indicates an expected call of CanConstruct.
func (mr *MockWeaponMockRecorder) CanConstruct() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CanConstruct", reflect.TypeOf((*MockWeapon)(nil).CanConstruct))
}

// DamageAmount mocks base method.
func (m *MockWeapon) DamageAmount() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DamageAmount")
	ret0, _ := ret[0].(int)
	return ret0
}

// DamageAmount indicates an expected call of DamageAmount.
func (mr *MockWeaponMockRecorder) DamageAmount() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DamageAmount", reflect.TypeOf((*MockWeapon)(nil).DamageAmount))
}

// GetCardMovedToPileObserver mocks base method.
func (m *MockWeapon) GetCardMovedToPileObserver() cards.CardMovedToPileObserver {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCardMovedToPileObserver")
	ret0, _ := ret[0].(cards.CardMovedToPileObserver)
	return ret0
}

// GetCardMovedToPileObserver indicates an expected call of GetCardMovedToPileObserver.
func (mr *MockWeaponMockRecorder) GetCardMovedToPileObserver() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCardMovedToPileObserver", reflect.TypeOf((*MockWeapon)(nil).GetCardMovedToPileObserver))
}

// GetID mocks base method.
func (m *MockWeapon) GetID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetID")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetID indicates an expected call of GetID.
func (mr *MockWeaponMockRecorder) GetID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetID", reflect.TypeOf((*MockWeapon)(nil).GetID))
}

// MultiplierFactor mocks base method.
func (m *MockWeapon) MultiplierFactor(target cards.Warrior) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MultiplierFactor", target)
	ret0, _ := ret[0].(int)
	return ret0
}

// MultiplierFactor indicates an expected call of MultiplierFactor.
func (mr *MockWeaponMockRecorder) MultiplierFactor(target any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MultiplierFactor", reflect.TypeOf((*MockWeapon)(nil).MultiplierFactor), target)
}

// String mocks base method.
func (m *MockWeapon) String() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "String")
	ret0, _ := ret[0].(string)
	return ret0
}

// String indicates an expected call of String.
func (mr *MockWeaponMockRecorder) String() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "String", reflect.TypeOf((*MockWeapon)(nil).String))
}

// Type mocks base method.
func (m *MockWeapon) Type() types.WeaponType {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Type")
	ret0, _ := ret[0].(types.WeaponType)
	return ret0
}

// Type indicates an expected call of Type.
func (mr *MockWeaponMockRecorder) Type() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Type", reflect.TypeOf((*MockWeapon)(nil).Type))
}
