// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/domain/game/game.go
//
// Generated by this command:
//
//	mockgen -package game -source ./internal/domain/game/game.go -destination ./internal/domain/game/board_mocks.go
//

// Package game is a generated GoMock package.
package game

import (
	reflect "reflect"

	board "github.com/alelopezbcn/thecampaign/internal/domain/board"
	gomock "go.uber.org/mock/gomock"
)

// MockBoard is a mock of Board interface.
type MockBoard struct {
	ctrl     *gomock.Controller
	recorder *MockBoardMockRecorder
}

// MockBoardMockRecorder is the mock recorder for MockBoard.
type MockBoardMockRecorder struct {
	mock *MockBoard
}

// NewMockBoard creates a new mock instance.
func NewMockBoard(ctrl *gomock.Controller) *MockBoard {
	mock := &MockBoard{ctrl: ctrl}
	mock.recorder = &MockBoardMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBoard) EXPECT() *MockBoardMockRecorder {
	return m.recorder
}

// Cemetery mocks base method.
func (m *MockBoard) Cemetery() board.Cemetery {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cemetery")
	ret0, _ := ret[0].(board.Cemetery)
	return ret0
}

// Cemetery indicates an expected call of Cemetery.
func (mr *MockBoardMockRecorder) Cemetery() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cemetery", reflect.TypeOf((*MockBoard)(nil).Cemetery))
}

// Deck mocks base method.
func (m *MockBoard) Deck() board.Deck {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Deck")
	ret0, _ := ret[0].(board.Deck)
	return ret0
}

// Deck indicates an expected call of Deck.
func (mr *MockBoardMockRecorder) Deck() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Deck", reflect.TypeOf((*MockBoard)(nil).Deck))
}

// DiscardPile mocks base method.
func (m *MockBoard) DiscardPile() board.DiscardPile {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DiscardPile")
	ret0, _ := ret[0].(board.DiscardPile)
	return ret0
}

// DiscardPile indicates an expected call of DiscardPile.
func (mr *MockBoardMockRecorder) DiscardPile() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DiscardPile", reflect.TypeOf((*MockBoard)(nil).DiscardPile))
}

// Players mocks base method.
func (m *MockBoard) Players() []board.Player {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Players")
	ret0, _ := ret[0].([]board.Player)
	return ret0
}

// Players indicates an expected call of Players.
func (mr *MockBoardMockRecorder) Players() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Players", reflect.TypeOf((*MockBoard)(nil).Players))
}
