// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/domain/game/gamestatusprovider.go
//
// Generated by this command:
//
//	mockgen -package game -source ./internal/domain/game/gamestatusprovider.go -destination ./internal/domain/game/gamestatusprovider_mocks.go
//

// Package game is a generated GoMock package.
package game

import (
	reflect "reflect"

	board "github.com/alelopezbcn/thecampaign/internal/domain/board"
	cards "github.com/alelopezbcn/thecampaign/internal/domain/cards"
	gamestatus "github.com/alelopezbcn/thecampaign/internal/domain/gamestatus"
	gomock "go.uber.org/mock/gomock"
)

// MockGameStatusProvider is a mock of GameStatusProvider interface.
type MockGameStatusProvider struct {
	ctrl     *gomock.Controller
	recorder *MockGameStatusProviderMockRecorder
}

// MockGameStatusProviderMockRecorder is the mock recorder for MockGameStatusProvider.
type MockGameStatusProviderMockRecorder struct {
	mock *MockGameStatusProvider
}

// NewMockGameStatusProvider creates a new mock instance.
func NewMockGameStatusProvider(ctrl *gomock.Controller) *MockGameStatusProvider {
	mock := &MockGameStatusProvider{ctrl: ctrl}
	mock.recorder = &MockGameStatusProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGameStatusProvider) EXPECT() *MockGameStatusProviderMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockGameStatusProvider) Get(viewer board.Player, game *Game, newCards ...cards.Card) gamestatus.GameStatus {
	m.ctrl.T.Helper()
	varargs := []any{viewer, game}
	for _, a := range newCards {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Get", varargs...)
	ret0, _ := ret[0].(gamestatus.GameStatus)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockGameStatusProviderMockRecorder) Get(viewer, game any, newCards ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{viewer, game}, newCards...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockGameStatusProvider)(nil).Get), varargs...)
}

// GetWithModal mocks base method.
func (m *MockGameStatusProvider) GetWithModal(viewer board.Player, game *Game, modalCards []cards.Card) gamestatus.GameStatus {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWithModal", viewer, game, modalCards)
	ret0, _ := ret[0].(gamestatus.GameStatus)
	return ret0
}

// GetWithModal indicates an expected call of GetWithModal.
func (mr *MockGameStatusProviderMockRecorder) GetWithModal(viewer, game, modalCards any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWithModal", reflect.TypeOf((*MockGameStatusProvider)(nil).GetWithModal), viewer, game, modalCards)
}
