// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/domain/game/game.go
//
// Generated by this command:
//
//	mockgen -package game -source ./internal/domain/game/game.go -destination ./internal/domain/game/game_mocks.go
//

// Package game is a generated GoMock package.
package game

import (
	reflect "reflect"
	time "time"

	board "github.com/alelopezbcn/thecampaign/internal/domain/board"
	cards "github.com/alelopezbcn/thecampaign/internal/domain/cards"
	types "github.com/alelopezbcn/thecampaign/internal/domain/types"
	gomock "go.uber.org/mock/gomock"
)

// MockBoard is a mock of Board interface.
type MockBoard struct {
	ctrl     *gomock.Controller
	recorder *MockBoardMockRecorder
}

// MockBoardMockRecorder is the mock recorder for MockBoard.
type MockBoardMockRecorder struct {
	mock *MockBoard
}

// NewMockBoard creates a new mock instance.
func NewMockBoard(ctrl *gomock.Controller) *MockBoard {
	mock := &MockBoard{ctrl: ctrl}
	mock.recorder = &MockBoardMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBoard) EXPECT() *MockBoardMockRecorder {
	return m.recorder
}

// Cemetery mocks base method.
func (m *MockBoard) Cemetery() board.Cemetery {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cemetery")
	ret0, _ := ret[0].(board.Cemetery)
	return ret0
}

// Cemetery indicates an expected call of Cemetery.
func (mr *MockBoardMockRecorder) Cemetery() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cemetery", reflect.TypeOf((*MockBoard)(nil).Cemetery))
}

// Deck mocks base method.
func (m *MockBoard) Deck() board.Deck {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Deck")
	ret0, _ := ret[0].(board.Deck)
	return ret0
}

// Deck indicates an expected call of Deck.
func (mr *MockBoardMockRecorder) Deck() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Deck", reflect.TypeOf((*MockBoard)(nil).Deck))
}

// DiscardPile mocks base method.
func (m *MockBoard) DiscardPile() board.DiscardPile {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DiscardPile")
	ret0, _ := ret[0].(board.DiscardPile)
	return ret0
}

// DiscardPile indicates an expected call of DiscardPile.
func (mr *MockBoardMockRecorder) DiscardPile() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DiscardPile", reflect.TypeOf((*MockBoard)(nil).DiscardPile))
}

// Players mocks base method.
func (m *MockBoard) Players() []board.Player {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Players")
	ret0, _ := ret[0].([]board.Player)
	return ret0
}

// Players indicates an expected call of Players.
func (mr *MockBoardMockRecorder) Players() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Players", reflect.TypeOf((*MockBoard)(nil).Players))
}

// MockGame is a mock of Game interface.
type MockGame struct {
	ctrl     *gomock.Controller
	recorder *MockGameMockRecorder
}

// MockGameMockRecorder is the mock recorder for MockGame.
type MockGameMockRecorder struct {
	mock *MockGame
}

// NewMockGame creates a new mock instance.
func NewMockGame(ctrl *gomock.Controller) *MockGame {
	mock := &MockGame{ctrl: ctrl}
	mock.recorder = &MockGameMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGame) EXPECT() *MockGameMockRecorder {
	return m.recorder
}

// AddHistory mocks base method.
func (m *MockGame) AddHistory(msg string, cat types.Category) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddHistory", msg, cat)
}

// AddHistory indicates an expected call of AddHistory.
func (mr *MockGameMockRecorder) AddHistory(msg, cat any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddHistory", reflect.TypeOf((*MockGame)(nil).AddHistory), msg, cat)
}

// Allies mocks base method.
func (m *MockGame) Allies(playerIdx int) []board.Player {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Allies", playerIdx)
	ret0, _ := ret[0].([]board.Player)
	return ret0
}

// Allies indicates an expected call of Allies.
func (mr *MockGameMockRecorder) Allies(playerIdx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Allies", reflect.TypeOf((*MockGame)(nil).Allies), playerIdx)
}

// Board mocks base method.
func (m *MockGame) Board() Board {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Board")
	ret0, _ := ret[0].(Board)
	return ret0
}

// Board indicates an expected call of Board.
func (mr *MockGameMockRecorder) Board() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Board", reflect.TypeOf((*MockGame)(nil).Board))
}

// CurrentAction mocks base method.
func (m *MockGame) CurrentAction() types.PhaseType {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CurrentAction")
	ret0, _ := ret[0].(types.PhaseType)
	return ret0
}

// CurrentAction indicates an expected call of CurrentAction.
func (mr *MockGameMockRecorder) CurrentAction() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CurrentAction", reflect.TypeOf((*MockGame)(nil).CurrentAction))
}

// CurrentPlayer mocks base method.
func (m *MockGame) CurrentPlayer() board.Player {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CurrentPlayer")
	ret0, _ := ret[0].(board.Player)
	return ret0
}

// CurrentPlayer indicates an expected call of CurrentPlayer.
func (mr *MockGameMockRecorder) CurrentPlayer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CurrentPlayer", reflect.TypeOf((*MockGame)(nil).CurrentPlayer))
}

// DisconnectedPlayers mocks base method.
func (m *MockGame) DisconnectedPlayers() map[int]bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DisconnectedPlayers")
	ret0, _ := ret[0].(map[int]bool)
	return ret0
}

// DisconnectedPlayers indicates an expected call of DisconnectedPlayers.
func (mr *MockGameMockRecorder) DisconnectedPlayers() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DisconnectedPlayers", reflect.TypeOf((*MockGame)(nil).DisconnectedPlayers))
}

// DrawCards mocks base method.
func (m *MockGame) DrawCards(p board.Player, count int) ([]cards.Card, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DrawCards", p, count)
	ret0, _ := ret[0].([]cards.Card)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DrawCards indicates an expected call of DrawCards.
func (mr *MockGameMockRecorder) DrawCards(p, count any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DrawCards", reflect.TypeOf((*MockGame)(nil).DrawCards), p, count)
}

// EliminatedPlayers mocks base method.
func (m *MockGame) EliminatedPlayers() map[int]bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EliminatedPlayers")
	ret0, _ := ret[0].(map[int]bool)
	return ret0
}

// EliminatedPlayers indicates an expected call of EliminatedPlayers.
func (mr *MockGameMockRecorder) EliminatedPlayers() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EliminatedPlayers", reflect.TypeOf((*MockGame)(nil).EliminatedPlayers))
}

// Enemies mocks base method.
func (m *MockGame) Enemies(playerIdx int) []board.Player {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enemies", playerIdx)
	ret0, _ := ret[0].([]board.Player)
	return ret0
}

// Enemies indicates an expected call of Enemies.
func (mr *MockGameMockRecorder) Enemies(playerIdx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enemies", reflect.TypeOf((*MockGame)(nil).Enemies), playerIdx)
}

// GameStartedAt mocks base method.
func (m *MockGame) GameStartedAt() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GameStartedAt")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// GameStartedAt indicates an expected call of GameStartedAt.
func (mr *MockGameMockRecorder) GameStartedAt() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GameStartedAt", reflect.TypeOf((*MockGame)(nil).GameStartedAt))
}

// GameStatusProvider mocks base method.
func (m *MockGame) GameStatusProvider() GameStatusProvider {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GameStatusProvider")
	ret0, _ := ret[0].(GameStatusProvider)
	return ret0
}

// GameStatusProvider indicates an expected call of GameStatusProvider.
func (mr *MockGameMockRecorder) GameStatusProvider() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GameStatusProvider", reflect.TypeOf((*MockGame)(nil).GameStatusProvider))
}

// GetHistory mocks base method.
func (m *MockGame) GetHistory() []types.HistoryLine {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHistory")
	ret0, _ := ret[0].([]types.HistoryLine)
	return ret0
}

// GetHistory indicates an expected call of GetHistory.
func (mr *MockGameMockRecorder) GetHistory() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHistory", reflect.TypeOf((*MockGame)(nil).GetHistory))
}

// GetPlayer mocks base method.
func (m *MockGame) GetPlayer(name string) board.Player {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlayer", name)
	ret0, _ := ret[0].(board.Player)
	return ret0
}

// GetPlayer indicates an expected call of GetPlayer.
func (mr *MockGameMockRecorder) GetPlayer(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlayer", reflect.TypeOf((*MockGame)(nil).GetPlayer), name)
}

// GetTargetPlayer mocks base method.
func (m *MockGame) GetTargetPlayer(playerName, targetPlayerName string) (board.Player, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTargetPlayer", playerName, targetPlayerName)
	ret0, _ := ret[0].(board.Player)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTargetPlayer indicates an expected call of GetTargetPlayer.
func (mr *MockGameMockRecorder) GetTargetPlayer(playerName, targetPlayerName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTargetPlayer", reflect.TypeOf((*MockGame)(nil).GetTargetPlayer), playerName, targetPlayerName)
}

// IsGameOver mocks base method.
func (m *MockGame) IsGameOver() (bool, string) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsGameOver")
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(string)
	return ret0, ret1
}

// IsGameOver indicates an expected call of IsGameOver.
func (mr *MockGameMockRecorder) IsGameOver() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsGameOver", reflect.TypeOf((*MockGame)(nil).IsGameOver))
}

// IsPlayerWinner mocks base method.
func (m *MockGame) IsPlayerWinner(playerIdx int) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsPlayerWinner", playerIdx)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsPlayerWinner indicates an expected call of IsPlayerWinner.
func (mr *MockGameMockRecorder) IsPlayerWinner(playerIdx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsPlayerWinner", reflect.TypeOf((*MockGame)(nil).IsPlayerWinner), playerIdx)
}

// LastResult mocks base method.
func (m *MockGame) LastResult() GameActionResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LastResult")
	ret0, _ := ret[0].(GameActionResult)
	return ret0
}

// LastResult indicates an expected call of LastResult.
func (mr *MockGameMockRecorder) LastResult() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LastResult", reflect.TypeOf((*MockGame)(nil).LastResult))
}

// Mode mocks base method.
func (m *MockGame) Mode() types.GameMode {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Mode")
	ret0, _ := ret[0].(types.GameMode)
	return ret0
}

// Mode indicates an expected call of Mode.
func (mr *MockGameMockRecorder) Mode() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Mode", reflect.TypeOf((*MockGame)(nil).Mode))
}

// NextActiveTurnPlayer mocks base method.
func (m *MockGame) NextActiveTurnPlayer() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NextActiveTurnPlayer")
	ret0, _ := ret[0].(string)
	return ret0
}

// NextActiveTurnPlayer indicates an expected call of NextActiveTurnPlayer.
func (mr *MockGameMockRecorder) NextActiveTurnPlayer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NextActiveTurnPlayer", reflect.TypeOf((*MockGame)(nil).NextActiveTurnPlayer))
}

// OnCardMovedToPile mocks base method.
func (m *MockGame) OnCardMovedToPile(card cards.Card) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnCardMovedToPile", card)
}

// OnCardMovedToPile indicates an expected call of OnCardMovedToPile.
func (mr *MockGameMockRecorder) OnCardMovedToPile(card any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnCardMovedToPile", reflect.TypeOf((*MockGame)(nil).OnCardMovedToPile), card)
}

// PlayerIndex mocks base method.
func (m *MockGame) PlayerIndex(name string) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PlayerIndex", name)
	ret0, _ := ret[0].(int)
	return ret0
}

// PlayerIndex indicates an expected call of PlayerIndex.
func (mr *MockGameMockRecorder) PlayerIndex(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PlayerIndex", reflect.TypeOf((*MockGame)(nil).PlayerIndex), name)
}

// SameTeam mocks base method.
func (m *MockGame) SameTeam(i, j int) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SameTeam", i, j)
	ret0, _ := ret[0].(bool)
	return ret0
}

// SameTeam indicates an expected call of SameTeam.
func (mr *MockGameMockRecorder) SameTeam(i, j any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SameTeam", reflect.TypeOf((*MockGame)(nil).SameTeam), i, j)
}

// SetCanMoveWarrior mocks base method.
func (m *MockGame) SetCanMoveWarrior(value bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetCanMoveWarrior", value)
}

// SetCanMoveWarrior indicates an expected call of SetCanMoveWarrior.
func (mr *MockGameMockRecorder) SetCanMoveWarrior(value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCanMoveWarrior", reflect.TypeOf((*MockGame)(nil).SetCanMoveWarrior), value)
}

// SetCanTrade mocks base method.
func (m *MockGame) SetCanTrade(value bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetCanTrade", value)
}

// SetCanTrade indicates an expected call of SetCanTrade.
func (mr *MockGameMockRecorder) SetCanTrade(value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCanTrade", reflect.TypeOf((*MockGame)(nil).SetCanTrade), value)
}

// SetHasMovedWarrior mocks base method.
func (m *MockGame) SetHasMovedWarrior(value bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetHasMovedWarrior", value)
}

// SetHasMovedWarrior indicates an expected call of SetHasMovedWarrior.
func (mr *MockGameMockRecorder) SetHasMovedWarrior(value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetHasMovedWarrior", reflect.TypeOf((*MockGame)(nil).SetHasMovedWarrior), value)
}

// SetHasTraded mocks base method.
func (m *MockGame) SetHasTraded(value bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetHasTraded", value)
}

// SetHasTraded indicates an expected call of SetHasTraded.
func (mr *MockGameMockRecorder) SetHasTraded(value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetHasTraded", reflect.TypeOf((*MockGame)(nil).SetHasTraded), value)
}

// SwitchTurn mocks base method.
func (m *MockGame) SwitchTurn() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SwitchTurn")
}

// SwitchTurn indicates an expected call of SwitchTurn.
func (mr *MockGameMockRecorder) SwitchTurn() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SwitchTurn", reflect.TypeOf((*MockGame)(nil).SwitchTurn))
}

// TurnState mocks base method.
func (m *MockGame) TurnState() TurnState {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TurnState")
	ret0, _ := ret[0].(TurnState)
	return ret0
}

// TurnState indicates an expected call of TurnState.
func (mr *MockGameMockRecorder) TurnState() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TurnState", reflect.TypeOf((*MockGame)(nil).TurnState))
}
